### ISSUE TITLE
Cannot Run ImList.<T>of()?

### ISSUE THREAD

**Issue by hengyjj** [nus-cs2030/2122-s2#100]
# Description

Hello! I am not too sure why I am unable to run this ImList.<T>of() method in jshell. Below is my code. 
![image](https://user-images.githubusercontent.com/77519191/158558299-ab7f5899-5b50-48d8-9096-36e7fe0bb1a8.png)

I followed what the prof did in lecture..
![image](https://user-images.githubusercontent.com/77519191/158558482-6c79daee-29e0-4dc8-bb96-cb33529dba40.png)

## Topic:

Specific Topics this question is related to (If Any)

## Screenshots

Screenshots (if any)

**Comment by hwkchia** [comment]
I'm guessing that `ImList` has a dependency on something else... `Pair` perhaps?

**Comment by hengyjj** [comment]
Thank you Prof!
