### ISSUE TITLE
Level 2 Keyable Map

### ISSUE THREAD

**Issue by hengyjj** [nus-cs2030/2122-s2#103]
# Summary

Description of the question / problem here.

Hello. I am currently attempting Level 2 of Lab 6. We are supposed to create a KeyableMap that Module and Student class would extend from. However, I keep getting warnings when compiling the Module class after extending it from KeyableMap.

This is my constructor from KeyableMap that takes in a string and an immutable map.
```
KeyableMap(String key, ImmutableMap<String, V> map) {
    this.key = key;
    this.map = map;
}
```

This is the constructor from my Module class after it extends from my KeyableMap.
```
Module(String title, ImmutableMap<String, Assessment> tests) {
    super(title, tests);
    this.title = title;
    this.tests = tests;
}

```
This warning keeps popping up after I compiled the file. 
<img width="705" alt="image" src="https://user-images.githubusercontent.com/77519191/158942957-53c5ab3e-e1ae-4899-8d0b-1a1f4c043183.png">

I believe the error lies at the ImmutableMap in KeyableMap class which takes in a `<String, V>` ? But I am unsure of it too. Thank you for your help!

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by LauWyeRock** [comment]
I think you didn't specify the type of KeyableMap somewhere in your code

**Comment by jingyulim1** [comment]
It seems like you didn't specify what V would be in Module/Student (when you extends KeyableMap). As such, when compiling, the compilier is not sure that you used a class that indeed extends Keyable.

**Comment by hengyjj** [comment]
> It seems like you didn't specify what V would be in Module/Student (when you extends KeyableMap). As such, when compiling, the compilier is not sure that you used a class that indeed extends Keyable.

Hi Jing Yu. By specifying, do you mean like this?

`
class Module<V> extends KeyableMap {
}

`

**Comment by jingyulim1** [comment]
What i meant was for example. `class Module extends KeyableMap<V> `  <- Make sure you fill in the V with the correct class that extends Keyable.

**Comment by hengyjj** [comment]
> What i meant was for example. `class Module extends KeyableMap<V> ` <- Make sure you fill in the V with the correct class that extends Keyable.

I see. Thank you Jing Yu!
