### ISSUE TITLE
PriorityQueue issue at Level 3

### ISSUE THREAD

**Issue by hongyaong** [nus-cs2030/2122-s2#107]
# Summary
Did any face this issue where a waiting customer gets serves first before the server is done serving the customer?

## Description 
I am wondering if it is my EventComparator problem but i'm not sure. As you can see my in my output at time 1.500 shows "2 serves by 1" first but it is suppose to be "1 done serving by 1" that comes first.
<img width="261" alt="image" src="https://user-images.githubusercontent.com/25282511/159107014-31681c3d-896c-4b02-a4f1-ba437da3ccce.png">
![Untitled](https://user-images.githubusercontent.com/25282511/159107044-62a1fa77-4f93-42c9-8ece-4e052f1a5218.png)

**Comment by eesung00** [comment]
I think your EventComparator might need to find a way to deal with the priority of event that come first when the event time is the same. Your event flow probably have some minor bugs too (not sure) since if "1 done serving by 1" does not come first, 2 cant be serve by 1.

**Comment by hongyaong** [comment]
hey @eesung00 thanks so much, i changed my event comparator to deal with that and it worked now :)
