### ISSUE TITLE
What value of type V should orElse return if the Optional is empty?

### ISSUE THREAD

**Issue by JhChee18** [nus-cs2030/2122-s2#109]
For the `getGrade(String student, String module, String assessment)` method in the Roster class, I am using `get()` method defined in KeyableMap class to retrieve the appropriate Optional<V>. In order to get the V, I am using `orElse<V v>` to extract the value. However, since the return value should be type V, what should I return if the Optional is empty?

**Comment by LauWyeRock** [comment]
You should return a String. You can check the test cases out to see the format they want - should be something like "No such record: Name Module Assessment"

**Comment by szeying02** [comment]
`orElse("No such record: ....` would be sufficient!

**Comment by JhChee18** [comment]
Thank you all for answering! Despite my original code implementation was wrong, I managed to get it correct now. Thanks. In short, the `getGrade(...)` should be implemented by using `flatMap `and `map`, then only check it at the end using `orElse(...)`. Thanks!
