### ISSUE TITLE
level 4 

### ISSUE THREAD

**Issue by wk1267** [nus-cs2030/2122-s2#111]
# Summary
Hi I have successfully implemented levels 1 to 3 for the lab, but am facing an error when trying to pass level 4's add functionality.
The error comes out when the existing module or the assessment is different from the one being added. Instead of adding the new Student/module/assessment/grade, it _replaces_ it instead.  

In my current faulty code, my code more or less just uses the .put(xxx) method, which I thought should add, but it turns out that it replaces whatever has been there previously. Can any kind soul bless me with an explanation or some pseudocode? Thank you 

Screenshots (if any)
<img width="428" alt="Screenshot 2022-03-19 at 11 42 12 PM" src="https://user-images.githubusercontent.com/97509680/159127944-7d9c1ca4-bc5c-439a-b83a-c1390eac882d.png">

**Comment by loqir** [comment]
hi, you can think of it as you have to consider whether the student exists in the immutable map. if not, you can directly put a new student into the map. However, if the student already exists in the map, im not sure if what i did was the most efficient but i created a new student and then put the student back into the map. Likewise for the module, you will have to check if the module already exists in the map.

**Comment by Darien2307** [comment]
Hi, I think @loqir has given a very detailed planning of the method, just want to add on: 
`Student stud = this.get(studName).orElseGet(() -> { return new Student(studName); });`
The above optional method was useful to me in the checking processes.
Hope it helps!

**Comment by wk1267** [comment]
Thank you kind souls. I have gotten the correct results on jshell using orElse(), which is a variant of the method @Darien2307 shared above.

**Comment by Darien2307** [comment]
Yup, orElse() is one of the main useful methods your respective lab sessions would have shared with you. 
Good to hear that!
