### ISSUE TITLE
Lab 6 Level 5

### ISSUE THREAD

**Issue by loqir** [nus-cs2030/2122-s2#112]
does anyone know for lab 6 level 5, are we supposed to use a main method and deal with arrays, scanners and lists to split the string inputs?

**Comment by Ohnojiso** [comment]
Yes. You can try referring the Java API & check the taxi example in the multimedia videos regarding all these stuff.

**Comment by loqir** [comment]
i see thanks!

However , I am facing an error  "Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1" upon an integer input after calling java Main.

**Comment by LauWyeRock** [comment]
I don't think you should use arrays and lists, in case codecrunch rejects your solution. As for the error, I think it is just about how you structured your main method, maybe you can elaborate on how ur main method works?

**Comment by loqir** [comment]
oh in that case how did you manage to get each individual string without using arrays and lists?

**Comment by LauWyeRock** [comment]
Scanner::next() identifies tokens, so if the entire string has 4 words and you use .next() 4 times it will automatically separate the string for you

**Comment by Ohnojiso** [comment]
> manage

If you want to get the individual String just use sc.next(). If you mean that you want to store these values in a list, then just use ImList as in prev labs.

**Comment by loqir** [comment]
Alright thanks so much for the help everyone!
