### ISSUE TITLE
method references detected

### ISSUE THREAD

**Issue by wk1267** [nus-cs2030/2122-s2#113]
Good day folks. It is me again with a new error. My code works on jshell and also compiles successfully. But on codecrunch, they tell me that method references are detected. 

Has anyone faced a similar issue before? some methods i used: .put(xxx), orElse(xxx), get(xxx), and (flat)mappers. 
I never used Optional's .get(), .isEmpty() or .isPresent().

<img width="349" alt="Screenshot 2022-03-20 at 12 20 56 AM" src="https://user-images.githubusercontent.com/97509680/159129406-ac7c24a7-92e6-4412-867f-7c319016f0a6.png">

**Comment by wxlim26** [comment]
I had this error too when I used .map(Assessment::getGrade). The error disappeared once i swapped over to .map(x -> x.getGrade()).

**Comment by wk1267** [comment]
Thank you kind soul. Indeed, that was the issue.
