### ISSUE TITLE
 Optional.orElse() vs Optional.orElseGet()

### ISSUE THREAD

**Issue by Noel-Lee** [nus-cs2030/2122-s2#117]
Not very sure about the difference in usage of the two Optional class methods and when to use them

**Comment by Kent-twl** [comment]
orElse() takes any parameter of a type T, whereas orElseGet() accepts a functional interface of type Supplier that returns an object of type T

Here is a thread from stackoverflow if you still have more queries
https://stackoverflow.com/questions/33170109/difference-between-optional-orelse-and-optional-orelseget

**Comment by Noel-Lee** [comment]
Oh I see thank you :)
