### ISSUE TITLE
How to read from stdin

### ISSUE THREAD

**Issue by wzs02** [nus-cs2030/2122-s2#119]
# Summary

Description of the question / problem here.

## Description: 
Hi all,  as above, I am having difficulties reading input from the scanner class for level 5. Would appreciate some hints as to how I can read the lines
12
Jack   CS2040 Lab4    B
Jack   CS2040 Lab6    C
Jane   CS1010 Lab1    A

as specified on level 5. When I checked online for a solution, most suggested using a delimiter and using a loop to separate elements in the string but this does not seem applicable here because we must pass the name, module, test and grade into the function all at  once.

Clarifications or details with respect to the issue you are facing

## Screenshots

Screenshots (if any)

**Comment by szeying02** [comment]
Hello! You can consider initialising the scanner first:

`Scanner scanner = new Scanner(System.in)`

Then, proceed to read the first integer: `int n = scanner.nextInt()`

After that, you'd want to read each line by line. As there are a total of n of these lines with name, module, test, grades, you can consider setting up a for loop to loop through 0 to < n, and take into all four tokens at the same time.

```
for (int i = 0; i < n; i++) {
            String student = scanner.next();
            String module = scanner.next();
            ... // repeat for the test and grade then proceed to add all of these to your roster!
}
```

**Comment by wzs02** [comment]
Thanks for the detailed instructions! I tried implementing it but strangely I get a "D" appended to the end of my first query, which has probably got to do with the ctrl d that I used to terminate the input. So instead of "B C A+..." I got  "BD C A+...".  I produced this output by doing: an infinite loop involving scanner.hasNext(), and appending the result of getGrade() to a string., which I printed out at the very end (after the infinite loop was terminated). How should I go about resolving this?

**Comment by szeying02** [comment]
I had the same issue as well, I believe it may be a glitch on the jshell side of it? It was accepted when I submitted it on codecrunch.

**Comment by alantay11** [comment]
You can try adding sc.nextLine(); at the end of your loop

**Comment by wzs02** [comment]
I see, thanks for the help everyone!

**Comment by adityajirafe** [comment]
I got the same bug, but yea it gets accepted on code crunch so not to worry. you can refer to this link for more details as to why the D appeared. tldr the terminal overwrites the caret so its not sth to worry about 
https://stackoverflow.com/questions/25756825/ctrl-d-on-mac-terminal-outputs-a-d-character
