### ISSUE TITLE
Level 5 toString()

### ISSUE THREAD

**Issue by just-LB** [nus-cs2030/2122-s2#130]
# Summary

Description of the question / problem here.

## Description: I'm having trouble trying to code the toString() method for Module as my key is always printed inside the outermost curly braces. 

for example:
instead of printing CS2040: {{Lab1: B}}
my code prints CS2040: {CS 2040 = {Lab1: B}}
 
 Anyone has hints? 

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by ignatiustan123** [comment]
you probably need to code the toString using the getKey() and getValue() methods

**Comment by jlee1007** [comment]
Yep use the key and values to code the toString so you can set it manually! If not it will give the = which is the default

**Comment by mk2905** [comment]
can try using an ImList to loop the values in the ImmutableMAp and add it to a new ImList, then loop the values in the ImList to form a big String of values and then add it to your String.format, i hardcoded the commas, not sure if there's a more efficient method
