### ISSUE TITLE
Issues when Loading Main2.java in Level 2

### ISSUE THREAD

**Issue by hengyjj** [nus-cs2030/2122-s2#136]
# Summary
Put a summary of the question

## Description 
Hello! I was attempting Level 2 of the Project and I was trying out the test cases and it passed successfully. However, when I downloaded the Main2.java and try to run in terminal, it pops up error like this. I submitted onto Codecrunch and there was no issue. So I am just curious what is causing this error. 

Thank you!

<img width="932" alt="image" src="https://user-images.githubusercontent.com/77519191/159662742-fdf9a5b3-1323-41a3-9ff1-ab66b1ec8dbe.png">

## Screenshots (if any): 
Insert Images here if necessary

**Comment by LauWyeRock** [comment]
did you type in ^D cause i think youre just supposed to ctrl D

**Comment by hengyjj** [comment]
> did you type in ^D cause i think youre just supposed to ctrl D
I typed in Crtl D and this error appears too.


<img width="937" alt="image" src="https://user-images.githubusercontent.com/77519191/159683454-00131dce-a74c-470b-ba4e-861dd4e3b38e.png">

**Comment by LauWyeRock** [comment]
I havent seen this before but did you package your Simulate2?

**Comment by daitenshionyan** [comment]
Try `^Z` (ctrl + z) enter.

**Comment by hengyjj** [comment]
> I havent seen this before but did you package your Simulate2?

Thank you for your help! I managed to find the error. I stored the file initially within the simulator folder together with Simulate2. I shifted the Main2.java to outside of the simulator folder.
