### ISSUE TITLE
Class not found Level 2

### ISSUE THREAD

**Issue by tungkei** [nus-cs2030/2122-s2#139]
hi, if we want to use ImList do we just have to do import cs2030.util.ImList; and can use it already? 
My Shop class is compilable and I can run this first test case on jshell just with the Server and Shop class

![image](https://user-images.githubusercontent.com/99954534/159756057-c52e3e00-fb92-4a61-b264-12f7e70fd575.png)

but when I submit to codecrunch with the other files like Event I keep getting this error that the Shop class is not found
![image](https://user-images.githubusercontent.com/99954534/159756418-484ea821-c89b-435f-95ce-e478f21f6378.png)

**Comment by hengyjj** [comment]
Yup. Just import cs2030.util.ImList will do. Maybe you could into your EventStub and Shop class? The error is saying the location is in Class EventStub.

**Comment by tungkei** [comment]
> Yup. Just import cs2030.util.ImList will do. Maybe you could look into your EventStub and Shop class? The error is saying the location is in Class EventStub.

The error is actually in both Event and EventStub, both are the same error about Shop class not found (error in EventStub because it implements Event but error in Event so like ecf), but I copied what they gave for Event interface though.

**Comment by michael192002** [comment]
Maybe if possible you could check incrementally (put each class one by one into jshell, see at what point the implementation breaks), and make sure that the dependency is correct (e.g. put Pair before ImList, etc.)
