### ISSUE TITLE
Restricted API on the use of Collection Interface on Codecrunch

### ISSUE THREAD

**Issue by gypsyxx** [nus-cs2030/2122-s2#141]
I noticed that my code was not able to run on codecrunch as I may have used collection interface outside of ImmutableMap but I'm not sure if we are able to use it under KeyableMap as my toString requires me to loop through every value in the map.

**Comment by michael192002** [comment]
I think you might be able to use e.getValue() to retrieve the value in the iteration, and e.getKey() for the key in the iteration in place of the Collection interface (more details on problem description Lab 5).

**Comment by ReganKvioke** [comment]
For Lab 6, I believe you can import and use the Collections class in ImmutableMap, however, you should not be using this.map.values() to get the values. Erm you should use the looping method, maybe refer to level 4 of Lab 5?

**Comment by gypsyxx** [comment]
Thanks @ReganKvioke and @michael192002
