### ISSUE TITLE
Compilation Error for level 2 when running in code crunch

### ISSUE THREAD

**Issue by joannelxl** [nus-cs2030/2122-s2#142]
Hi for lab 6 level 2, does anybody know why theres this compilation error when i run in codecrunch?

![image](https://user-images.githubusercontent.com/79855907/159912816-d38a9e11-d0ee-49eb-9ba8-e83d10491466.png)

**Comment by LauWyeRock** [comment]
try changing it to a small v?

**Comment by eesung00** [comment]
Its a checkstyle error, change your variable name to v as suggested by @LauWyeRock should be fine

**Comment by joannelxl** [comment]
thank u all! i solved it :)
