### ISSUE TITLE
Queries about static constructors

### ISSUE THREAD

**Issue by rachtan27** [nus-cs2030/2122-s2#146]
# Description

Hi I am still not very sure why there is a need to create static constructors such as : static <T> Lazy of(T value) to instantiate a Lazy object.....
why can't we instantiate using the "normal constructor" Lazy(Supplier<T> supplier)? (which is made private)

## Screenshots

![image](https://user-images.githubusercontent.com/100123345/160043517-dbb65142-f1e7-4802-9991-1c82dbcf2912.png)

**Comment by junbin-tan** [comment]
i'm not sure if I am correct but, it might be because we want to catch if a null is passed in?

**Comment by lukasleeyo** [comment]
I think it's because we want to use it the way such that it is like ``class.method()`` and the method must be static if we want call it via the class.
A good example would be the ``List.of("1", "2");``

So for this case, you will use ``Lazy.of(supplier);`` to create a Lazy object and initialize the supplier attribute.

**Comment by wk1267** [comment]
Does this mean there's technically nothing wrong with making the private constructor public, which allows us to use New List(Supplier s), other than idk programming norms?

**Comment by hwkchia** [comment]
There's also a design perspective to consider.  A factory method allows us to do some pre-processing before committing to creating the appropriate object.  Following single responsibility, the constructor should only due with the creation of the object, and we let the factory method handle the preprocessing part.

**Comment by rachtan27** [comment]
ohhh okayyy thank you prof and everyone !!!!
