### ISSUE TITLE
Level 2 Shop Class

### ISSUE THREAD

**Issue by rachtan27** [nus-cs2030/2122-s2#149]
# Summary
Hi i am struggling with creating the Shop class that takes in a list of server.

## Description 
I am trying to put the List<Server> of server into a private final ImList<Server>. but i keep receiving the error shown below? anyone else faced this problem as well?
I do not understand why the implementation works in jshell but not in the class Shop....

## Screenshots (if any): 
Compile Error from javac Shop.java
![image](https://user-images.githubusercontent.com/100123345/160183628-5b257af8-beb2-426e-9fcc-e8cab168a22b.png)

Tested my idea in jshell and works...?
![image](https://user-images.githubusercontent.com/100123345/160184213-4f89e427-5f37-4302-90d2-5c1774bb8e71.png)

**Comment by calvinseptyanto** [comment]
Perhaps check your class attribute "serverImList" make sure it's a correct type

**Comment by rachtan27** [comment]
Hi, my TA helped me resolved the issue!
the problem was because I was using Pair.java and ImList.java from prevous labs and their static methods were not made public, unlike the ones provided in codecrunch!

so the solution is to just download the Pair.java and  ImList.java by clicking on them in codecrunch:
![image](https://user-images.githubusercontent.com/100123345/160240961-978a1d04-4fa2-46a1-bfa3-f1f4ed52f79b.png)
