### ISSUE TITLE
Lab 7 Level 4 UnaryOperator

### ISSUE THREAD

**Issue by lyjm21** [nus-cs2030/2122-s2#151]
# Summary

Unsure of how to apply map function to a stream of a list following the rules in the question

## Description:

For level 4, my approach is to convert the list to a stream by using .stream() , before using .map() and collecting it at the end. However, I am not sure about the syntax of mapping selected elements to follow the 
game of life rules. Should I define another function that checks if the cell will die next round? Or is it possible to put my conditions in the map function itself, because i have to check the numbers adjacent to the list?  Or should I approach the level differently (im not sure if we can map selectively with the map function...)?

For example, the code ive attached maps all the elements in the list to 1. 
<img width="889" alt="Screenshot 2022-03-26 at 2 14 13 PM" src="https://user-images.githubusercontent.com/100070009/160227863-e4661b2a-7813-45dd-88e2-4046d06e456c.png">

Thank you!

**Comment by zmchang3009** [comment]
Hi! Personally I think it is easier to make use of List indexing to check whether the cells will be alive, because we need to consider the adjacent cells. But I think there might be alternatives with Streams too.

As for mapping selectively, I'm not sure if this works but maybe something like
```java
.map(x -> somePredicate(x) ? someMethod(x) : x)
```
might do the trick?

Hope this helps!

**Comment by tlylt** [comment]
You can try creating helper classes/methods to help consolidate the checking logic and then call it within the stream pipeline

**Comment by BotBw** [comment]
maybe try to construct an `IntStream` containing the previous round indices and use a local `IntUnaryOperator` as a mapper?

**Comment by lindyapeintern** [comment]
Hey there guys, could someone explain what's the idea behind level 4? I don't really know how to start

**Comment by lyjm21** [comment]
Hello! The UnaryOperator in this qn essentially takes in a List of Integers with 0 and 1 inside, and should return an updated result for the next stage for the game of life. For example,

UnaryOperator a = x -> x + 1

When we put a.apply(1) in jshell, it gives a result 2.

For this question, perhaps you could consider using some helper functions to manipulate the list first. 

So instead of manipulating an integer we are dealing with a list of integers this time. Hope this helps!
