### ISSUE TITLE
Lab 6 Level 3

### ISSUE THREAD

**Issue by Zhenyubbx** [nus-cs2030/2122-s2#152]
# Summary

 "get" method could not be found after calling roster.get("Tony").flatMap(x -> x.get("CS1231"))

## Description:

I have been stuck at this level because I am not sure why when I chain a flatMap function after calling roster.get("Tony").flatMap(x -> x.get("CS1231")), I got an error (Screenshot attached below) that says my "get" method could not be found. When I call roster.get("Tony"), it returns optional[tony]. When i proceed on to chain a flatMap method on this, wouldnt it be using tony.get("CS1231")? If i call tony.get("CS1231"), it works to return me the module for cs1231 as well. Quite puzzled why the "get" method could not be found. 

Appreciate if anyone can help out with this issue!! :)

## Screenshots

![image](https://user-images.githubusercontent.com/79489486/160229423-cb9ac0a6-64b4-4666-aea4-ab3e3626754f.png)

![image](https://user-images.githubusercontent.com/79489486/160229425-8e21a334-104b-4cff-ac3f-67c1997d5d6d.png)

![image](https://user-images.githubusercontent.com/79489486/160229540-c8d95022-b1bf-42fc-8e99-7305153f81f6.png)

**Comment by danyelys** [comment]
since roster.get("TONY") returns an optional, i think can try roster.get("Tony").orElse( alternate return) function that gets the value from an optional object.

**Comment by tlylt** [comment]
Perhaps can you try `roster.get("Tony").flatMap(x -> System.out.println(x));` to double check what is `x` when this call executes?

**Comment by nanfang02** [comment]
hiii i have this error before too..it is related to your get function in other classes, most probably KeyableMap or ImmutableMap. Previously my get function was Optional<Object> get(Object o )  and I changed it to Optional<T> object get(T t) as Object was too generalised in a sense. 
Hopefully it works for you too!

**Comment by Zhenyubbx** [comment]
Yep, it finally works! Thanks everyone for all the help, really appreciate it :)
