### ISSUE TITLE
Calling supplier.get() too early

### ISSUE THREAD

**Issue by bryanwonggy** [nus-cs2030/2122-s2#153]
Basically, for level 6 of the project, I managed to clear all the test cases except for the last one and the issue that I discovered was that basically, I'm calling the supplier.get() too early so the input for my customers' service time is wrong. (e.g. customer 4 taking the service time of customer 6 because 4 'waits' first, but is served after customer 6 because the server for 6 is done earlier than that for 4. 

Does anyone know how to approach this issue? Or how to approach this level in general?

Thanks in advance.

**Comment by danyelys** [comment]
Try using supplier.get() only when the serveEvent is being printed. I had this issue too because my waitEvent used my supplier.get() which resulted in the same problem. What i did was removed supplier.get() from my waitEvent execute method and only updated my shop in the ServeEvent.

**Comment by sinteary** [comment]
@danyelys Hi, just wondering how you managed to only call `supplier.get()` in the ServeEvent? In my current implementation, I am calling it in WaitEvent because we need to compute how long a customer must wait in the queue before it is served so that we can return the next ServeEvent, which requires knowing the service times of the customers ahead of itself

**Comment by bryanwonggy** [comment]
> 
I faced the same issue as you and I still can't solve it. I tried to make use of another way of implementation, e.g. 
Serve -> Done
Wait -> Empty
Done -> Serve (basically when the server is done serving, check his waitingList for the next service)

I could get the results but the issue I have now is with cyclic dependency because Serve -> Done -> Serve.

**Comment by danyelys** [comment]
@sinteary 
for my implementation, the wait event executes returns an optional. empty, but returns an updated shop of a waiting customer. The serve event for the waiting customer is then added to the PQ in the simulate class. In the simulate class as we loop through each event we should check if the event is a done event. If the event is a done event, we should then check if the server of the done event has customers waiting on him, if there is a customer waiting then id create a serve event and add it into the PQ. Let me know if its not clear!

**Comment by danyelys** [comment]
@bryanwonggy initially i had the same issue, so instead of using done to return serve, id use simulate class to check if event is a done event and the add a serve event into the PQ.

**Comment by sinteary** [comment]
@danyelys How did you check if the event is a DoneEvent? From what I understand, using `instanceof` in a class outside of the class itself is not allowed :(

**Comment by LohYangXian** [comment]
> 
Hi ! perhaps you can try adding identifiers to your different events (maybe assign an integer to each type of event)

**Comment by danyelys** [comment]
@sinteary yup like @LohYangXian said, i had an identifier for each event which was and then a getEventID function in every event

**Comment by sinteary** [comment]
@LohYangXian @danyelys Thanks for the suggestion! I have tried using an Enum to represent the event type and I've gotten it to work :)

**Comment by bryanwonggy** [comment]
@sinteary @LohYangXian @danyelys i managed to solve it by creating a new class called TryToServe. whenever there's a wait, the execute of the wait will give a try to serve, so it's kinda like recursive until the customer gets served. let me know if u need more details!

**Comment by sinteary** [comment]
Hi @bryanwonggy, thanks for responding! I think that your implementation sounds more intuitive, so I have tried implementing my own version of it as well. What I do is dequeue the customer from the server in the `WaitEvent`, check if the dequeued customer matches that of the WaitEvent. If so, I return a ServeEvent, and otherwise I return a PendingServeEvent (similar to your `TryToServe`). We get the server's next available time from the shop to ensure that the timing of these events are correct. The PendingServeEvent has the same `execute` logic as WaitEvent, but returns an empty string in the `toString` (which is excluded from the simulation output). Ideally, PendingServeEvent inherits from WaitEvent since the `execute` logic is the same, but I found that doing this still results in a cyclic dependency that CodeCrunch rejects, so I have no choice but to simply duplicate the code. Just putting this here for anyone who might be interested!

**Comment by duofeng0110** [comment]
> Hi @bryanwonggy, thanks for responding!
> 
> I think that your implementation sounds more intuitive, so I have tried implementing my own version of it as well. What I do is dequeue the customer from the server in the `WaitEvent`, check if the dequeued customer matches that of the `WaitEvent`. If so, I return a `ServeEvent`, and otherwise I return a `PendingServeEvent` (similar to your `TryToServe`). We get the server's next available time from the shop to ensure that the timing of these events are correct. The `PendingServeEvent` has the same `execute()` logic as WaitEvent, but returns an empty string in the `toString` (which is excluded from the simulation output).
> 
> Ideally, `PendingServeEvent` inherits from `WaitEvent` since the `execute()` logic is the same, but I found that doing this still results in a cyclic dependency that CodeCrunch rejects, so I have no choice but to simply duplicate the code. Just putting this here for anyone who might be interested!

Hi! May I know how did you update your Server in the PendingServeEvent? In my implementation I do not know how to get the event time for the next PendingServeEvent, if the current PendingServeEvent does not return a Serve event.

**Comment by duofeng0110** [comment]
> @sinteary @LohYangXian @danyelys i managed to solve it by creating a new class called TryToServe. whenever there's a wait, the execute of the wait will give a try to serve, so it's kinda like recursive until the customer gets served. let me know if u need more details!

Hi Bryan, 

> @sinteary @LohYangXian @danyelys i managed to solve it by creating a new class called TryToServe. whenever there's a wait, the execute of the wait will give a try to serve, so it's kinda like recursive until the customer gets served. let me know if u need more details!

Hi Bryan, how do you update the Server and get the next available time to serve in your TryToServe class without invoking the supplier.get() method in Customer's serving time? e.g. I have a Server with 2 people on the queue, how do I know when will it next be available, after the first customer is done? Thanks!

**Comment by ryougi1702** [comment]
I have the same question as duofeng as well. Would very much appreciate an explanation, I have been racking my brains all day over this and have not come up with a way to implement this TryToServe without messing up my event ordering.

**Comment by ongyongen** [comment]
hi, when you mention this, do you mean only calling it in the update method of serveEvent? I'm currently doing so but everything matches (up to the value for the statistics generated) except the last few cases where I think I called get() too early too.

> Try using supplier.get() only when the serveEvent is being printed. I had this issue too because my waitEvent used my supplier.get() which resulted in the same problem. What i did was removed supplier.get() from my waitEvent execute method and only updated my shop in the ServeEvent.

**Comment by sinteary** [comment]
Hi, sorry for the late reply. I used `Lazy` to cache the serving time for each customer. The server's next available time is updated in the ServeEvent, when it begins to serve the customer.
