### ISSUE TITLE
Reduce function takes in 2 arguments vs 3 arguments

### ISSUE THREAD

**Issue by Noel-Lee** [nus-cs2030/2122-s2#159]
Not very sure regarding the use cases for these two reduce functions

**Comment by dapscc** [comment]
from what i understand, the 2 argument reduce function gives a result of type T, where T is the type of the stream elements. for example, adding a stream of integers together to get an integer
on the other hand, the 3 argument reduce function gives a result that is not necessarily of type T through applying the accumulator argument to them, then combining them with the combiner argument

**Comment by jingyulim1** [comment]
Usually for streams, we use the reduce with 3 agruments when working with parallel streams.

Lets say I want the sum of the Stream.of(1,2,3,4) with each element multiplied by 3.

Without parallel stream:

![image](https://user-images.githubusercontent.com/95527957/160269436-691f3a69-6e80-40cd-bab7-c45c095a1f5e.png)

With just the accumulator, we can simply accumulate the seed with 3 times the value of each element of the stream.

With parallel stream:

![image](https://user-images.githubusercontent.com/95527957/160269452-9ec4598c-b421-49a1-b1bb-faa7ad2d7dcd.png)

We accumulate the seed with each of the element, before combining them(of the same type) together.

![image](https://user-images.githubusercontent.com/95527957/160269405-e42f823b-14a4-4c68-8aff-c300f7afd707.png)

It seems like the 3rd argument will be ignored if you use the reduce with 3 arguments when not in parallel.

![image](https://user-images.githubusercontent.com/95527957/160269805-114cf739-4618-460c-81d6-4e0748e4a831.png)
