### ISSUE TITLE
Lab 6 Level 4

### ISSUE THREAD

**Issue by Zhenyubbx** [nus-cs2030/2122-s2#166]
# Summary

Roster became empty after calling "add" method

## Description:

Not really sure why the roster became empty after I called my "add" method. It returns the correct output but the roster variable became empty. Would appreciate any suggestion and help with this issue, thank you!

## Screenshots

![image](https://user-images.githubusercontent.com/79489486/160351780-6b57e3de-c242-4902-9974-d98a01a2f7b5.png)

**Comment by gordengorden** [comment]
Hi zhenyu, could you show your add method?

**Comment by jamietan123** [comment]
I think the problem is in your add method

**Comment by undeser** [comment]
Hi Zhen Yu, I believe the problem might lie within your add method. Ensure that your add method returns a new roster.

**Comment by zendenleong** [comment]
Hi Zhen yu, I agree with @undeser. The problem most likely lies with the add method. Do remember to follow immutability at all times. Your add method for roster should return a new roster after every addition of a student.

**Comment by junbin-tan** [comment]
Hi Zhen yu, I agree with @undeser @zendenleong. But I think you might want to look at you constructor as well, as it when you return a new roster the constructor might be returning an empty one instead. Hope that helps.

**Comment by mamayuan** [comment]
To give you more help, i believe there is definitely something wrong with your add method. Your add method returns a new Roster. To do that, I think you should create an overloaded constructor method that takes in an identifier and a Student, and use that method to create the new Roster object you need to return.

**Comment by ReganKvioke** [comment]
I agree with all that says it is about the add method. You can take a look at it and make sure the types you are returning is correct.

**Comment by chloeoxe** [comment]
I agree with the rest! The problem likely lies within your add method. Check that it returns a new updated roster at the end. It would help to have an overloaded roster constructor!

**Comment by Zhenyubbx** [comment]
Thanks everyone for the help! It has been resolved! Turns out the problem lies in my Immutable map file :/
