### ISSUE TITLE
Lab 7 level 4

### ISSUE THREAD

**Issue by lindyapeintern** [nus-cs2030/2122-s2#167]
# Summary

Description of the question / problem here.

## Hey guys, I just reached level 4 of Lab 7 and have no idea how to even begin. Any clues/hints would be appreciated. 
Do I have to know the rules of John Conway's Game of Life? 

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by lyjm21** [comment]
Hello! The rules are included on codecrunch itself; its essentially an algorithm. So the UnaryOperator essentially takes in a List of Integers with 0 and 1 inside, and should return an updated result for the next stage for the game of life. For example,

UnaryOperator<Integer> a = x -> x + 1

When we put a.apply(1) in jshell, it gives a result 2. 

So instead of manipulating an integer we are dealing with a list of integers this time. Hope this helps!

**Comment by giffordlee** [comment]
Hi! Adding on to the above, you can use a helper function that takes in the index and the list, this function will tell you whether that integer at that index is 1 or 0 in the next generation. Then under generateRule, you can stream through the indexes of the list and map each index to the next generation integer using the helper function

**Comment by szeying02** [comment]
The way I did the question was to first determine what the next value for a value in the list of integers should be, so example: 
```
[0,1,0]
//I indexed through each value to determine what the subsequent generation will be, so the first 0 after going through the rules would be 1 etc.
```

Next, I mapped these values into a new list and returned this as a lambda function / UnaryOperator under generateRule()

In the gameOfLife, I iterated through the list and mapped them into "*" or " ".

Hope this helps!

**Comment by kaitlyngoh** [comment]
Hi! you can try to incorporate the rules into the unary operator, what i did was to take in the List<Integer> of cells and then map the "state" (whether dead or alive) to the next generation depedning on the rules given. for the gameOfLife() part you can make use of iterate and limit to keep looping to get the next generation, then convert them into a string (i used map)

**Comment by LohYangXian** [comment]
Hi! You can try to break down level 4 into smaller steps. 

for generateRule(), we will be creating a Unary Operator that generates the next generation of List<Integer> from the previous generation (the input List<Integer>). This can be done using Stream and lambda, which we have learnt in the previous levels.

for gameOfLife(), we will be iterating the initial given List<Integer> through the unary operator by n times to get each nth generation. After which, the result will be converted into a stream of strings ( which i used a helper function to map)

hope this helps!

**Comment by lindyapeintern** [comment]
Thanks all. Appreciate the assistance!
