### ISSUE TITLE
LSP and overriding

### ISSUE THREAD

**Issue by yongchein-o** [nus-cs2030/2122-s2#17]
# Description
I'm quite confused about LSP and overriding. It seems to me that as long as you override you're violating LSP since you're changing the implementation and behavior of a method in the superclass. 

Edit: Additionally, isn't the definition very subjective. 
eg if the customers were very picky then the third son would violate LSP. So Only the son who brews beverages exactly like the father satisfy LSP (no overriding)

## Topic:

LSP & Overriding 

## Screenshots

Screenshots (if any)

**Comment by hwkchia** [comment]
Yes, you are absolutely right that LSP is very subjective when it comes to "expectations of the client".  With reference to the third son example as per week #3's lecture poll, the mention of the "customers not being picky" sets the expectations, and hence son C is substitutable.  If customers only expect the same type/taste of coffee/tea brewed, then C is not substitutable.  Expectations can be derived from the specifications of the problem statement; changing implementation in the child class based on overriding new behavior may or may not break expectations.
