### ISSUE TITLE
Helper function

### ISSUE THREAD

**Issue by gypsyxx** [nus-cs2030/2122-s2#172]
May I ask for the helper function for Level 4, can we use if-else statements to determine if the cell will be 1 or 0. As I am also thinking if we can use pipelines or ternary operators for this.

**Comment by rachtan27** [comment]
I personally did if-else to determine the cell as well

**Comment by LauWyeRock** [comment]
yeap both are possible

**Comment by gypsyxx** [comment]
@LauWyeRock for ternary operator in this case, would we need to have multiple ternary statements?

**Comment by LauWyeRock** [comment]
yea i had multiple ternary operators for mine

**Comment by jamietan123** [comment]
the ternary operator can look something like x -> x == 0 ? " " : "*"
