### ISSUE TITLE
Project Cyclic Dependencies

### ISSUE THREAD

**Issue by yjjjiajie** [nus-cs2030/2122-s2#178]
# Summary
Hi, so far I have tried to implement the events in such a way:

Arrive -> Serve/Wait/Leave Events
Serve Event -> Done Event
Done Event -> Rest Event
Rest Event -> Serve Event
Wait and Leave -> empty events

However, the serve,done,rest will have a cyclic dependency. I can't seem to think of another method. Does anyone have any method to get around this? Or how did you all implement the sequence of the events. Thank you very much in advance.

**Comment by Yang990121** [comment]
Maybe can do enum instead of different classes?
But i also not sure what is the correct structure

**Comment by LauWyeRock** [comment]
i dont think youre supposed to have a rest event

**Comment by mingshan2705** [comment]
I think your idea of implementing the RestEvent after DoneEvent is correct, but that leads to cyclic dependency. Maybe you could try to just update the status of your Server (if the server is resting or not) after the DoneEvent instead of creating a RestEvent.

**Comment by wk1267** [comment]
Hi, I faced a similar problem. I managed to circumvent it by transferring the logic of the Rest Event to the .run() method in Simulate. This allows you to have Rest class returning only empty events.

**Comment by yjjjiajie** [comment]
@mingshan2705 @wk1267 I guess for both of your implementation, your wait would return a Serve? Because for my implementation, even if I took out Rest, my serve will return done, and done will return serve so there's still a cyclic dependency

**Comment by wk1267** [comment]
@yjjjiajie the same transferring of logic can still work for the Done event. so Done returns empty, but in .run() it returns Serve

**Comment by yjjjiajie** [comment]
thank you so much for the help !
