### ISSUE TITLE
downloading VIM 

### ISSUE THREAD

**Issue by chelseayap02** [nus-cs2030/2122-s2#18]
![photo_2022-01-26_17-48-55](https://user-images.githubusercontent.com/91821234/151140930-4deaffa5-803c-4d5a-bac3-02e68536c370.jpg)

does anyone know how to resolve this issue? im using a ryzen software and idk if that is the problem. send help pls :(

**Comment by yongchein-o** [comment]
You probably need to enable virtualisation in your BIOS.

**Comment by chelseayap02** [comment]
i followed the steps to enable visualisation alr but i am still unable to run Ubuntu :(

**Comment by yongchein-o** [comment]
Hmmm I'm not too sure about that... Maybe you can see it this helps: 
https://askubuntu.com/questions/1264102/wsl-2-wont-run-ubuntu-error-0x80370102
