### ISSUE TITLE
Cannot find symbol Error

### ISSUE THREAD

**Issue by evewlim** [nus-cs2030/2122-s2#181]
hello! ive been getting this "Cannot find symbol" error (but it works when I upload my files codecrunch and I managed to clear the level?) in this case, i had to keep submitting without being able to test the cases myself. is there any way i could fix this or am i doing something wrongly? thanks in advance:-)

![image](https://user-images.githubusercontent.com/95474365/160873959-56bc7993-3c72-42e5-8d8a-67f6dae796d5.png)

**Comment by shanernigans** [comment]
hello, did you set your classes to public?

**Comment by tygq13** [comment]
Having the same issue.

**Comment by undeser** [comment]
Hi Eve, I agree with @shanernigans, did you remember to set your methods to public? Hope this helps!

**Comment by junbin-tan** [comment]
Hey there, agree with @shanernigans.

You may also want to take a look if you packaged the Customer in the simulator as well. Hope this helps!

**Comment by evewlim** [comment]
ohh i see thanks everyone for ur help:-)
