### ISSUE TITLE
Level 6 Test Case 6_3

### ISSUE THREAD

**Issue by szeying02** [nus-cs2030/2122-s2#183]
I'm facing this issue in level 6, where my event times are messed up possibly because I am called the `Lazy::get` for the service time too early. As a result, the wrong service times are allocated to the wrong customers. 

<img width="411" alt="Screenshot 2022-03-31 at 11 19 14 AM" src="https://user-images.githubusercontent.com/97298202/160969650-486a18d6-54b6-4b1b-864e-808ba2c803f1.png">

I use the `Lazy::get` in the `getQueueTime()` method in the server to get the total queue time of that particular server. The result of this method is then used to create the SERVE event. 

<img width="630" alt="Screenshot 2022-03-31 at 11 22 12 AM" src="https://user-images.githubusercontent.com/97298202/160969949-30e38e13-440d-456d-a0ed-dc80861d000b.png">

I believe this is the only time I'm calling it too early. Does anyone have any advice on how to workaround this?

**Comment by jingyulim1** [comment]
Since the service time of the customer is not known until he/she is being served, I don't think there is a way to calculate the queue time as the queue time depends on the service time of those customers who are waiting .

**Comment by szeying02** [comment]
> Since the service time of the customer is not known until he/she is being served, I don't think there is a way to calculate the queue time as the queue time depends on the service time of those customers who are waiting .

Oh... in that case how should we get the event time for the WAIT event?

**Comment by hongyaong** [comment]
Hi, I'm also facing this issue, what I don't understand is how does 4th customer done serving at 4.599 from 3.118, I thought its service time is 0.263761 from the input?
<img width="136" alt="image" src="https://user-images.githubusercontent.com/25282511/161185100-9c4a1938-1a77-4a51-94eb-e742903e306c.png">

**Comment by jingyulim1** [comment]
I did something similar to the folks [here](https://github.com/nus-cs2030/2122-s2/issues/178), where the .run() will add the serve instead of wait.
