### ISSUE TITLE
Project Level 1 EventComparator

### ISSUE THREAD

**Issue by morksen123** [nus-cs2030/2122-s2#188]
# Summary
Stuck at overriding compare method in EventComparator. My issue is I'm not sure how to compare the eventTime in the EventComparator class. Any hints for the compare method?

p.s my Event is an interface: 
class EventStub implements Event {}

## Description 
So far I've written
`class EventComparator implements Comparator<Event> {
      public int compare(Event event1, Event event2) { return Double.compare(...} 
}`

**Comment by LohYangXian** [comment]
hello! Since the compare method returns an int, maybe you can try to find a way to return an integer after comparing the eventTimes. for example, you can try assigning an integer value for different cases

**Comment by evewlim** [comment]
hello! like what @LohYangXian said, you should be returning an integer for the different cases! you can read the the compare method in the Comparator API for reference! i think the idea is slightly similar to the compareTo method in lab4 Booking class. hope this helps:-)

**Comment by morksen123** [comment]
> hello! like what @LohYangXian said, you should be returning an integer for the different cases! you can read the the compare method in the Comparator API for reference! i think the idea is slightly similar to the compareTo method in lab4 Booking class. hope this helps:-)

Since Event is an interface, how do I access the event time from event?

**Comment by jamietan123** [comment]
To access event time, maybe you can try having a getTime method. Hope this helps!

**Comment by evewlim** [comment]
> > hello! like what @LohYangXian said, you should be returning an integer for the different cases! you can read the the compare method in the Comparator API for reference! i think the idea is slightly similar to the compareTo method in lab4 Booking class. hope this helps:-)
> 
> Since Event is an interface, how do I access the event time from Event?

for me i made Event an abstract class since it says we could modify it (was a pass frm codecrunch)

**Comment by summerthia02** [comment]
for me , I took the idea off the comparator class we have done for lab4! so just need to compare event1.getTime() and event2.getTime(), if 1>2 return 1; else return -1. hope this helps!

**Comment by morksen123** [comment]
> > > hello! like what @LohYangXian said, you should be returning an integer for the different cases! you can read the the compare method in the Comparator API for reference! i think the idea is slightly similar to the compareTo method in lab4 Booking class. hope this helps:-)
> > 
> > 
> > Since Event is an interface, how do I access the event time from Event?
> 
> for me i made Event an abstract class since it says we could modify it (was a pass frm codecrunch)

Thanks for the heads up!

**Comment by jlee1007** [comment]
yep you can getTime() and compare the timings and return an integer
