### ISSUE TITLE
Does cs2030.simulator files have to be 'public'??

### ISSUE THREAD

**Issue by YohKato** [nus-cs2030/2122-s2#189]
# Summary
I tried to run Main2.java but it gave me the bottom errors. It was resolved after making the 'Simulate2' and its methods to public but I am not sure, whether I am supposed to do such. Do I need to set all the files to 'public'? Or else, how can I go around running Main2 without errors?

## Error 1: 

> $ jshell Simulate2.java Main2.java
> Main2.java:4: error: Simulate2 is not public in cs2030.simulator; cannot be accessed from outside package
> import cs2030.simulator.Simulate2;
>                        ^
> Simulate2.java:16: error: duplicate class: cs2030.simulator.Simulate2
> class Simulate2 {
> ^
> Main2.java:15: error: cannot access Simulate2
>         Simulate2 sim = new Simulate2(numOfServers, arrivalTimes);
>         ^
>   bad source file: ./Simulate2.java
>     file does not contain class Simulate2
>     Please remove or make sure it appears in the correct subdirectory of the sourcepath.
> 3 errors

## Error 2: 
When I go through the above error with making 'Simulate2' public, the following error happens also.

> $ java Main2 
> 1
> 0.5
> 0.6
> 0.7
> Exception in thread "main" java.lang.IllegalAccessError: failed to access class cs2030.simulator.Simulate2 from class Main2 (cs2030.simulator.Simulate2 and Main2 are in unnamed module of loader 'app') at Main2.main(Main2.java:15)

**Comment by jamietan123** [comment]
Yes all classes need to be public!

**Comment by shotnothing** [comment]
Specific to your error, did you compile everything you need yet? i.e. javac *.java in /simulator/

**Comment by rexlionz** [comment]
yup it should be public cos it's in another folder which is another directory

**Comment by alwinngjw** [comment]
Yup, just make everything public(Constructors, methods etc) and there should be no issues!

**Comment by summerthia02** [comment]
yes whenever it throws an error "not public in cs2030.simulator; cannot be accessed from outside package", change the class and its constructor to public !

**Comment by YohKato** [comment]
I see, thanks all for the help. I will try out with 'public' constructor and classes.
