### ISSUE TITLE
Project Level 3 WAIT class

### ISSUE THREAD

**Issue by ReganKvioke** [nus-cs2030/2122-s2#191]
## Description 
Hi all, I would like to ask how do we track the eventTime for the execution of the WAIT class?

For my code of WAIT, once the Server finishes serving one Customer, he would need to immediately serve the person who is waiting. However, how do we track the eventTime of this person since cannot execute WAIT until we have a Server that has finished serving?

**Comment by Swagston20** [comment]
when u get the wait event, you can execute by getting the server nextServiceTIming in the server

**Comment by LohYangXian** [comment]
Hi, you can consider adding a field in the Server class to track its next available time

**Comment by ReganKvioke** [comment]
@Swagston20 Do you mean like in my SERVER.java file, I have another function to return the nextServiceTime? Then call this in my WAIT.java file?

**Comment by Swagston20** [comment]
yessir

**Comment by ReganKvioke** [comment]
@Swagston20 Damn alright thank you! @LohYangXian Thanks thanks
