### ISSUE TITLE
Anyone know how to solve this hidden test case?

### ISSUE THREAD

**Issue by Yang990121** [nus-cs2030/2122-s2#192]
# Summary

I pass all the previous test cases, but for the hidden test cases I don't even know what are my problems
<img width="670" alt="Screenshot 2022-04-01 at 9 28 01 PM" src="https://user-images.githubusercontent.com/65878741/161273632-ad5e1657-b9a5-4d67-aa2b-1dde2cf8145d.png">

<img width="670" alt="image" src="https://user-images.githubusercontent.com/65878741/161273460-3f17c79a-3c9a-40d6-9792-8044ce8edb49.png">

**Comment by wxlim26** [comment]
I think if there is no previous room, you should return the current room.  Also, when you go from e.g Room A to Room B and bringing along a sword from A to B, you should remove the sword from room A. this removes the double count of swords when you go back from Room B to Room A.

**Comment by duofeng0110** [comment]
I have the same problem, still trying to solve it

**Comment by teresasee** [comment]
> I think if there is no previous room, you should return the current room. Also, when you go from e.g Room A to Room B and bringing along a sword from A to B, you should remove the sword from room A. this removes the double count of swords when you go back from Room B to Room A.

I agree with this ^ when i go to room B, I check whether I have taken a sword from room A. If yes, then the sword should be removed from room A because it should not be in A anymore if you brought it into B. I believe this should fix your error

**Comment by szeying02** [comment]
hello! i'm stuck on this part as well.

<img width="534" alt="Screenshot 2022-04-02 at 11 40 34 PM" src="https://user-images.githubusercontent.com/97298202/161390549-9208c683-5d7f-4e17-80a3-f6d8b7a83823.png">

How should I remove the sword from the room A while returning B? I'm not sure how to go about updating both rooms simultaneously? Currently whether the sword is on hand is indicated by a boolean variable within the Room, and I'm not sure how to update room A's while moving to room B. Thanks!
