### ISSUE TITLE
Restricted API

### ISSUE THREAD

**Issue by JeremyChuaWX** [nus-cs2030/2122-s2#193]
Hello, are we not allowed to use Collectors in lab 8?

![image](https://user-images.githubusercontent.com/79556863/161288953-7c1e2119-1906-40b7-8cfc-d3019121e116.png)

**Comment by szeying02** [comment]
Doesn't seem like it.

**Comment by JeremyChuaWX** [comment]
hmm so lab 7 was exception? Maybe cuz collectors can be mutable

**Comment by JeremyChuaWX** [comment]
> hello u can use the map function defined in the ImList and u do not have to submit your ImList or Pair files to code crunch

Yeah, i found out shortly after posting XD thanks for the tip!

**Comment by Ohnojiso** [comment]
Just to add up this also appiles for filter(I used Collectors to collect after I filtered, then I realised that there's actually a defined filter in the ImList)
