### ISSUE TITLE
Work around for Optional get(), isEmpty() methods level 2

### ISSUE THREAD

**Issue by fionlim** [nus-cs2030/2122-s2#195]
# Summary
Hi! For simulator2, I understand that we can iterate through the priority queue until there are no events left, but we also have to check for the next event executed by the highest priority event and add it to the priority queue. if i were to use orElse(), i would have to add a new event to the priority queue so wouldn't that mean the loop never ends? is there any way to work around this or is the only solution to use orElse()?

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary

**Comment by daitenshionyan** [comment]
You can mapping the `Optional<Event>` directly into `Optional<PQ>` and add the Event into the queue in the process. After that, extract the updated PQ out to update the existing using orElse(). If the Optional is empty it should return the original PQ.

**Comment by fionlim** [comment]
@daitenshionyan  ooh thank you!! your idea worked!
