### ISSUE TITLE
Hidden test case :(

### ISSUE THREAD

**Issue by Yang990121** [nus-cs2030/2122-s2#199]
# Summary
Does anyone know how to solve this hidden test case?

## Screenshots

<img width="389" alt="Screenshot 2022-04-02 at 12 00 23 PM" src="https://user-images.githubusercontent.com/65878741/161365461-efcd8db8-8673-4210-a7ad-a70fe797d11b.png">

**Comment by xywang08** [comment]
Maybe you can check if the room you are returning to has the same items?

**Comment by Yang990121** [comment]
OKie thank you so much
