### ISSUE TITLE
Lab 8 Test Case: Multiple swords

### ISSUE THREAD

**Issue by Luna2SY** [nus-cs2030/2122-s2#209]
# Summary

I can pass all the test cases in the task, but I am not sure how should I handle the situation when there are multiple swords in the room.  I would appreciate any suggestions.

## Screenshots

![image](https://user-images.githubusercontent.com/88837643/161395382-21494373-24e4-4070-a5ba-518f5ca4ef9b.png)

**Comment by Bearypop** [comment]
Maybe you can check if one of your methods is accidentally adding in additional swords? The lab states at the start: "For simplicity, you may assume that at no time will there be two of the same thing in a room.".

**Comment by Swagston20** [comment]
your methods should not be adding swords as there can only be one sword in every room scenario. So you nid to check whether your room already have sword anot and add accordingly

**Comment by xywang08** [comment]
Maybe when you moved to the next room, you didnt delete the sword in the current room (if picked up). Then when you move back there would be a duplicate.

**Comment by Swagston20** [comment]
Just imagine and picture yourself taking a sword going to rooms and going back rooms. It help for me

**Comment by baymaxtdx97** [comment]
When you pick up sword in room A and go to room B, this sword should disappear from Room A, you will need to make this adjustments accordingly. You should ensure that in any room, there should only be at most 1 sword.

**Comment by Luna2SY** [comment]
Thank you all for your help! I understood and solved this.
