### ISSUE TITLE
Submitting incrementally

### ISSUE THREAD

**Issue by Swagston20** [nus-cs2030/2122-s2#21]
In the announcement, it stated to submit our work incrementally. Does it mean we submit the work after every level?

**Comment by yongchein-o** [comment]
Really depends on personal preference. Usually its good to commit every so often and especially before you make any significant changes to your code.  Any case, submitting allows you to keep a history of your work. 

There's always a possibility that you: 
- accidentally delete your file: in which case there is no recycling bin in Ubuntu 
- accidentally delete your code in vim and reflexively exit using :wq

On that note it's good to set up the backup folder as well. (refer to the .vimrc file)

**Comment by tanweiming00** [comment]
I submit incrementally whenever I am confident that I passed that particular level.

**Comment by eesung00** [comment]
For me I submit the code only after I code for all level as I didn't look at the announcement clearly. I have some time wasting experience after I did this as I didn't pass all test cases as I expected, and accidentally change my code to fail more test cases. Hence, I guess by submiting your work incrementally will allow you to make sure your code so far is correct and avoid changing it for the next few level.

**Comment by heeeyi** [comment]
Personally I prefer submitting the code only after I feel I passed ALL the level requirements...In that sense, when we find that the final score is not A we know there is some style issues in the code, and thus I can focus on correcting for the styles. Anyway if you pass each level but later edit the code, you are prone to make mistakes in styles

**Comment by yangyee-hub** [comment]
I feel you should test your code incrementally in the vim first before submitting as it takes shorter time to test in jshell compared to the codecrunch. Codecurnch is normally used for testing hidden test cases.
