### ISSUE TITLE
Lab 6 Level 5 Main Class Help

### ISSUE THREAD

**Issue by jonyeokj** [nus-cs2030/2122-s2#210]
# Summary

Hello, I don't understand how to start with the Main class. Am I supposed to create a method, how will a function run, or rather how do I make it so that jshell takes in inputs for a roster to return an output?

**Comment by jonyeokj** [comment]
I've figured out that I'm supposed to use a scanner, but how do I make it so that all the lines are printed after the main java file has been terminated, and not when I'm placing in my inputs?

**Comment by Bearypop** [comment]
When reading in the records, read them one after another using a loop. For the query part, I don't think you need to separate the input and output.

**Comment by Swagston20** [comment]
At the end use a for loop to System.out.println() to output your results

**Comment by morksen123** [comment]
Hope this helps: 

`while (scanner.hasNext()) {
            String queryStudentName = scanner.next(); 
            String queryModule = scanner.next(); 
            String queryTitle = scanner.next();

            System.out.println(roster.getGrade(queryStudentName, queryModule, queryTitle));
        } 
`

**Comment by yizziepeasy** [comment]
You can choose to use `while (scanner.hasNext())` and store each query (or Grade) in a ImList. Once scanner detects that there are no inputs (^D / Ctrl + D), you can then use a for loop to output the grades stored in the ImList.

**Comment by jeanyeeee** [comment]
> # Summary
> Hello, I don't understand how to start with the Main class. Am I supposed to create a method, how will a function run, or rather how do I make it so that jshell takes in inputs for a roster to return an output?

1. No method is created simply add it into the `public static void main(String[] args) {...}`
2. @morksen123 and @yizziepeasy has illustrated the looping to output the results

To run and test, you can simply do:
```
String[] test = new String[5] //this is just a dummy variable
Main.main(test) //since main takes in a String[] as argument
```
Hope this helps!

**Comment by tristky** [comment]
Hi, after doing the project i realised the importance of the main class and hence i decided to track back and find more insights about it, and this thread made me realise how it was supposed to be implemented for the project. thanks jonathan!
