### ISSUE TITLE
Level 5 of Lab 8 go() method taking in a Functional Interface

### ISSUE THREAD

**Issue by hengyjj** [nus-cs2030/2122-s2#214]
# Summary

## Description:

Hello. I am attempting Level 5 and for the go() method, I take in a Function<ImList<Item>, Room> but when the lambda expression include a `new Room("foyer").add(new Sword()).tick(takeSword).go(x -> new Room("dining").add(new Candle()))`, my code would fail.

This is my code.
![image](https://user-images.githubusercontent.com/77519191/161419052-d91f6556-0307-48c5-82d7-b1fc5a8a73fd.png)

As you can see, it only returns the candle added, but not the original items it takes from the original room.
![image](https://user-images.githubusercontent.com/77519191/161419095-38c2564a-5ce1-4b25-b73c-0fdd2319f9a6.png)

Not too sure where is the error. Would appreciate any help! Thank you!

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by kiacheng** [comment]
hii i think u need something in your code to check for taken items and add it to the next room you are going to. for example, u can use a loop to check for a taken sword and then return a new room with the taken sword added to the next room.

**Comment by yongchein-o** [comment]
Yeah the lamda in this case returns
` new Room("dining").add(new Candle())`
So when you run func.apply(), you get a room with just a candle. And then you go on to return this room.
So it does not contain a sword

**Comment by xywang08** [comment]
you can create an overloaded constructor which takes in a list of items and the sword if carried over

**Comment by haoyangw** [comment]
> Yeah the lamda in this case returns ` new Room("dining").add(new Candle())` So when you run func.apply(), you get a room with just a candle. And then you go on to return this room. So it does not contain a sword

Like yongchein-o said, your lambda takes a Room and creates a new Room without passing the old Room `x` to the new Room in any way, so no state(`Item`s) is preserved in the new Room returned from the lambda

**Comment by hengyjj** [comment]
Thank you guys for your reply. But may I ask how do you guys pass in the list of items from the original room to the new room? I am unsure of how the lambda expression would be. Thank you.

**Comment by Kathleencsy** [comment]
I have the same question too.. since the lamda expression is given like that, it means that a new room without the old items will be created no matter what we pass in as x, how do i add the item that have been picked up into the new room and ensure that it is added in front at the same time?

**Comment by mazchew** [comment]
hi, in order to pass in the list of items from original to new room, i had a helper function insertSword() that would create a new ImList, add new Sword(), then addAll() current room's items. 

so my order of the go() method was:
1) func.apply(this.items)
2) if this.holdingSword(), insertSword(), newRoom.holdSword()
3) return newRoom

hope this helps!

**Comment by Kathleencsy** [comment]
@mazchew it worked, thank you!!

**Comment by morksen123** [comment]
I found the addAll() method useful. Generate the new list and list.addAll(newList) to get the combined list. 
But this might cause double adding if the new list is not overwritten. I solved this with a little bit of cheating in the constructor.

**Comment by hengyjj** [comment]
> @mazchew it worked, thank you!!

Sorry I am still unsure on how it works. Does it mean within the Room class, I would have to create an insertSword() function that would do the following that Mazchew mentioned, followed by an if condition? What is the use of the if condition?  And what does `newRoom.holdSword()` mean? Thank you.

**Comment by hengyjj** [comment]
Thank you all for your help!
