### ISSUE TITLE
Lab 8 level 4 

### ISSUE THREAD

**Issue by terrrence** [nus-cs2030/2122-s2#216]
# Summary
hi! is anybody else facing this issue? I can't seem to pass this particular test case and i'm not sure why. I passed the other public test cases.

## Screenshots

<img width="405" alt="Screenshot 2022-04-03 at 6 41 33 PM" src="https://user-images.githubusercontent.com/100092065/161423980-aeab31fc-be33-446a-8daf-0611d90ff05c.png">

**Comment by danyelys** [comment]
is there a possiblity your toString method places the items in the wrong order

**Comment by yizziepeasy** [comment]
Seems like the sequence of your items are in the wrong order. Does your takeSword cause your Sword to be shifted to the end of the list (adding a new Sword)? If so, you need to modify the sword's isTaken status instead of removing the sword and inserting a new sword.
