### ISSUE TITLE
Lab 8 Level 4 hidden test cases

### ISSUE THREAD

**Issue by ldkai** [nus-cs2030/2122-s2#219]
# Summary

Hi, did anyone run into this error on codecrunch? I passed all the public test cases..  tried to initialise a room with just a sword and troll and got the required output (although im not sure what the test cases are). Any help is appreciated thanks!!

## Screenshots
<img width="418" alt="Screenshot 2022-04-03 at 11 49 00 PM" src="https://user-images.githubusercontent.com/97543987/161436650-6f275510-f893-4943-8101-f554e7414eaf.png">

**Comment by yizziepeasy** [comment]
Hi, seems like something is wrong with your Troll class that is tick related. Can you show your code?

**Comment by ldkai** [comment]
> Hi, seems like something is wrong with your Troll class that is tick related. Can you show your code?

Hi yizziepeasy, turns out i mixed up the indexing in tick in my troll class as you mentioned as I was using an ImList to store the states of the troll. It works fine now thanks!
