### ISSUE TITLE
[Level 1] Jshell class/method is not public in cs2030.simulator.*

### ISSUE THREAD

**Issue by haoyangw** [nus-cs2030/2122-s2#220]
# Summary
Put a summary of the question
Cannot test simulator classes and their methods in jshell

## Description 
Describe the problem and code snippets if necessary 
When using jshell to test Level 1 classes, e.g. EventStub, jshell complains that the cs2030.simulator.* classes are not public and cannot be accessed from outside package(jshell is launched from parent directory of `cs2030` folder). I have setup the working directory according to [#92](https://github.com/nus-cs2030/2122-s2/issues/92). Based on the task description in CodeCrunch the cs2030.simulator classes cannot be public, other than SimulateN, so in that case is there any way to fix the jshell errors without setting the simulator classes to public? Setting them to public has been the only way to overcome this issue for me so far.

## Screenshots (if any): 
Insert Images here if necessary

**Comment by teresasee** [comment]
Hi can I check, did you try to import a class from the simulator package? For me I didnt get that error and when I searched online, classes within the same package should be able to access each other as well. If they are in the same package, you dont need to import the class. Could that be the issue?

**Comment by haoyangw** [comment]
Oh I didn't import any simulator classes, I just can't run the test cases listed on CodeCrunch in jshell since everytime I try to instantiate any classes from `simulator` I get this error above

**Comment by teresasee** [comment]
Hmm, other than Pair, ImList and PQ, do all of your other classes have `package cs2030.simulator`? I didnt set my working directory according to # 92 and it seems to be okay. If all of your other classes have the `package cs2030.simulator` and u compile using `javac -d . filename.java`, then im not too sure what the issue is :/ sorry about that.

**Comment by haoyangw** [comment]
> Hmm, other than Pair, ImList and PQ, do all of your other classes have `package cs2030.simulator`? 

Oh yeah they do.

> I didnt set my working directory according to # 92 and it seems to be okay. If all of your other classes have the `package cs2030.simulator` and u compile using `javac -d . filename.java`, then im not too sure what the issue is :/ sorry about that.

Oh wait so you put all of your .java files in the same directory is it? But inside each .java file you set the correct `package cs2030.*`? Then you just compile using `javac -d . filename.java` and jshell, you didn't need to do `import cs2030.*` in jshell to instantiate classes like `Event event = new EventStub()`?

**Comment by neverdivideby0** [comment]
Hi did you managed to do it? I did similarly. i had to import cs2030.simulator and util to instantiate classes.

**Comment by haoyangw** [comment]
> Hi did you managed to do it? I did similarly. i had to import cs2030.simulator and util to instantiate classes.

Yeah I figured it out! For future reference to everyone else:

-Don't put .java files in cs2030/util and cs2030/simulator folders. Just put them all in the same folder like previous labs
-To test, there are two ways:
--> Public classes(SimulateN.java): Compile your classes using 'java -d . *.java' from the directory containing all your .java files. U should get a 'cs2030' folder now generated with the .class files sorted into cs2030/util or cs2030/simulator automatically. Without entering the cs2030 folder, do 'jshell' and then 'import cs2030.util.*' and 'import cs2030.simulator.*' before testing your classes
--> Nonpublic classes(the other cs2030.simulator.* classes): Delete all the .class files(e.g. `rm -R cs2030`), then do `jshell Pair.java ImList.java PQ.java Customer.java Server.java [...]` where [...] is the rest of your .java files arranged in the correct order. You'll get a bunch of 'invalid statement package cs2030.*' errors, but they don't affect your testing so ignore them. You can then test any of the .java files just like you do in the labs without worrying about making them public(it doesn't matter, any non-private class or method is now accessible in jshell)
