### ISSUE TITLE
Level 3 modifying isTaken

### ISSUE THREAD

**Issue by gypsyxx** [nus-cs2030/2122-s2#221]
I have a isTaken boolean property inside the sword class however I'm unsure on how I can modify the boolean from false to true after the sword has been taken. 
I also created a overloaded constructor to take in the modified boolean but if I were to call upon this constructor, it will give me a new sword which I do not want.

**Comment by SoSimplySean** [comment]
Given that the boolean is going to be private final, and in order to maintain immutability, you'll probably need to use the overloaded constructor to return a new sword, and modify your code around this return of a new, modified sword.

**Comment by jiaweiho72** [comment]
Hi I'm not sure how your implementation works but a new Sword should be returned if you want to modify the private final property. If you want to return a boolean after modifying, you can just return the isTaken property

**Comment by szeying02** [comment]
Just to add on, you'll definite need it to have the private final property, else CodeCrunch will reject your code. Hence, the only way around is to create a new sword. There isn't much difference between one sword from another if i remember correctly. If you're checking if the sword object is the same as another sword object at some point in your code, you can consider overriding the equals() method.
