### ISSUE TITLE
Level 3: cannot get "You already have sword"

### ISSUE THREAD

**Issue by tungkei** [nus-cs2030/2122-s2#224]
## Description:
Hi, I am unable to print "You already have sword" when I try to do takeSword twice. In my Sword class I have a property to check if the sword has been taken, and the isActionTaken() returns a boolean to see if the sword has been taken or not. 

For the takeSword method, I check if the sword has been taken, if false then I pick it up, create a new sword that has taken = true, change the list of items in the room such that the sword is taken and return a new room with this list.  I checked that the sword in the new room is indeed 'taken', but when I do another takeSword I'm not sure why the taken status becomes false and hence returns "You have taken sword" again.

## Code Snippets
![image](https://user-images.githubusercontent.com/99954534/161470256-1e7f6128-1645-4b1b-bf13-173f0a444fee.png)

**Comment by szeying02** [comment]
Your code looks correct to me, did you by any chance type 

```
> room.tick(takeSword)
> room.tick(takeSword)
```
instead of 
```
room.tick(takeSword).tick(takeSword)
```

**Comment by tungkei** [comment]
> Your code looks correct to me, did you by any chance type
> 
> ```
> > room.tick(takeSword)
> > room.tick(takeSword)
> ```
> 
> instead of
> 
> ```
> room.tick(takeSword).tick(takeSword)
> ```

![image](https://user-images.githubusercontent.com/99954534/161472653-2eb551ef-563a-46c1-a3c4-66e24b283c75.png)

**Comment by szeying02** [comment]
If your 
`System.out.println(roomItems.get(i).isActionTaken());` returns true, then for some reason, it would seem that when creating the new Room in the following line uses the original `roomItems` instead of the modified one. If that's the case, it might have something to do with the Java Memory Model? I'm not sure how to go about about amending that though :( I guess you could try changing the variable name of your roomItems? Something like this: 

```
ImList<Items> newItems = ImList.<List>of(roomItems);
newItems = newItems.set(i, newSword);
return new Room(room.getRoomName(), newItems);
```

**Comment by tungkei** [comment]
> If your `System.out.println(roomItems.get(i).isActionTaken());` returns true, then for some reason, it would seem that when creating the new Room in the following line uses the original `roomItems` instead of the modified one. If that's the case, it might have something to do with the Java Memory Model? I'm not sure how to go about about amending that though :( I guess you could try changing the variable name of your roomItems? Something like this:
> 
> ```
> ImList<Items> newItems = ImList.<List>of(roomItems);
> newItems = newItems.set(i, newSword);
> return new Room(room.getRoomName(), newItems);
> ```

I tried doing that and it made no difference :")

**Comment by jlee1007** [comment]
can trace your code back to the sword class to ensure the boolean is set to true! for me i had a similar method and problem & i realised that my error was in the sword class/constructor

**Comment by shanernigans** [comment]
hello i had the same issue and realised that i forgot to update my sword's tick( ) methods accordingly that would return a new sword with the boolean change to true

**Comment by tungkei** [comment]
> hello i had the same issue and realised that i forgot to update my sword's tick( ) method accordingly that would return a new sword with the boolean change to true

yea that was the issue, it works now thank you!
