### ISSUE TITLE
Project Level 5

### ISSUE THREAD

**Issue by mazchew** [nus-cs2030/2122-s2#227]
# Summary
Questions regarding evaluation of service times

## Description 
Since the service times of each customer should only be gotten when a serve event is called, how should each Customer be instantiated? In particular, in Main5, for those customers without a serve time, what does the Supplier<Double> in the Pair object refer to? (Since I think there's no double to be wrapped around a Supplier? I may be misunderstanding that part.)

How should I approach this level? Thanks!

**Comment by LauWyeRock** [comment]
you can consider using the lazy class for each customer's service time. the supplier refers to the scanner object created in the main class that takes in the service times, and you will only .get() when the customer is gg to get served or waits.

**Comment by szeying02** [comment]
The Supplier pair contains the serviceTime as a double, wrapped in a supplier. It's meant to be passed into a Lazy and this would then be passed into the Customer to be instantiated. 

So for those without a serveTime, the Lazy would never be called, and it won't have a service time. 

You'll only need to get the service time when serving the customer.

**Comment by mazchew** [comment]
i see, thanks! can i ask how you stored the service times then? i originally thought of storing it in the customer but i don't think that's right? perhaps an ImList?

thanks for the clarification!

**Comment by hengyjj** [comment]
Hi guys. I would wish to clarify like what's the purpose of the Lazy class? Based on my understanding, the Simulate5 will take in number of servers and a `List<Pair<Double, Supplier<Double>>>  arrivalServiceTimes`. However, I am not too sure where the Lazy comes in. 

What I thought was that i would still retrieve the customer arrival time within a for loop by writing: `this.arrivalServiceTime.get(i).first()` and the service time by `this.arrivalServiceTime.get(i).second()`. However, looking at some of the comments, you guys said not all customers have serviceTime?

This is what I have written so far.
<img width="688" alt="image" src="https://user-images.githubusercontent.com/77519191/161713973-7881f3a7-364c-479b-8859-81bc44eb2f7c.png">




Appreiciate any explanation. Thank you guys!

**Comment by LauWyeRock** [comment]
@hengyjj hi when creating my customer i used the Lazy constructor with just one argument (supplier). From level5 onwards i don't think they will use the default service time anymore. It's not about whether they have a different service time or not, but whether they leave upon arrival or not. If they leave, they won't even get a service time

**Comment by hengyjj** [comment]
> @hengyjj hi when creating my customer i used the Lazy constructor with just one argument (supplier). From level5 onwards i don't think they will use the default service time anymore. It's not about whether they have a different service time or not, but whether they leave upon arrival or not. If they leave, they won't even get a service time

I see.. thank you for your clarification!

**Comment by rachtan27** [comment]
Hi sorry im a bit confused, if the default service time is not put into the lazy class, how would the previous levels be executed/pass since level4 and below do not have specific service times? isit by creating different constructors or something....?

**Comment by loqir** [comment]
hi does anyone know how to take in the input of the servicetime? do we have to call .get() from the Lazy in Main5.java and if so, how does that work?
