### ISSUE TITLE
Fail Test Case: test4_1

### ISSUE THREAD

**Issue by TohDeKai** [nus-cs2030/2122-s2#228]
<img width="593" alt="Screenshot 2022-04-04 at 3 19 30 PM" src="https://user-images.githubusercontent.com/66544431/161492965-dc9bf872-07ce-4ae1-b0a9-3a4e2e6b706f.png">

Anyone has any idea what this hidden test case could be and what's causing it?

More Info:
In my Room.java, there is an int tick counter which keeps track of the ticks
Every time tick() is called, I create a new room with a tick that is increased by 1

**Comment by wk1267** [comment]
Hi De Kai, this may happen because you did not tick the troll / update troll's status. You may want to check if you update tick for all items in the room.

**Comment by TohDeKai** [comment]
> Hi De Kai, this may happen because you did not tick the troll / update troll's status. You may want to check if you update tick for all items in the room.

Hey, thanks for responding but I doubt that's the case since my tick counter is updated with every tick() method called. Not sure what else could be the issue

**Comment by shanernigans** [comment]
i think in this case a tick( ) is added after adding a new candle but before adding a new troll , so your tick counter would assume that all objects in the room are added before a tick, so your troll gets ticked an extra time.

**Comment by TohDeKai** [comment]
> i think in this case a tick( ) is called after adding a new sword but before adding a new troll , and your tick counter assumes that all objects in the room would undergo the same number of ticks, so your troll gets ticked an extra time.

Hey! Thanks a lot for this. Managed to fix by implementing the tick() method differently and inside each Thing instead. thanks!

**Comment by TohDeKai** [comment]
> i think in this case a tick( ) is called after adding a new sword but before adding a new troll , and your tick counter assumes that all objects in the room would undergo the same number of ticks, so your troll gets ticked an extra time.

Hey! Thanks a lot for this. Managed to fix by implementing the tick() method differently and inside each Thing instead. thanks!
