### ISSUE TITLE
Project: difference in server selection for before and after level 6

### ISSUE THREAD

**Issue by JeremyChuaWX** [nus-cs2030/2122-s2#240]
In the previous levels, the server was chosen based on the queue length, however, in level 6 it is now based on the total service time.

I have made a method `getTotalServiceTime()` for servers to call in order to get the best server in level 6, however, it seems that this conflicts with test case 5_3

How did you guys handle this? Is it to implement some kind of mode switch for the function?

Appreciate the help!

**Comment by Ohnojiso** [comment]
The customer will queue at the first queue available, it does not have to be the shortest one. 
For example, if all the servers are busy, qmax = 10, customers who arrives later will continue to queue at server 1 until these's 10 people waiting at server 1, then they queue at server2 until the queue length at server2 becomes 10...

**Comment by JeremyChuaWX** [comment]
> The customer will queue at the first queue available, it does not have to be the shortest one.
> For example, if all the servers are busy, qmax = 10, customers who arrives later will continue to queue at server 1 until these's 10 people waiting at server 1, then they queue at server2 until the queue length at server2 becomes 10...

hmm, i have tried this method, but it is not the same as the test case. After some testing, it seems that the test case is correct when you sort by people in queue. Then in the next test case, this method of sorting will fail again, so it is like there are 2 methods of sorting in level 6?

**Comment by Ohnojiso** [comment]
> > The customer will queue at the first queue available, it does not have to be the shortest one.
> > For example, if all the servers are busy, qmax = 10, customers who arrives later will continue to queue at server 1 until these's 10 people waiting at server 1, then they queue at server2 until the queue length at server2 becomes 10...
> 
> hmm, i have tried this method, but it is not the same as the test case. After some testing, it seems that the test case is correct when you sort by people in queue. Then in the next test case, this method of sorting will fail again, so it is like there are 2 methods of sorting in level 6?

It's not a method, it is the requirement of the task.(& it is not **sorting**, I think it is more like **filtering** out the servers with full queues when you decide whether the customer should wait at this server). Under level6 it says "Each server now has a queue of customers to allow multiple customers to queue up. A customer that chooses the **first queue available** and joins at the tail." The results should be correct if your code follows this requirement. Maybe you would like to share how it fails?

**Comment by JeremyChuaWX** [comment]
![image](https://user-images.githubusercontent.com/79556863/162123332-6353b8a7-f4d9-420c-bd16-91b3972502c8.png)

In my `Shop` class, I have a list of servers, then when a customer arrives, i assign a server to the customer.
For this test case, I tried to do what you suggested, and not care about queue length, so i assigned the customer to the first available server, however, it seems that thats not what the test case wants

**Comment by Ohnojiso** [comment]
> ![image](https://user-images.githubusercontent.com/79556863/162123332-6353b8a7-f4d9-420c-bd16-91b3972502c8.png)
> 
> In my `Shop` class, I have a list of servers, then when a customer arrives, i assign a server to the customer. For this test case, I tried to do what you suggested, and not care about queue length, so i assigned the customer to the first available server, however, it seems that thats not what the test case wants

From your output I guess(do correct me if I interpreted it wrongly) your logic might be something like check if server 1 can serve -else- check if can wait at server 1 -else- check if server 2 can serve -...
However it should have been check if server 1 can serve -else- check if server 2 can serve - else - ... if no server can serve after looping through all the servers, then you move on to check if can wait at server 1 - else- check if can wait at server 2-...

**Comment by JeremyChuaWX** [comment]
I have a `getAvailableServer()` method that sorts the `ImList` of servers in the `Shop` class, then returns the server at index 0, which is the 'best' server

Then my shop class has a ServerComparator than can be switched out based on how the question wants it

> However it should have been check if server 1 can serve -else- check if server 2 can serve - else - ... if no server can serve after looping through all the servers, then you move on to check if can wait at server 1 - else- check if can wait at server 2-...

but whats the difference between sorting by queue length and what you suggested here?

**Comment by Ohnojiso** [comment]
> I have a `getAvailableServer()` method that sorts the `ImList` of servers in the `Shop` class, then returns the server at index 0, which is the 'best' server
> 
> Then my shop class has a ServerComparator than can be switched out based on how the question wants it
> 
> > However it should have been check if server 1 can serve -else- check if server 2 can serve - else - ... if no server can serve after looping through all the servers, then you move on to check if can wait at server 1 - else- check if can wait at server 2-...
> 
> but whats the difference between sorting by queue length and what you suggested here?

<Condition: all servers are not available for serving>
Sorting by queue length means the "best" being the one with the shortest queue length, while the "best" should be the server with the smallest index & is available for queuing.

**Comment by JeremyChuaWX** [comment]
Hello, thanks for your help! I have solved the level, I think I didn't get it cuz i was stuck in the Comparator mindset, thanks for the tip on the looping, I managed to solve it by looping through twice.

Thanks!

**Comment by Ohnojiso** [comment]
> Hello, thanks for your help! I have solved the level, I think I didn't get it cuz i was stuck in the Comparator mindset, thanks for the tip on the looping, I managed to solve it by looping through twice.
> 
> Thanks!

Congrats!!
