### ISSUE TITLE
Level 1 of PA3

### ISSUE THREAD

**Issue by hengyjj** [nus-cs2030/2122-s2#242]
# Summary
Put a summary of the problem here

## Description 
Hi. Is anyone aware of what is this issue about?

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/77519191/161699138-a38ee0b1-d889-4192-b839-2418932ca97a.png">

Thank you.

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary

**Comment by alantay11** [comment]
Move on to level 2 first so the attributes of count are moved to the aggregate class instead

**Comment by hengyjj** [comment]
> Move on to level 2 first so the attributes of count are moved to the aggregate class instead

thanks alan!
