### ISSUE TITLE
Lab8 test6_1

### ISSUE THREAD

**Issue by hhujiale** [nus-cs2030/2122-s2#243]
Hii anyone facing the same issue..
all other test cases passed alr except this one line, i am so confused ahh
please help:(
![photo6222189898937512293](https://user-images.githubusercontent.com/95912577/161700431-0f4013d9-4324-439a-8f61-caca5efefa4c.jpg)

**Comment by bryankwe** [comment]
I also failed test6_1 and its cuz I still did a `tick()` for the first room when i called `back()` (whose previous room is `Optional.<Room>empty()`)

If that is not your issue, maybe you can reference this other thread: 
https://github.com/nus-cs2030/2122-s2/issues/204#issue-1190591468

ATB!

**Comment by hhujiale** [comment]
> I also failed test6_1 and its cuz I still did a `tick()` for the first room when i called `back()` (whose previous room is `Optional.<Room>empty()`)
> 
> If that is not your issue, maybe you can reference this other thread: [#204 (comment)](https://github.com/nus-cs2030/2122-s2/issues/204#issue-1190591468)
> 
> ATB!

ahhh do you mean if the previous room is empty we shall not tick()?

**Comment by jamietan123** [comment]
If the previous room is the same as the current room, don't tick()

**Comment by bryankwe** [comment]
> > I also failed test6_1 and its cuz I still did a `tick()` for the first room when i called `back()` (whose previous room is `Optional.<Room>empty()`)
> > If that is not your issue, maybe you can reference this other thread: [#204 (comment)](https://github.com/nus-cs2030/2122-s2/issues/204#issue-1190591468)
> > ATB!
> 
> ahhh do you mean if the previous room is empty we shall not tick()?

Yes, for my case.

**Comment by hhujiale** [comment]
Haloo to anyone facing this issue:

For me it happens cuz I didnt store the old reference to the room, which cause `this.previousRoom != this` when `this` does not have a previous room (means it should be the same as the current room). I added a for loop inside `back()` to check if their name is the same, if it is, straightly returns this room; if it is not, do the other required thing and return its previous room.

One more thing to note is that don't really need to use `Optional<Room> previousRoom` (my tutor commented out and it reallyyyy makes sense), making it optional wastes me a lot of time:(

ATB guys~
