### ISSUE TITLE
PA3 Level 1

### ISSUE THREAD

**Issue by Guanjung27** [nus-cs2030/2122-s2#244]
Hi, can anyone explain what this level is asking for, dont really understand the static part .
Thanks

**Comment by alantay11** [comment]
you can refer to imlist and see how it uses static method of to create new imlist. It's just another way of creating an object without using the new Object way of constructing it

**Comment by Swagston20** [comment]
Use ImList as reference

**Comment by Brianliew77** [comment]
Hi, static is basically a global variable. In this case if u read part 1 of PA3, u should see that u should be using private final for ur attributes instead of static (it resets)

**Comment by Zhenyubbx** [comment]
U can take ImList as a reference on how the of method was implemented. The method construction is pretty similar so I think it's easier to understand if u look at that!
