### ISSUE TITLE
Lab 8 Level 5 help

### ISSUE THREAD

**Issue by teekayowh** [nus-cs2030/2122-s2#248]
![image](https://user-images.githubusercontent.com/70503149/161728816-baf3f0ea-50e7-4055-90cb-c5aa88b4a939.png)
 Hello, i got this error from executing the test cases in level 5, does anyone know what is causing this?

**Comment by adityajirafe** [comment]
hey you can try closing jshell and reopening it, not sure why but it worked for me

**Comment by lindyapeintern** [comment]
I put my both my tick() and my overloaded tick method together one after another and then it worked fine after that.

**Comment by teekayowh** [comment]
Ah ok, I closed everything, opened again and it works! Thanks so much!
