### ISSUE TITLE
Incorrect restTime output for Project level 7

### ISSUE THREAD

**Issue by Ohnojiso** [nus-cs2030/2122-s2#254]
I got incorrect `restTime` output for project level 7. 

## Description 
Can see from the screenshot below: The first column is the `arrivalTime`, second column is the `doneTime` for the current service and the third one is the `nextAvailableTime`(= `doneTime` + `restTime`). If it is not messed up then `doneTime != nextAvailableTime` should occur after serving customer 2 and 9, but now it happens after 6 and 8 instead. Does anyone know how to avoid this? thankssss

## Screenshots: 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/70836710/161813975-14433c39-6eb5-4239-a498-3ed2c686cf15.png">

**Comment by sinteary** [comment]
@Ohnojiso I am facing a similar issue here (getting the same values as you), but I only call `get()` once for the rest time supplier in the DoneEvent. Could you please elaborate more on what you mean by calling `get()` twice?

**Comment by Ohnojiso** [comment]
> @Ohnojiso I am facing a similar issue here (getting the same values as you), but I only call `get()` once for the rest time supplier in the DoneEvent. Could you please elaborate more on what you mean by calling `get()` twice?

`get()` is called in `Serve` for the `serveTime`, and after that it is called again for `restTime`.

**Comment by wzs02** [comment]
Hi, can I ask how you all managed to generate the correct wait times for the servers? I'm calling the supplier in Main7 after every DONE event now and getting incorrect values. Thanks in advance!

**Comment by bryanwonggy** [comment]
I just solved it, basically my issue was with my Simulate. Because in my simulate, I kept calling _.execute(), so what I did was I assigned it to a variable such that I will only call it once.

**Comment by Ohnojiso** [comment]
> I just solved it, basically my issue was with my Simulate. Because in my simulate, I kept calling _.execute(), so what I did was I assigned it to a variable such that I will only call it once.

Congrats! I think we might have different sources of issue because in my Simulate I only execute once... I think my problem is caused by calling `.get()` twice and the scanner just scan the second next value for my restTime instead of the just the next value... Would you mind sharing how you implemented the get methods to get the correct `serveTime` & `restTime`? Thanks a lot!

**Comment by inas0ng** [comment]
Hi! I had the exact same issue, where the rest was at customers 6 and 8 instead. I just fixed it by not putting this Supplier<Double> for rest time within a Lazy case. I think the Lazy cache was making the Random outputs all the same (instead of being 'random' lol) so this solves it! Hope this helps!

**Comment by E0857389** [comment]
> I just solved it, basically my issue was with my Simulate. Because in my simulate, I kept calling _.execute(), so what I did was I assigned it to a variable such that I will only call it once.

hello could u elaborate on this!!

**Comment by Ohnojiso** [comment]
> Hi! I had the exact same issue, where the rest was at customers 6 and 8 instead. I just fixed it by not putting this Supplier for rest time within a Lazy case. I think the Lazy cache was making the Random outputs all the same (instead of being 'random' lol) so this solves it! Hope this helps!

Hello I tried on this. I got the correct restTime for Server 2 but not server 9. Here is a table of what I got (serverID: nextTime(`eventTime`+`serveTime`) `restTime` nextServe(nextTime+`restTime`))
<img width="276" alt="image" src="https://user-images.githubusercontent.com/70836710/163365762-df3215ce-0c44-4bd5-8be8-292c2cbe5ac7.png">
I assigned the supplier(not wrapped in Lazy) as an attribute of the Server class, is this similar to your implementation?

**Comment by yizziepeasy** [comment]
> > Hi! I had the exact same issue, where the rest was at customers 6 and 8 instead. I just fixed it by not putting this Supplier for rest time within a Lazy case. I think the Lazy cache was making the Random outputs all the same (instead of being 'random' lol) so this solves it! Hope this helps!
> 
> I solved it! Thank you so much!

Hello! Which class did you call `Supplier.get()`? Also, Does your `Rest event` call `Serve event`?

**Comment by yizziepeasy** [comment]
> > > Hi! I had the exact same issue, where the rest was at customers 6 and 8 instead. I just fixed it by not putting this Supplier for rest time within a Lazy case. I think the Lazy cache was making the Random outputs all the same (instead of being 'random' lol) so this solves it! Hope this helps!
> > 
> > 
> > I solved it! Thank you so much!
> 
> Hello! Which class did you call `Supplier.get()`? Also, Does your `Rest event` call `Serve event`? My customer 2 does not have a rest time. :( Not sure why even though I did not wrap my supplier around a Lazy

**Comment by Ohnojiso** [comment]
I called `Supplier.get()` in my `Done` class. I do not have a Rest event in my implementation.
