### ISSUE TITLE
TestCase 4_1

### ISSUE THREAD

**Issue by summerthia02** [nus-cs2030/2122-s2#256]
hii does anyone know what's the issue here? 
<img width="437" alt="Screenshot 2022-04-06 at 2 45 29 AM" src="https://user-images.githubusercontent.com/97536121/161827675-be605a3d-94b7-4e7b-ba53-de0402d83a76.png">
![Screenshot 2022-04-06 at 2 46 28 AM](https://user-images.githubusercontent.com/97536121/161827710-c8b8903c-60a6-44b8-90e4-a87b756a8342.png)

The image below is my code ! so I tot its correct. any idea which method this falls under?

**Comment by Ohnojiso** [comment]
The code adds the sword to the room before adding troll, so "Sword is shimmering" should go first in the output.

**Comment by jlee1007** [comment]
sword gets added first you could check to see if that is reflected in your code!

**Comment by sshawnlim** [comment]
Your "Sword is shimmering." is coming in the line after "Troll is getting hungry." whereas in the correct output it should come as the line before!

**Comment by jamietan123** [comment]
Maybe you can check your toString method to see if the items are returned in the correct order

**Comment by NUST007** [comment]
<img width="424" alt="Screenshot 2022-04-07 at 8 57 34 AM" src="https://user-images.githubusercontent.com/98576690/162099057-bede0e15-b1e2-4823-8b02-0568e0c765c7.png">

I might be facing the same issue, I also can't pass private test 4_1. Above is the printed outputs for some test cases of my own for reference.

**Comment by theshaydays** [comment]
might be because your kilTroll/takeSword method is returning a new sword which rearranged itself when when callign the function. So might wanna check how u added a new sword in the take sword method and make sure it stays in the same position
