### ISSUE TITLE
Level 5 issue

### ISSUE THREAD

**Issue by lindyapeintern** [nus-cs2030/2122-s2#257]
# Summary

Hi guys! I saw a few of the threads and created my solution for level 5 but I have some problems with some outputs. Any help is appreciated!!

## Description:

My solution is to check through the list if any of the items are taken and if they are, we add them to the new list and use addAll to create a new room with the taken items. 

So for instance, when I enter a new room, I will have an initial listOfThings that is [Sword is shimmering.]. 
However, when I add a new candle, the list somehow pushes the sword backwards and my new list is [Candle flickers., Sword is shimmering.]
When I add a troll first then add a candle, then the list doesnt push the sword and the returned list is [Sword is shimmering., Troll lurks in the shadows., Candle flickers.]

## Screenshots

<img width="668" alt="image" src="https://user-images.githubusercontent.com/99935293/161853324-a497012c-c27e-4a65-b8f0-42856cce58e5.png">

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/99935293/161853769-0c1884b8-c59d-4292-b6db-9c2e82394e57.png">

**Comment by lindyapeintern** [comment]
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/99935293/161854545-74837334-6442-4d04-be04-768915f1b20e.png">

Just to add on in case I missed something

**Comment by lindyapeintern** [comment]
oh nvm I think I found the error

> <img alt="image" width="1117" src="https://user-images.githubusercontent.com/99935293/161854545-74837334-6442-4d04-be04-768915f1b20e.png">
> 
> Just to add on in case I missed something

**Comment by HaiJin123** [comment]
May I ask you how you solved your problem? I am facing the same issue right now.
