### ISSUE TITLE
Parallel streams tested in PA2 / Finals?

### ISSUE THREAD

**Issue by TohDeKai** [nus-cs2030/2122-s2#259]
Hi, just wanted to check if the handling of parallelism in streams will be tested in our PA2 or finals. Thanks!

**Comment by lukasleeyo** [comment]
Hi De Kai, If I recall correctly during the lecture, I think parallelism, in general, is not examinable in this module. I am not 100% sure, so others can add on or correct me. Thanks!

**Comment by jamietan123** [comment]
I think its not tested

**Comment by TohDeKai** [comment]
okie thanks lukas and jamie!
