### ISSUE TITLE
Failed test case 6_1

### ISSUE THREAD

**Issue by rexlionz** [nus-cs2030/2122-s2#261]
Hi, I'm having some difficulty figuring out why I'm failing this particular test case, could anyone help me with this? Thank you! 
edit: I know it has something to do with the back method but I passed all the frontend test cases

<img width="993" alt="Screenshot 2022-04-06 at 1 02 18 PM" src="https://user-images.githubusercontent.com/87936033/161899478-02cada44-e4a3-4eeb-84c4-c62dc6631787.png">

**Comment by zuohui48** [comment]
handsome

**Comment by evelyynnz** [comment]
Hello, i think u can fix it by returning the current room if a room doesn't have a previous room to go to when back() is called instead of returning empty!

**Comment by lukasleeyo** [comment]
To add to what @evelyynnz has said, one possible way to do it is to use ``return this.prevRoom.orElse(this);`` at the end of your back method, if you used the previous room method where prevRoom is an ``Optional<Room>``. At least this is what I did, not sure for you and the rest.

**Comment by alwinngjw** [comment]
Hi, i think you have to return the current room if a previous room does not exist.

That may fix your error

Hope this helps.

**Comment by rexlionz** [comment]
I managed to fix it! thanks everyone for the help :)
