### ISSUE TITLE
PA#3 Level 4 flatMap

### ISSUE THREAD

**Issue by kiacheng** [nus-cs2030/2122-s2#262]
# Summary
i couldn't pass the last test case of PA#3 level 4 about flatMap. A small part of my code looks like this 

Aggregate<S,T> flatMap(Function<T, Aggregate<S,T>> objFunc) {
Pair<S,T> seedobj = objFunc.apply(this.optionalObj.get()).func.get().apply(this.seed.get())
 }

the error i got on code crunch is Aggregate<java.lang.Integer,java.lang.Integer> cannot be converted to Aggregate<java.lang.Integer,java.lang.String>

**Comment by szeying02** [comment]
Hey, you may want to check out the last test case of level 4. You'll see that the there is a change of type for T from String to Integer to Circle. So you'll need add new generic type to the method e.g. U. 

`<U> Aggregate<S,U> flatMap(Function<T, Aggregate<S,U>> objFunc) {
Pair<S,U> seedobj = objFunc.apply(this.optionalObj.get()).func.get().apply(this.seed.get())
}`

**Comment by kiacheng** [comment]
@szeying02 thank you!! that helped
