### ISSUE TITLE
PA2 Optional.get()

### ISSUE THREAD

**Issue by Kent-twl** [nus-cs2030/2122-s2#270]
Hi, I would to clarify if we are allowed to use the Optional.get() method in the PA. Thanks in advance for the clarification!

**Comment by Darien2307** [comment]
I believe no.

**Comment by adityajirafe** [comment]
The use of isPresent(), isEmpty() and get() is banned

**Comment by jamietan123** [comment]
^ You can use orElse(), etc and ifPresent() etc. in place of these methods

**Comment by alwinngjw** [comment]
Hi, Yea I think it was mentioned in the lecture that the use of these 3 methods isPresent(), isEmpty() and get() will be prohibited by CodeCrunch auto grader

Hope this helps.

**Comment by vinessa23** [comment]
hello, during the rec ytd i asked prof whether it isEmpty() will be banned, but prof say just read the instructions for the PA tmr,,, so i think it might be allowed!

**Comment by Kent-twl** [comment]
Thank you all for the clarification!
