### ISSUE TITLE
Error when testing with Main file

### ISSUE THREAD

**Issue by xywang08** [nus-cs2030/2122-s2#271]
# Summary
Hi I was trying to test my Simulate2 file which worked fine in normal jshell but when I try to test it with the provided Main2 it throws the NumberFormatException. May I know which are the possible parts that caused this?

## Screenshots (if any): 
![Screenshot (32)](https://user-images.githubusercontent.com/81962290/162030404-2c0008ed-1fd8-4594-96d8-dcf3e0a2e7ee.png)

**Comment by jamietan123** [comment]
Did u accidentally add a space after your inputs?

**Comment by xywang08** [comment]
> Did u accidentally add a space after your inputs?

Nope I just entered after each input

**Comment by jamietan123** [comment]
The NumberFormatException occurs when an attempt is made to convert a string with improper format into a numeric value. I think you need to double check your code in Simulate2?

**Comment by yizziepeasy** [comment]
Hi, did you manage to resolve this?

**Comment by meganparrot889** [comment]
Hi I had this problem too because I was pressing shift 6 and the d key ie manually typing out "^D". Maybe you could try to press the control button followed by d key instead!

**Comment by xywang08** [comment]
thanks guys for your response i have managed to resolve it
