### ISSUE TITLE
test 6_1

### ISSUE THREAD

**Issue by pwnfish203** [nus-cs2030/2122-s2#273]
Hello, I'm having issues passing this test case. Saw that some people had the same test case issue but my error was a bit different. I have already implemented this.prevRoom.orElse(this) so I'm not sure what went wrong. Thank you!

![Screenshot 2022-04-07 at 10 58 43 AM](https://user-images.githubusercontent.com/99274421/162111510-ba42dea2-53f0-495c-b8ee-f68521ba166f.png)

**Comment by ReganKvioke** [comment]
It seems that the problem lies with your tick() when you are going back to the old room. Maybe you want to double-check your back() function to make sure it only tick once and also that you are storing the correct old room

**Comment by zuohui48** [comment]
Hi, I believe that if the room you are currently in do not have a previous room, and you return to the same room, the time should remain the same, meaning .tick() should not happen. Hope it helps!

**Comment by pwnfish203** [comment]
@zuohui48 @ReganKvioke ok i managed to solve it, thanks guys!
