### ISSUE TITLE
actions.jsh not being read

### ISSUE THREAD

**Issue by andrea-yxl** [nus-cs2030/2122-s2#274]
# Summary

When I try to call new Room("foyer").add(new Sword()).tick(takeSword).tick(takeSword), it throws me an error that my takesword function cannot be found. Anyone knows what's wrong? Thank you!
<img width="473" alt="Screenshot 2022-04-07 at 3 27 30 PM" src="https://user-images.githubusercontent.com/100149561/162145801-0d148b7d-dfb0-4de3-9cc4-41ede729dc28.png">
<img width="415" alt="Screenshot 2022-04-07 at 3 27 57 PM" src="https://user-images.githubusercontent.com/100149561/162145848-98ae03a7-4847-4739-a3e7-87ffebcb1544.png">

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by ryuniqlo** [comment]
hi I think it might be because you forgot to close your for loop in your helper function

**Comment by andrea-yxl** [comment]
I managed to solve it! Thanks for your help @ryuniqlo !
