### ISSUE TITLE
Lab 8 Test case 6_1 (How to update both rooms this and prev when back() is called)

### ISSUE THREAD

**Issue by Lu-Yi-Fan** [nus-cs2030/2122-s2#275]
![Screenshot 2022-04-07 at 4 21 40 PM](https://user-images.githubusercontent.com/88626655/162154219-c45d9273-aadd-47ce-928b-6340c1f16e5b.png)

Hi i am facing these issues for test case 6_1, i looked through the previous forums opened and i think the issue is when i am holding a sword in room b and i go from room b -> room a, it doesnt get removed from room b, hence the many extra lines printed for sword. How do i update both rooms simultaneously in back()? I managed to update the previous room to hold the sword but i dont know how to update current room to drop what im holding

**Comment by pohja1999** [comment]
hello i think you can create a helper called removeSword() after you go to a diff room , basically do return new Room(.....,Optional.of(prevroom.removeSword())) into your constructor. Anw it depends on how you construct your class so ... ◡̈ this is one way ig.  removeSword shud be ez to impl. just filter your objectlist ig.

**Comment by pohja1999** [comment]
anw just break it down in many diff helpers. It'll help i guess. if you wanna drop sword, just create a helper dropsword. I suppose u have an equip/unequip bool state, so to drop a sword u just wanna switch equipped to unequipped as you bring the sword into the new room. sooo yea ◡̈

**Comment by Lu-Yi-Fan** [comment]
thank you! yup i found my error it was in go, when i took a sword, i forgot to remove it before i go next room! thanks for the help @pohja1999
