### ISSUE TITLE
PA2 EOFException

### ISSUE THREAD

**Issue by mingshan2705** [nus-cs2030/2122-s2#281]
Does anyone know what kind of error causes this exception? It seems to "block" the test case from being tested as seen in line 70 of my output

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/85282762/162484000-e317d38a-f0fd-405f-95a1-37ce8cf061ab.png">

**Comment by alantay11** [comment]
Check if your code causes infinite loops?

**Comment by tlylt** [comment]
Test the code locally to verify how fast the code is (and fix it if it is too slow). Doing something like
```java
// 1
Num.of(30000).mul(Num.of(2));
// 2
Num.of(2).mul(Num.of(30000));
```
Should both return the correct answer (60000) in less than ~1 second (definitely should not take more than 2 seconds)

**Comment by mingshan2705** [comment]
Thanks TA :D
