### ISSUE TITLE
How to approach PA2 Level 4?

### ISSUE THREAD

**Issue by Jonacs13** [nus-cs2030/2122-s2#283]
How do I approach PA2 level 4? The question says our Fraction class inherits from AbstractNum class. However, at the same time we are not supposed to define any toString methods in our implementation (correct me if I'm wrong). So I would assume that we have to utilise the Frac class given to us but the constructor in Frac class is private and any child class would not be able to use super() in its own constructor. Anyone can provide some direction or help here? Thanks in advance!

**Comment by pohja1999** [comment]
helloo... when u store a frac inside your abstractnum<frac>.. your tostring method inside abstractnum will retrieve the tostring of frac. and you realised that the frac tostring method is "a:b". sooo yea you don't have to bother abt the tostring method at all.

**Comment by alantay11** [comment]
yup frac and abstractnum will take care of it for you. actually if you defined a toString method checkstyle would auto fail you too.

**Comment by Jonacs13** [comment]
Oh damn... I didn't tot of that. Thanks guys.
