### ISSUE TITLE
Constructor for PQ and .add() 

### ISSUE THREAD

**Issue by t11-20** [nus-cs2030/2122-s2#284]
![ss1](https://user-images.githubusercontent.com/101245687/162577497-6e6e36e7-3cc4-42ea-a375-631bc8371087.JPG)

![ss2](https://user-images.githubusercontent.com/101245687/162577502-f370e8e3-b447-46e4-95ed-ac9c853e3adf.JPG)

Hello! I have tried to work on the project's PQ class. But.. my PQ class is mutable. Am I doing something wrong here? Attached are my .add() and PQ's constructor.

Any help is appreciated! Thank you!

**Comment by yizziepeasy** [comment]
Hi t11-20, I faced this error as well. You just got to carefully trace your code.  For ease of reference, I will use `private final PriorityQueue<T> queue` instead. In the `add` method you are creating newPQ that uses the constructor that takes in a `PriorityQueue<T> pq`. This is where it goes wrong, you are giving your newPQ the current `this.queue` which points to the same thing even when you create a new PQ object. So you got to think of a way to make the newPQ point to a different `queue` to ensure immutability. You may refer to Java API Docs PriorityQueue for ideas. :)

**Comment by t11-20** [comment]
Hi @yizziepeasy thank you for the detailed explanation! I got it! :)
