### ISSUE TITLE
How to solve PA2 level 6?

### ISSUE THREAD

**Issue by Jonacs13** [nus-cs2030/2122-s2#285]
How do I implement the reduce method to simplify fractions? I am assuming a loop is required using the mul method in Num class but I'm not sure how to implement. Any kind soul please advise!

**Comment by mingshan2705** [comment]
I think you can start by writing a helper function to find the GCD of 2 numbers, then another division function to reduce the fraction. Hope this helps!

**Comment by gordengorden** [comment]
I solved it by creating a mod() method for the Num class. Then solved for the gcd of the numerator and denominator using the following algorithm

![image](https://user-images.githubusercontent.com/46585440/162606148-1f68ac15-5f09-486e-90e3-db3cc4476bde.png)

**Comment by Geraldworks** [comment]
I created a method to generate the greatest common denominator, as well as a division method for natural numbers. In my gcd method, I started the divisor with two and kept increasing the prime factorisation by one until the divisor exceeds a condition. (I used a while loop for this)

**Comment by junbin-tan** [comment]
Hi @Jonacs13, you might want to create a `.division()` and `.greatestCommonFactor()` class, inside your Num

This will make it easier after you access the Num in  `.reduce()` found in Fraction.class to reduce to simplest fraction.

**Comment by jlee1007** [comment]
create a gcd method to find the gcd and div method in num to do any "divide" functions u may need

**Comment by Jonacs13** [comment]
Thanks guys!

**Comment by giffordlee** [comment]
@gordengorden hi how do you create a mod() method without using the '%' operator as stated in the qn?

**Comment by gordengorden** [comment]
> @gordengorden hi how do you create a mod() method without using the '%' operator as stated in the qn?

hi @giffordlee, what I did was to call sub() until the next sub() would result in a NaN output

**Comment by giffordlee** [comment]
> hi @giffordlee, what I did was to call sub() until the next sub() would result in a NaN output

i see, thank you!

**Comment by undeser** [comment]
Hi @Jonacs13! I agree with @junbin-tan and @gordengorden on creating a ```divide()``` and ```highestCommonFactor()``` function. Personally, for me, I created an additional ```remainder()``` function to replace the ```%``` operator used in the ```highestCommonFactor()``` function mentioned by @gordengorden. Hope this helps!
