### ISSUE TITLE
Don't understand Level 7 Requirements

### ISSUE THREAD

**Issue by wzs02** [nus-cs2030/2122-s2#286]
# Summary
Hi all, I am confused by how the probability of a server resting and how the input of simulate 7 works for this level, would be grateful if someone could clarify the rules.

For probability: 
On CC, it states than a server, say server 1, with a rest probability of 0.5 will serve 2 customers normally and rest for the next 2 customers before serving the 5th customer. So for other rest probabilities, say 0.6, would it be right to interpret it as: the server will serve 3 customers normally, then rest for the next 2  customers before serving the 6th customer? (I just use the ratio 3/5 = 0.6 here just like how 2/4 = 0.5 when the rest probability is 0.5)

For simulate7:
The code in Main 7 is given as: 
Supplier<Double>` restTimes = () -> rngRest.nextDouble() < probRest ? genRestPeriod() : 0.0
Simulate7 sim = new Simulate7(numOfServers, inputTimes, qmax, restTimes);

So restTimes is a supplier in Main7 BUT in CC it was mentioned that the 4th input is the probability of a server resting (which should be one double only), which does not seem to add up. Also, going by the above logic of probability, why would we need to generate a rest time? Because we already know for sure that the server will miss out on a certain number of customers and immediately resume service as per normal once the ratio of customers served is met.

SORRY FOR THE LONG EXPLANATION HAHA, I'M REALLY LOST ABOUT THIS AND THANKS FOR TAKING THE TIME TO READ THROUGH MY POST :')

## Screenshots (if any): 
![Screenshot 2022-04-10 at 10 44 56 AM](https://user-images.githubusercontent.com/79785001/162598980-a754fef9-76d9-4b58-a27b-d393a3945af9.png)
![Screenshot 2022-04-10 at 10 44 35 AM](https://user-images.githubusercontent.com/79785001/162598982-6945ddbf-476f-4aba-83e7-aef21ff1e067.png)

**Comment by mingshan2705** [comment]
> On CC, it states than a server, say server 1, with a rest probability of 0.5 will serve 2 customers normally and rest for the next 2 customers before serving the 5th customer.

The probability does not tell you the number of customers it serves before resting. The 0.5 rest probability means that there is 50% chance for the server to take a rest after serving a customer, and in the case where they do, you would need to generate the rest time.

Tracing out the codecrunch example:
- server 1 serves customer 1
- server 1 finishes serving customer 1
- server 1 decides to rest with 0.5 probability -> no rest
- server 1 serves customer 2
- server 1 finishes serving customer 2
- server 1 decides to rest with 0.5 probability -> rest
- server 1 rests for x amt of time (get x by using the supplier)
- server 1 finishes resting
- server 1 serves customer 5 and so on...

Hope this helps!

**Comment by hengyjj** [comment]
Hi @wzs02! Could I clarify how did you proceed with your Level 5 of Project? I am still stucked at that level. Thank you!

**Comment by wzs02** [comment]
Hey there @hengyjj ! I assume ur implementation now was similar to mine in #247. I solved it by recoding everything and changing my implementation completely HAHA, like I changed my code all the way from level 2 to level 5 (starting from customer, server, all simulate classes and all serve events). This sounds very drastic but I was forced to do so because my previous implementation wouldn't allow me to call at the serve event only (I had to call at wait for it to work). 

As for how I came up with my new implementation, I referred to your post #260 for inspiration and it helped a lot. Hope this helps and if u have any doubts, do feel free to comment back and I'll try to help!

**Comment by wzs02** [comment]
@mingshan2705 thank you for the detailed reply! I'll give it a go now

**Comment by hengyjj** [comment]
> Hey there @hengyjj ! I assume ur implementation now is similar to mine in #247. I solved it by recoding everything and changing my implementation completely HAHA, like I changed my code all the way from level 2 to level 5 (starting from customer, server, all simulate classes and all serve events). This sounds very drastic but I was forced to do so because my previous implementation wouldn't allow me to call at the serve event only (I had to call at wait for it to work).
> 
> As for how I came up with my new implementation, I referred to your post #260 for inspiration and it helped a lot. Hope this helps and if u have any doubts, do feel free to comment back and I'll try to help!

Thank you wzs! I will take a look.

**Comment by wzs02** [comment]
> The probability does not tell you the number of customers it serves before resting. The 0.5 rest probability means that there is 50% chance for the server to take a rest after serving a customer, and in the case where they do, you would need to generate the rest time.
> 
> Tracing out the codecrunch example:
> 
> * server 1 serves customer 1
> * server 1 finishes serving customer 1
> * server 1 decides whether to rest with 0.5 probability -> no rest
> * server 1 serves customer 2
> * server 1 finishes serving customer 2
> * server 1 decides whether to rest with 0.5 probability -> rest
> * server 1 rests for x amt of time (get x by using the supplier)
> * server 1 finishes resting
> * server 1 serves customer 5 and so on...

Hi @mingshan2705, how would you know whether the server decides to rest based on the stimulation? I looked at the Main7 file and there seems to be no indication of whether the server decides to rest, other than the supplier. So currently I'm calling the supplier after each DONE event, but it seems to be wrong..

**Comment by hengyjj** [comment]
Hi @wzs02! I just wanna ask did you encounter the issue for Level 6 where a server will serve the waiting customers all at once? Do you have any suggestions on how to overcome this issue too? Thank you!

Something like this.
![image](https://user-images.githubusercontent.com/77519191/162906170-f42ff069-9892-4b08-a31b-aeef5d672200.png)

**Comment by E0857389** [comment]
> 
 so does this mean that we just call the supplier and it may just give us a possibility to rest or not ? im not sure how the probability works

**Comment by wzs02** [comment]
@hengyjj sorry for the late reply, I missed this out. I didn't encounter this issue and I'm not sure of ur implementation, but maybe you could try looking into the state of your shops and servers, and see if they are updating in the way that you want it to update. From there, you could identify the methods that are not functioning as expected and change ur code accordingly. Personally I approached this level by creating an attribute in my server and updating the time of completion from there.

**Comment by wzs02** [comment]
@E0857389 yes, but be sure to call the probability ONLY WHEN you need to, otherwise the sequence of values will not be the same as the one in CC. The random values will be consistent with the ones in CC if you call them correctly, because the values in the generator (refer to Main7.java) are defined by a log function.
