### ISSUE TITLE
Time exceeded error Level 5

### ISSUE THREAD

**Issue by wk1267** [nus-cs2030/2122-s2#29]
# Summary

Hi, I have faced this error when trying to clear level 5. 

## Description:

My code currently works for the test cases in level 5, but fails in codecrunch. I used a nested for loop within a for loop, with a while loop inside. Please advise if its a problem of algorithmic inefficiency or other errors I may not have foreseen. 

## Screenshots

![image](https://user-images.githubusercontent.com/97509680/154112363-bc7575d8-54c2-46e3-a81b-d44754c35946.png)

**Comment by ldkai** [comment]
Hi I believe you may have run into an infinite loop - if you are using a while loop do check if you missed out a condition to break the loop

**Comment by wk1267** [comment]
Hi, thanks for the feedback. After debugging I have realised indeed that I was stuck in an infinite loop.
