### ISSUE TITLE
Generating the correct numbers for Level 7 

### ISSUE THREAD

**Issue by wzs02** [nus-cs2030/2122-s2#291]
# Summary
Hi, can I ask how we are supposed to generate the wait times for level 7 correctly? I'm not really sure of how to check whether the server decides to rest before calling the supplier which generates the times, so I'm now calling the supplier in Main 7 after every DONE event and getting incorrect values. Would appreciate some assistance on how to approach this, thank you!

**Comment by michael192002** [comment]
For me, I generated the rest times from the server itself, and it works, but I'm not sure if that's the best way.

**Comment by wzs02** [comment]
Hi, could you elaborate more on your approach? I believe it's similar to what I'm doing now, as I stored the supplier in the server and will call the supplier to get the rest time after each done event. However, in test7_2, the server does not rest after serving customer 1, but I'm getting a rest time that is not zero.

**Comment by michael192002** [comment]
Hi, so basically every time a DONE event is issued, I get the restTime from the specific server involved in the DONE event; if your program yields an incorrect rest time perhaps you could check if you called the right server during runtime?

**Comment by wzs02** [comment]
Thanks for ur reply! I think I thought too deeply into the rules HAHA

**Comment by bryanwonggy** [comment]
> Hi, could you elaborate more on your approach? I believe it's similar to what I'm doing now, as I stored the supplier in the server and will call the supplier to get the rest time after each done event. However, in test7_2, the server does not rest after serving customer 1, but I'm getting a rest time that is not zero.

hello, I got the same issue as you. may I know if you solved it?
