### ISSUE TITLE
Codecrunch issue (illegal start of expression)

### ISSUE THREAD

**Issue by yizziepeasy** [nus-cs2030/2122-s2#294]
Hi, I'm facing a problem with submission of files on Codecrunch. Anyone managed to resolve this issue or have a workaround?

<img width="891" alt="Screenshot 2022-04-11 at 2 41 46 PM" src="https://user-images.githubusercontent.com/74005160/162683981-c1206319-df81-41ad-b8e4-7e00823bbcf4.png">

**Comment by gordengorden** [comment]
hi @yizziepeasy, is the package line the first line of your file?

**Comment by yizziepeasy** [comment]
> hi @yizziepeasy, is the package line the first line of your file?

Hi @gordengorden, yes it is. Am I supposed to put it somewhere else?

**Comment by gordengorden** [comment]
> > hi @yizziepeasy, is the package line the first line of your file?
> 
> Hi @gordengorden, yes it is. Am I supposed to put it somewhere else?

Nope that is correct. Hm strange, I just submitted my files and didn't encounter this issue.

**Comment by yizziepeasy** [comment]
> > > hi @yizziepeasy, is the package line the first line of your file?
> > 
> > 
> > Hi @gordengorden, yes it is. Am I supposed to put it somewhere else?
> 
> Nope that is correct. Hm strange, I just submitted my files and didn't encounter this issue.

How many test cases are shown on your codecrunch? Yesterday they ran 25 test cases for my code but today there are 43.

![Uploading Screenshot 2022-04-11 at 4.17.45 PM.png…]()

**Comment by jamietan123** [comment]
I think there's many issues about this right now, it could be a system error!

**Comment by Darien2307** [comment]
> > > > hi @yizziepeasy, is the package line the first line of your file?
> > > 
> > > 
> > > Hi @gordengorden, yes it is. Am I supposed to put it somewhere else?
> > 
> > 
> > Nope that is correct. Hm strange, I just submitted my files and didn't encounter this issue.
> 
> How many test cases are shown on your codecrunch? Yesterday they ran 25 test cases for my code but today there are 43.
> 
> <img alt="Screenshot 2022-04-11 at 4 17 45 PM" width="447" src="https://user-images.githubusercontent.com/74005160/162694532-adb4f714-a564-4b05-b6ef-bb1fab37bdbf.png">

Based on today's lecture, Prof Henry has included more test cases, for correctness and checkstyle.

**Comment by Darien2307** [comment]
There is indeed something wrong with Codecrunch today. Prof Henry has already emailed their side and they should be rectifying.
