### ISSUE TITLE
toString() error for level 1

### ISSUE THREAD

**Issue by raynang** [nus-cs2030/2122-s2#295]
Hello, I'm not sure why I'm getting this error in my toString() method in Room class. 

![Screenshot (1067)](https://user-images.githubusercontent.com/99885253/162703888-f1d545de-574b-44ea-894b-ebd3aadcab94.png)

**Comment by hengyjj** [comment]
Hi not too sure what is your implementation but if you are += to a string, you could put "\n" to the next line. 

For example,
String str = "Hello";
str += "\n";
return str;

Not sure if it helps but you could try it out.

**Comment by raynang** [comment]
> Hi not too sure what is your implementation but if you are += to a string, you could put `\n`to the next line.
> 
> For example,
> 
> ```
> String str = "Hello";
> str += "\n";
> return str;
> ```
> 
> Not sure if it helps but you could try it out.

Yep, I did this already but for some reason, the string output returns the string with \n inside as shown in the screenshot above instead of inserting the string after the \n into a new line.

**Comment by Darien2307** [comment]
What does your code look like?

**Comment by raynang** [comment]
public String toString() {
    String res = "@" + name;
    for (Item item : items) {
        res += "\n" + item.toString();
        }
        return res;
    }

**Comment by raynang** [comment]
> What does your code look like?

public String toString() {
String res = "@" + name;
for (Item item : items) {
res += "\n" + item.toString();
}
return res;
}

**Comment by yongchein-o** [comment]
res += "\n" + item.toString();

maybe you wanna separate this?

**Comment by hengyjj** [comment]
> > What does your code look like?
> 
> public String toString() { String res = "@" + name; for (Item item : items) { res += "\n" + item.toString(); } return res; }

You can try:
```
public String toString() {
String res = "@" + name;
for (Item item : items) {
res += "\n";
res += item.toString();
}
return res;
}

```

**Comment by Darien2307** [comment]
> > > What does your code look like?
> > 
> > 
> > public String toString() { String res = "@" + name; for (Item item : items) { res += "\n" + item.toString(); } return res; }
> 
> You can try:
> 
> ```
> public String toString() {
>     String res = "@" + name;
>     for (Item item : items) {
>        res += "\n";
>        res += item.toString();
>      }
>      return res;
> }
> ```

You can try this, but mine was the same as yours.
Did you try this in jshell? Was the output the same as in Codecrunch?
Otherwise, could be another Codecrunch issue...

**Comment by szeying02** [comment]
You could also try this alternative method:
`res += String.format("%n%s", item.toString());`
%n represents a new line
