### ISSUE TITLE
Incorrect Packaging 

### ISSUE THREAD

**Issue by loqir** [nus-cs2030/2122-s2#298]
![image](https://user-images.githubusercontent.com/100114362/162795088-facb4244-7998-459e-b459-fbc013e51bb2.png)

hello has anyone encountered this/ know what is the issue?

At the top of all my files, i typed package cs2030.simulator;  except for PQ,Pair and ImList where i typed package cs2030.util;
I have also set all my classes to be public and my code is able to compile and run in vim.

Thanks!

**Comment by jlee1007** [comment]
are your java files stores outside of the cs2030 folder?

**Comment by loqir** [comment]
hi i thought we are only required to submit java files to codecrunch, do we submit the entire cs2030 folder?

**Comment by sc00tt** [comment]
Should store all your java files outside of you cs2030 folder, then let package cs2030.simulator and cs2030.util create the sub-folders for you. Do make sure that the util and simulator files are put in the right folders, could be a simple spelling error

**Comment by loqir** [comment]
thanks everyone for the help! I realised I did not create a simulate class for each level and just used the main class itself to run
