### ISSUE TITLE
When is the project deadline?

### ISSUE THREAD

**Issue by TohDeKai** [nus-cs2030/2122-s2#299]
I cannot find the project deadline in the announcements

**Comment by loqir** [comment]
Hi according to codecrunch it is 24 Apr 2022 23:59:59

**Comment by yizziepeasy** [comment]
24 April, Sunday 2359!

**Comment by Ahuanglovescoding** [comment]
It's due on 24 April 23:59~~

**Comment by HaiJin123** [comment]
24 April 23:59!

**Comment by Lu-Yi-Fan** [comment]
24 April !
