### ISSUE TITLE
PA2 Level 3 Sub

### ISSUE THREAD

**Issue by Canoya** [nus-cs2030/2122-s2#304]
After negating the symbol and adding the number, **and if the number is less than 0**, how to change it back to invalid? How do you check for this part? Or is my methodology wrong

**Comment by Guanjung27** [comment]
you can make use of the filter function as mention here https://github.com/nus-cs2030/2122-s2/issues/288#issuecomment-1094225165

**Comment by kayyenl** [comment]
Hi @Canoya , your thinking is not wrong! In addition to the filter suggestions above, also keep in mind that the isValid() in the AbstractNum class does not do the checking for you, and only sees if the contained object is empty or not. Hope this helps!

**Comment by jlee1007** [comment]
you can also check the new fraction & return an empty optional if it is invalid! this might be longer but clearer

**Comment by undeser** [comment]
Hi @Canoya, the approach for level 3 was discussed in a [previous thread](https://github.com/nus-cs2030/2122-s2/issues/288#issuecomment-1094225165).

To summarise, before returning, you might want to filter the ```opt``` using ```.filter(x -> AbstractNum.valid.test(x))```.

Hope this helps!
