### ISSUE TITLE
PA2 level 6 reduce()

### ISSUE THREAD

**Issue by Guanjung27** [nus-cs2030/2122-s2#305]
Anyone has ideas on how to approach this level?

**Comment by junbin-tan** [comment]
You might want to create a `.divide()` & `.getGreatestCommonFactor()` methods inside your `Num.class`

So when you do your `.reduce()` you can just `.flatMap(.map())` to access the Num inside, and reduce it to the smallest value.

Hope this helps!

**Comment by shotnothing** [comment]
For finding GCF, take a look at the Euclidean algorithm

**Comment by kayyenl** [comment]
Hi @Guanjung27 ! I agree with @junbin-tan , **implementing a divide function would make things easier once you found your GCD. As for finding the GCD itself, I have seen some use the implementation of streams to tackle this problem (implementing a GCD algorithm that you can find online)**, but I did it a much more primitive way. 

My primitive way involves multiplying numbers till they match the numbers in your fraction, and outputting the common number that both numbers in my fraction has. I could give you some more pointers if you wish to know how I did it! It is slightly more lengthy though. Hope this helps!

**Comment by jlee1007** [comment]
i created a gcd, divide method on top of reduce!
i then returned a optional gcd and used map to divide the fraction by the gcd!

**Comment by undeser** [comment]
Hi @Guanjung27, there is an [existing thread](https://github.com/nus-cs2030/2122-s2/issues/285) that discussed a similar method!

But to reiterate both the above thread and @junbin-tan, creating a ```divide()``` and ```highestCommonFactor()``` function in your ```Num``` class. 

Once you have these functions, simply find the HCF between the numerator and denominator, dividing them by their HCF to obtain the "reduced" (simplified) fraction.

Hope this helps!
