### ISSUE TITLE
Lab 8 test 6_1

### ISSUE THREAD

**Issue by chloeoxe** [nus-cs2030/2122-s2#308]
Hi, 

does anyone know what could be wrong such that I keep failing this test case? The output is rather vague, so I can't figure out what's wrong. Any input would help, thank you!

<img width="466" alt="Screenshot 2022-04-12 at 5 17 13 PM" src="https://user-images.githubusercontent.com/97609174/162927479-d19cde58-5779-4103-a6de-d60df5c625fa.png">

**Comment by zuohui48** [comment]
You may want to take a look at your back method. If you go back to the same room, the time in that room does not change.

**Comment by jlee1007** [comment]
you might have ticked too much. do check your back method that you did not tick excessively!

**Comment by maximyam** [comment]
for the back method, if there is no previous room, it should return to the current room, not a tick version of that room

**Comment by kkinmunn** [comment]
It seems likely your back() method might have some errors from the test cases. If previous room does not exist, return `this` (which is the current room but without any `tick()`). Else, return `previousRoom.tick()`. In this case, you will only tick once, when you move back to the previous room or tick none if there are no previous room. Hope this helps!

**Comment by chloeoxe** [comment]
Yup, I fixed it. I forgot to implement the if statement to check whether the previous room is just the current room, so I ticked too many times. Thx everyone for the help!
