### ISSUE TITLE
How do you break tie between events with the same timing

### ISSUE THREAD

**Issue by yongchein-o** [nus-cs2030/2122-s2#309]
Hi can anyone enlighten me on how to break tie between events that have the same timing?

For example I want the done event to be polled first 

1.500 1 done serving by 1
1.500 2 serves by 1

**Comment by SoSimplySean** [comment]
Hi, I basically just compared the event's customer IDs within the comparator if the events are tied for time. Believe you'll always want the customer who arrived first (ie. lower ID) to be polled first.

**Comment by Swagston20** [comment]
compare the id

**Comment by jlee1007** [comment]
compare the id as in the event of a time tie, the sort will be in id ascending order
