### ISSUE TITLE
@Override when a class implements an interface.

### ISSUE THREAD

**Issue by DikshantDulal** [nus-cs2030/2122-s2#31]
# Summary

@Override throws an error when a class implements a method from an interface.

## Description:
When I code my interface in a separate file and then implement that interface from a class then **@Override** throws me an error. But when I write my interface in the same .java file as the class, @Override works. Why is that the case? Does that mean we shouldn't use **@Override** when a class implements a method of an interface? 

## Screenshots
<img width="649" alt="Screenshot 2022-02-18 at 7 08 03 PM" src="https://user-images.githubusercontent.com/73227786/154671469-58316d60-e45e-42e0-849a-79d46f1d83c7.png">

**Comment by bl7447** [comment]
hmm, did you try opening your ComputeFare java file in jshell first?

**Comment by szeying02** [comment]
Two things to look at when this happens would be: the order and type of the arguments that the method that is being overridden takes in. The other thing to keep an eye out for is the name of the methods -- have to make sure it's the same! I had the same issue today as well haha. Good luck!

**Comment by DikshantDulal** [comment]
Apparently, I didn't open Request.java before running JustRide.java in jshell haha. Thank you both for your comments.
