### ISSUE TITLE
Hidden test case for level 2/3

### ISSUE THREAD

**Issue by Noel-Lee** [nus-cs2030/2122-s2#313]
# Summary
Issue with hidden test case using current implementation

Does anybody have an idea what the hidden test case is at the end of level 2? Seem to have used up all the resources on one of the test cases before proceeding to level 3. 

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/79415498/163095798-c44e59e8-6736-4262-a6ef-26b35c8e806f.png)

**Comment by ryuniqlo** [comment]
hi u might want to check #281, testing locally helped me understand what caused the error

**Comment by undeser** [comment]
Hi @Noel-Lee, think somebody experienced something similar to your case in a [previous thread](https://github.com/nus-cs2030/2122-s2/issues/281) as mentioned by @ryuniqlo. 

Hope this helps!
