### ISSUE TITLE
Project Test Case 3_2

### ISSUE THREAD

**Issue by seanpbteo** [nus-cs2030/2122-s2#314]
# Summary
Hello all, I've run into this issue where my shop does not update with a server that is able to wait after it serves the customer that is waiting. However, I implemented my execute method in DoneEvent to make that server available and able to Wait on another customer. Has anyone else run into the same problem?

## Description 
Describe the problem and code snippets if necessary 
My DoneEvent.execute()
<img width="698" alt="image" src="https://user-images.githubusercontent.com/99883397/163099911-4aa5634b-a6e4-462d-9bda-55ce0719bf74.png">

## Screenshots (if any): 
<img width="424" alt="image" src="https://user-images.githubusercontent.com/99883397/163096370-039f424e-0d66-443a-8e15-a02085826ea7.png">

**Comment by ongyongen** [comment]
Hi! This is how I solved it for now, not sure if it is the best way or not. Would like to hear other ways to solve too!
These are my steps 
1) For each customer, create their respective arrive events
2) Check current state of the shop 
     > Purge done events 
     > Serve the next customer in the queue (if any)
3) Assign new arrive event to a suitable server (to serve immediately / queue)

**Comment by yongchein-o** [comment]
For my done event. I change the currentCustomer for my Server to Optional.empty(). And by right if you have someone in the queue, your PriorityQueue will already have a Serve Event which will immediately get executed. If not, since my currentCustomer is Optional.empty(), when my shop checks for available Servers, this sever will be flagged as available

**Comment by YangHaoying** [comment]
Hii! From the codes you provided, the logic seems correct. I’d suggest checking your implementation of shop.changeServer and your conditions of checking whether a server is available in Server class and Arrive event. There might have been a mismatch in these implementations which led to the error. Hope this helps!
