### ISSUE TITLE
Level 7_3 Hidden Test Case

### ISSUE THREAD

**Issue by yjjjiajie** [nus-cs2030/2122-s2#322]
# Summary
Hi, did anyone face anything similar for Project Level 7_3? What did yall do to solve it? Thanksss

## Screenshots (if any): 
Insert Images here if necessary
![Screenshot 2022-04-14 at 2 45 27 PM](https://user-images.githubusercontent.com/80145122/163330807-8c7c26e9-be87-4b4a-9ece-dee2f113719b.png)

**Comment by weihan10** [comment]
I faced this issue awhile back too. Iirc, it's similar to an edge case issue. As you can see, the error begins at the leave condition of your output, thus the rest snowballs.

**Comment by yjjjiajie** [comment]
@weihan10 hi can I know whats the edge case and how did you go about solving it?

**Comment by wzs02** [comment]
@yjjjiajie u can refer to #303, I think it'll help
