### ISSUE TITLE
Level 6 tick() and back() strange behaviour

### ISSUE THREAD

**Issue by sinlerr** [nus-cs2030/2122-s2#323]
# Summary

hello! i cant pass the level 6 test cases. my code works for some test cases but not for all. for example, r3.tick().back() leads me back to r2 but r3.tick(takeSword).back() causes me to still be in r3.. am confused why does my tick().back() work but not tick(func).back()? any help will be appreciated thank you!

## Screenshots

![Screenshot 2022-04-14 at 3 49 42 PM](https://user-images.githubusercontent.com/100189830/163339801-f7839ff3-f691-4631-97ff-6831903523e8.png)

**Comment by herq-ules** [comment]
hello! did you change your function in tick(func) accordingly to account for the previous room as well?

**Comment by sinlerr** [comment]
> hello! did you change your function in tick(func) accordingly to account for the previous room as well?

hi! i changed my tick() method then my tick(func) used the modified tick() method
so i think my tick(func) has no areas to change? my tick(func) looks like this now!

Room tick(Function<Room,Room> func) {
      return func.apply(this).tick();
 }

**Comment by bryankwe** [comment]
> > hello! did you change your function in tick(func) accordingly to account for the previous room as well?
> 
> hi! i changed my tick() method then my tick(func) used the modified tick() method so i think my tick(func) has no areas to change? my tick(func) looks like this now!
> 
> Room tick(Function<Room,Room> func) { return func.apply(this).tick(); }

My tick(func) is exactly the same as yours. Did you ensure that your return statements for your functions in actions.jsh call the input room's previous room?

**Comment by sinlerr** [comment]
ok i found my error haha i didnt change the new room in my actions.jsh to accommodate the change in constructor!
