### ISSUE TITLE
Project Level 8

### ISSUE THREAD

**Issue by giffordlee** [nus-cs2030/2122-s2#327]
Hi, can you guys provide some suggestions on how to solve this level? 
My idea is to record down the first self-checkout ID to display in WaitEvent but in the background the customer will wait for the self-checkout with the earliest nextAvailableTime, but somehow I can't get this to work. Do I need to create a new SelfCheckout class that extends server or what else can I do? Thanks!

**Comment by wk1267** [comment]
Do u _need_ to create a new selfcheckout class? prob not, depending on ur implementation.
But I did create a separate class that extends server, and have found some success in that

**Comment by Yang990121** [comment]
I created a new SC class that extends server and it works :)

**Comment by giffordlee** [comment]
@wk1267 @Yang990121 thank you! May i know how did you guys implement the shared queue for self-checkout?
