### ISSUE TITLE
lvl 9 statistic wrong

### ISSUE THREAD

**Issue by wk1267** [nus-cs2030/2122-s2#328]
## Description 
Hi, was wondering if anyone else faced a similar error when trying to pass the test case? if so, might it be due to things like java dealing with large numbers, or just some error in code logic that only appears when u have large no. of customers? idk the test case, but it seems like all the events that transpired before seemed to be correct

<img width="634" alt="Screenshot 2022-04-15 at 12 56 04 AM" src="https://user-images.githubusercontent.com/97509680/163437178-db270529-0006-43ad-8fe8-47ae99f20c24.png">

**Comment by weihan10** [comment]
I managed to pass this, and oh my I didn't notice 9_09 was so large until I saw this post.... but it can't be with java and large numbers, mine worked perfectly. I think you can try to look at the logic of how you implemented the time, might be a very small corner case?

**Comment by Yang990121** [comment]
Wa I feel bad for you man, but I don't think it is because java cannot deal with large numbers, mine also works

**Comment by wk1267** [comment]
helo may i ask if yall @Yang990121  @weihan10  used lazy to deal with customer service times? cos i didn't use lazy, and maybe my laziness to not use lazy has cost me this level 😞 thanks !!

**Comment by Yang990121** [comment]
Nope I didnt use lazy also 
Im pretty sure u just made some careless mistakes, just read all your method and tell yourself what it is doing, maybe u missing some corner cases

**Comment by weihan10** [comment]
> helo may i ask if yall @Yang990121 @weihan10 used lazy to deal with customer service times? cos i didn't use lazy, and maybe my laziness to not use lazy has cost me this level 😞 thanks !!

I didn't use Lazy class, I simply called the get() only when it's a ServeEvent. There's absolutely no need to use Lazy imo haha

**Comment by wk1267** [comment]
Hi if anyone has faced a similar error, it is because i used == instead of .equals() to compare 2 (huge) integers. I have since fixed it !! thank you all
