### ISSUE TITLE
[Level 2] Must Event be an interface?

### ISSUE THREAD

**Issue by haoyangw** [nus-cs2030/2122-s2#329]
# Summary
Can I define Event as an abstract class directly?

## Description 
Level 2 provides us with an `Event` interface to use. Can I completely don't use it and define my own abstract class even in Level 2? I remember reading another issue on this question but can't find it anymore. And I'm not sure if Level 2's test cases require that `Event` is an interface. Because if possible, I don't want to have to change it into an abstract class in later Levels. Unless I define an abstract class that implements the given `Event` interface and then my actual events will extend this abstract class but doesn't directly implement the `Event` interface?

## Screenshots (if any): 
N/A

**Comment by alantay11** [comment]
Nope it doesn't have to be.

**Comment by Zhenyubbx** [comment]
I think using the Event as an interface will work as well.

**Comment by morksen123** [comment]
Think someone mentioned abstract class is ok

**Comment by jamietan123** [comment]
I used abstract class, which is more helpful i think

**Comment by haoyangw** [comment]
thanks everyone!
