### ISSUE TITLE
Simulate 7 conflicts with Simulate 8 

### ISSUE THREAD

**Issue by wzs02** [nus-cs2030/2122-s2#330]
# Summary
Hi, I have managed to get my code to run for the specified test cases in level 7 and level 8. However, I realised that test8_1.in does not work for my simulate7 when I changed the arguments of test8_1.in to 4 inputs instead of 5. Similarly, the level 8 equivalent of the hidden test case 7_3 does not work for my simulate8.  My implementation for simulate 7 and simulate 8 was slightly different, in terms of when the serve event was created. 

For simulate7,  I created a serve event for every delayed wait event (when the server is not ready but a customer waits), but in simulate 8 I only created the serve event after the done event. If I applied the level 7 code to level 8, I would get wrong timings for the serve event when multiple customers wait at the server simultaneously.

Would appreciate some assistance on how I can better implement Simulate 7 and Simulate 8, thank you!

**Comment by teresasee** [comment]
' I would get wrong timings for the serve event when multiple customers wait at the server simultaneously'

**Comment by teresasee** [comment]
> ' I would get wrong timings for the serve event when multiple customers wait at the server simultaneously'. I got this error previously. My implementation was a combination of your simulate7 and simulate8. I created a serve event for every delayed wait event, as well as created a serve event after each done event. For the 'create serve event for every delayed wait event' I had to add a condition to check that the customer is the only one in the queue, cos if e.g. the customer is 2nd in queue, then that customer's serve event will be created after the done event of the previous customer in queue, hence there is no need to create a serve event after this wait event. Hope this will help you!

**Comment by WenJett** [comment]
Hello,

Faced the same issue as well, what I did was similar to your delayed wait event but adds an additional condition to check which is to only create a serve event only if the customer is the next immediate in the queue. Otherwise, it will be a delayed wait event again for the remaining customers in the queue until the server is free again.

**Comment by wzs02** [comment]
Thanks for the help! I solved it
