### ISSUE TITLE
Level 0 and 1 PQ add confusion

### ISSUE THREAD

**Issue by Canoya** [nus-cs2030/2122-s2#331]
How are you supposed to implement add? Am I supposed to sort the list as I add an element to PQ? because if I do that then my code will fail the implementation in level 0. What's the pattern?

> jshell> pq = pq.add(new EventStub(new Customer(3, 0.7), 1.7))
pq ==> [1.700, 3.500, 2.600]

**Comment by alantay11** [comment]
No, the way the pq is sorted when displayed [1.700, 3.500, 2.600] is handled by java. The sorting that we want is the order in which the elements are polled. If you just add them in straight they should come out in that strange order given and be able to be polled according to a comparison you define somewhere else.

**Comment by Canoya** [comment]
> No, the way the pq is sorted when displayed [1.700, 3.500, 2.600] is handled by java. The sorting that we want is the order in which the elements are polled. If you just add them in straight they should come out in that strange order given and be able to be polled according to a comparison you define somewhere else.
> 
> I think there's a more detailed explanation here. #87

so, the way PQ is sorted as shown in its toString() method doesnt really matter? as long as my poll() is done correctly?

**Comment by alantay11** [comment]
yup the tostring is some arbitrary way of sorting, you only need to get poll right and it should work fine

**Comment by Zhenyubbx** [comment]
To implement add, you can just use the PriorityQueue add method because it will help you sort the list accordingly. Don't really have to worry bout how the sorting works.

**Comment by Yang990121** [comment]
The entire PQ is very similar to how prof did his ImList, can just copy most of the idea inside
