### ISSUE TITLE
Project Level 3 Updating Servers Issue

### ISSUE THREAD

**Issue by b1n4chan** [nus-cs2030/2122-s2#332]
hello,
how do i update my servers after a done event? like eg when there's only 1 server and customer 4 arrives, before that the server has to be updated such that it is now busy serving customer 2 and wait is now empty such that customer 4 can go to wait

currently i tried checking my servers for done and updating them (i.e if served customer is done, wait customer will now be served and wait becomes empty OR if all previous customers are done and server is free and wait empty), i only checked for shop updates when the arriving customer's arrival time is >= to any of the done events' times, otherwise it just uses the existing shop returned from execute methods

right now my code works for test case 1 but the moment there's more than 3 customers, only events for customer 1 and 2 are printed correctly and every other customer arrives and leaves... so can anyone advice me how i can go around solving this issue? or let me know the logic that you have used to update your servers, thank you!

**Comment by shotnothing** [comment]
Don't base your server on times, you will regret it in higher levels (the one with Lazy supplier). What I did was keep a list of customers _without_  any reference to time, and all the timing logic is done in my events and simulateX::run. 

For what's wrong, can't really tell from this much information but my guess is that you are not freeing up your servers after they are done, causing all new customers to think they are unable to wait and end up just leaving.

**Comment by b1n4chan** [comment]
> Don't base your server on times, you will regret it in higher levels (the one with Lazy supplier). What I did was keep a list of customers _without_ any reference to time, and all the timing logic is done in my events and simulateX::run.
> 
how did you do the timing logic in your events? i wanted to update my servers in the done event class but i cant figure out what conditions to do so.  also what do you mean by customer list without reference to time as a customer is linked to arrival time and we need to sync server updates with customer arrival times?

**Comment by jamietan123** [comment]
You can free the server after each Done event, and each event should link to the next event without depending on time. So Wait event will link to Serve event.

**Comment by shotnothing** [comment]
@b1n4chan Whenever there is a `Done` event, check (inside simulateX::run loop) if there are more customers in that server. If so, add a new serve event into the PQ with customer being the customer in the server.

Also sorry I meant that even though customer has arrival time, your server updates need not refer to them at all (at least until the resting level, where you can get by with a minor change). All your server keeps tracks of in this level is a queue of customers.

**Comment by kiacheng** [comment]
> @b1n4chan Whenever there is a `Done` event, check (inside simulateX::run loop) if there are more customers in that server. If so, add a new serve event into the PQ with customer being the customer in the server.
> 
> Also sorry I meant that even though customer has arrival time, your server updates need not refer to them at all (at least until the resting level, where you can get by with a minor change). All your server keeps tracks of in this level is a queue of customers.

@shotnothing 
hii i made use of of what u said here for level 3 and it has worked well so far up till level 6. However, i am facing a bit of trouble on this implementation in level 7 where servers are allowed to rest. I checked if the event is a done event and checked if the server is resting and modified the shop under the loop itself. Then i added a serve event at the time done.getTime + rest time from supplier. I'm not too sure if I am going in the right direction as the test cases seem to come out weird. May I know how you approached level 7? Would appreciate your insight into this matter!
