### ISSUE TITLE
Project Level 8 Implementation 

### ISSUE THREAD

**Issue by yjjjiajie** [nus-cs2030/2122-s2#333]
# Summary
Hi, does anyone have any tips on how to implement the part about all self-checkout counters having the same waiting queues. Thanks !

**Comment by weihan10** [comment]
For me I used an ImList<Customer> called waitList in my Simulate8.java and added to it everytime there is a WaitEvent at the selfchecks( whose id > number of normal servers ) and remove from it everytime a selfcheck serves it ( basically you can do this by checking if the waitList has any customer everytime there is a DoneEvent by a selfcheck counter. ). I'm sure there is a better way to do this, but for me at least, this is a very straightforward way that requires only additonal 3 lines of code.

**Comment by yizziepeasy** [comment]
> For me I used an ImList<Customer> called waitList in my Simulate8.java and added to it everytime there is a WaitEvent at the selfchecks( whose id > number of normal servers ) and remove from it everytime a selfcheck serves it ( basically you can do this by checking if the waitList has any customer everytime there is a DoneEvent by a selfcheck counter ). I'm sure there is a better way to do this, but for me at least, this is a very straightforward way that requires only additional 3 lines of code.

Did you manage to pass level 9 test cases?

**Comment by weihan10** [comment]
> > For me I used an ImList called waitList in my Simulate8.java and added to it everytime there is a WaitEvent at the selfchecks( whose id > number of normal servers ) and remove from it everytime a selfcheck serves it ( basically you can do this by checking if the waitList has any customer everytime there is a DoneEvent by a selfcheck counter ). I'm sure there is a better way to do this, but for me at least, this is a very straightforward way that requires only additional 3 lines of code.
> 
> Did you manage to pass level 9 test cases?

Yup haha, 43/43. With proper logic (only adding 7 lines at the start of my run() method in my Simulate8 class), it did the magic. Previously I was stuck at test case 37. But adding those lines took care of edge cases and it passed perfectly.

**Comment by Yang990121** [comment]
for me i put the queue in the shop

**Comment by E0857389** [comment]
> > > For me I used an ImList called waitList in my Simulate8.java and added to it everytime there is a WaitEvent at the selfchecks( whose id > number of normal servers ) and remove from it everytime a selfcheck serves it ( basically you can do this by checking if the waitList has any customer everytime there is a DoneEvent by a selfcheck counter ). I'm sure there is a better way to do this, but for me at least, this is a very straightforward way that requires only additional 3 lines of code.
> > 
> > 
> > Did you manage to pass level 9 test cases?
> 
> Yup haha, 43/43. With proper logic (only adding 7 lines at the start of my run() method in my Simulate8 class), it did the magic. Previously I was stuck at test case 37. But adding those lines took care of edge cases and it passed perfectly. It's just a matter of dealing with the fact that they share the same queue. So you have to insert an if-else condition (e.g. if that event's next event is a WaitEvent at a server ID > numOfServers(self checks have ID > numOfServers) and your waitList.size() < qmax, you create a new WaitEvent at self check k + 1, else create a new LeaveEvent if waitList.size() >= qmax). Also, take note to be careful which event to add into pq.

did u extend the self scheck out from server? because when i did it the tostring method still returns servers tostring and not the overriden tostring

**Comment by yuuutong** [comment]
> > > > For me I used an ImList called waitList in my Simulate8.java and added to it everytime there is a WaitEvent at the selfchecks( whose id > number of normal servers ) and remove from it everytime a selfcheck serves it ( basically you can do this by checking if the waitList has any customer everytime there is a DoneEvent by a selfcheck counter ). I'm sure there is a better way to do this, but for me at least, this is a very straightforward way that requires only additional 3 lines of code.
> > > 
> > > 
> > > Did you manage to pass level 9 test cases?
> > 
> > 
> > Yup haha, 43/43. With proper logic (only adding 7 lines at the start of my run() method in my Simulate8 class), it did the magic. Previously I was stuck at test case 37. But adding those lines took care of edge cases and it passed perfectly. It's just a matter of dealing with the fact that they share the same queue. So you have to insert an if-else condition (e.g. if that event's next event is a WaitEvent at a server ID > numOfServers(self checks have ID > numOfServers) and your waitList.size() < qmax, you create a new WaitEvent at self check k + 1, else create a new LeaveEvent if waitList.size() >= qmax). Also, take note to be careful which event to add into pq.
> 
> did u extend the self scheck out from server? because when i did it the tostring method still returns servers tostring and not the overriden tostring

hi! did u manage to resolve this issue? i am having the same issue now...also, may i ask which implementation did u choose to use eventually?
