### ISSUE TITLE
Lab 8 Level 5 extra output

### ISSUE THREAD

**Issue by tungkei** [nus-cs2030/2122-s2#334]
# Summary
Hi, I managed to pass all other test cases for level 5 except the last one as it double prints the "You have taken sword" part. The issue is at the first lambda part when it does .tick(takeSword), the rest of the parts seem fine.

![image](https://user-images.githubusercontent.com/99954534/163660363-63041eae-cae2-4c85-8c96-71bfe72bd1ec.png)

**Comment by vvarshh** [comment]
you might want to check your tick method followed by the Room constructor you use in it.

**Comment by vvarshh** [comment]
Hello! You might want to check your tick method followed by the Room constructor you use in it to check what exactly you are returning
