### ISSUE TITLE
Project Level 5 issue with input

### ISSUE THREAD

**Issue by vveining** [nus-cs2030/2122-s2#335]
# Summary
When I run Main5.java, it takes in the wrong number of inputs.

## Screenshots (if any): 
Is this related to the extra/unnecessary service times?

CC sample run (test5_1):
![image](https://user-images.githubusercontent.com/94526059/163574163-4b34d8ab-0101-499e-9409-8ca0cb2a2089.png)

My sample run (test5_1): 
The program runs before the last line of input can even be typed (the last 1.0).
![image](https://user-images.githubusercontent.com/94526059/163574304-2b1124da-1443-4619-bdc9-6dfbc564bf39.png)

**Comment by elysiaojr** [comment]
hi yes i think bc not all the serviceTime inputs will be needed, as seen from this paragraph below

![image](https://user-images.githubusercontent.com/96276919/163579978-8d73ddcc-f91d-4177-bdf5-388890be9634.png)
