### ISSUE TITLE
PA2 Level 6 Reduce()

### ISSUE THREAD

**Issue by hongyaong** [nus-cs2030/2122-s2#337]
# Summary
Is it allowed to use recursion to solve level 6 reduce() ? 
 

## Description 
I have solved level6 reduce with a gcd method along with a helper method to solve reduce(), but the helper method uses recursion. It seems like codecrunch did not flag me for this, I'm not sure if it is allowable since level2 says no recursion. Thanks!

**Comment by wjahoward** [comment]
I think should be fine as long as there are no specific constraints mentioned i.e. level 2 explicitly mentions no recursion, maybe prof can clarify this? 😅

**Comment by jingyulim1** [comment]
I believe the way it has been is that codecrunch will be the judge, so if it's not flagged then you should be fine! (checkstyles are not graded for PAs anyway, unless Prof decides that codecrunch should be more stringent on that)

**Comment by adityajirafe** [comment]
The no recursion constraint seems to only apply for the add/sub... methods

**Comment by alwinngjw** [comment]
Hi, I think it should be okay. For reduce(), the question paper didn't explicitly state that recursion was not allowed.

Probably recursion is not allowed only for the earlier methods like add etc

Hope this helps

**Comment by jlee1007** [comment]
i guess the only way to check if its banned is via CC
