### ISSUE TITLE
optional methods?

### ISSUE THREAD

**Issue by herq-ules** [nus-cs2030/2122-s2#339]
# Summary
which optional methods are restricted?

## Description 
hello! i used isPresent(), isEmpty() and get() in my code and i'm not sure which one (or maybe all) led to the issue below. and other than these methods, which other optional methods are restricted? thank you :")

## Screenshots (if any): 
<img width="319" alt="Screenshot 2022-04-15 at 11 55 29 PM" src="https://user-images.githubusercontent.com/100022021/163592629-fa30760f-b719-4d6e-83ae-2d20c75553d5.png">

**Comment by Geraldworks** [comment]
I believe the restrictions prof applied to our labs apply to the project as well. 
So all the methods you mentioned are probably illegal
I made the same mistake .-.

**Comment by hongyaong** [comment]
if i'm not wrong, i think we aren't allow to use all of them, i personally used orElse for handling them.

**Comment by wjahoward** [comment]
Hi @herq-ules, for the PE2 the optional methods are all banned. 
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/25324531/163593069-82a35e4d-6c85-4bee-9933-b0d668494870.png">

**Comment by ca-leb** [comment]
hi, i believe only the 3 methods you mentioned (`isPresent()`, `isEmpty()` and `get()`) are restricted. you can try using `orElse()` or any other form of it to handle optionals.

**Comment by shotnothing** [comment]
orElseThrow() is a good one if you are confident you won't return empty.

**Comment by jamietan123** [comment]
Yup, you can try using orElseGet() instead

**Comment by Yang990121** [comment]
just use orElseThrow(), its the most straight forward

**Comment by alwinngjw** [comment]
Hi, iirc CodeCrunch bans isEmpty(), isPresent(), and get(). 
You can consider to implement orElse() instead

Hope this helps

**Comment by herq-ules** [comment]
thank you everybody!
