### ISSUE TITLE
Level 3 Hidden Test Case

### ISSUE THREAD

**Issue by micaellaa** [nus-cs2030/2122-s2#340]
# Summary
Got an odd test case and can't seem to figure out how the output could be NaN given similar test cases (ie one.sub(one)) were passed

## Ideas
Have so far tried swapping my constructors, add() methods (each separately) with the TA's ones but they all came back with the same error on code crunch. And the only methods I used inside sub() are the constructors, add(), and map(), almost identical to the TA's and in no way do I have some sort of ceiling for the input or anything :(

## Screenshots (if any): 
<img width="797" alt="Screenshot 2022-04-16 at 2 56 49 AM" src="https://user-images.githubusercontent.com/99943347/163622053-8a820fef-1728-4175-9ff7-8df304c6a756.png">

**Comment by ddeung0302** [comment]
I think it is due to detail. Probably something to do with the inner check for sub or making as optional?

**Comment by jamietan123** [comment]
I think you can try checking your add method? Just copy the TA one if need i think.

**Comment by morksen123** [comment]
Did u do a validity check in the constructor

**Comment by micaellaa** [comment]
> Did u do a validity check in the constructor

Yea but my constructors were very different from the TA's :( weighed my options & felt that adding one more constructor that's kinda tailored for sub()'s return statement was the least character-heavy change I could make! and it worked! Thanks for the q!

**Comment by micaellaa** [comment]
> I think it is due to detail. Probably something to do with the inner check for sub or making as optional?

I didn't really have a check in sub other than checking that `this` and `inputNum` were both valid. Not too sure but in the end, I rearranged the checks in the constructors and the static of()'s and changed the return statement for sub. somehow worked. Thanks for the suggestion!:)
