### ISSUE TITLE
Project level 8

### ISSUE THREAD

**Issue by E0857389** [nus-cs2030/2122-s2#344]
<img width="707" alt="Screen Shot 2022-04-16 at 2 05 39 PM" src="https://user-images.githubusercontent.com/98506014/163663896-1321ca18-4a72-4344-ba16-cd901ee15b85.png">

Has anyone faced this issue? not sure why it waits at 1 instead of being served by 2

**Comment by michael192002** [comment]
I've had times where the behavior of the servers was not expected; the way I debugged it was to the public the attributes and print them out (i.e. "server 1 is busy", "server 2 ....." ) to narrow down the scope of the logic error. Hope it helps!

**Comment by Yang990121** [comment]
Maybe u should add println statements to check what is your server 2 doing

**Comment by yjjjiajie** [comment]
yup for me, i printed out the shop to see what my servers were doing and they are extremely useful to debug. Then can just add a "output += shop" in Simulate8 to see

**Comment by ca-leb** [comment]
hi just to add on some tips for debugging, one way to see what your server is doing is to modify the server's `toString()` to include its status as well (i.e. resting/serving/idle). hope this helps!

**Comment by E0857389** [comment]
Thanks everyone!
