### ISSUE TITLE
Weird behavior case 8_1.in

### ISSUE THREAD

**Issue by shotnothing** [nus-cs2030/2122-s2#345]
Hi! Anyone know why 14 queues at 2 instead of 1 (see pic below)?  The state of the servers then is:
Server 1: [10, 13] (i.e. slot for one more, 10 is serving and 13 is waiting now)
Server 2: [12]

My understanding is they are allocated based on Server numbers as
> A customer that chooses the first queue available and joins at the tail

and this is corroborated by the previous lines which are consistent with this. 

However, in this case it seems to possibly be allocated by balancing queue length (inconsistent with previous lines) or completion time (requiring Lazy.get() to be called eagerly, thus not possible).

Am I missing something?

Thank you!

![image](https://user-images.githubusercontent.com/16388604/163664303-1ed6b37c-3158-4dd6-af7b-2540399d9124.png)

**Comment by shotnothing** [comment]
Okay I think I pulled restTime wrongly, oops

**Comment by elysiaojr** [comment]
hi @shotnothing im facing the same issue,, may i know how u fixed the problem?
