### ISSUE TITLE
non-static method error

### ISSUE THREAD

**Issue by pwnfish203** [nus-cs2030/2122-s2#347]
Hi guys, I keep obtaining this error _"error: non-static method isValid() cannot be referenced from a static context"_ when I try to compile my Num.java. This error also pops up when I use "this" in my code. Was wondering if my error lies within my constructors (it's similar to the TA's) or something else?  

Thank you!

**Comment by ReganKvioke** [comment]
Your succ() function should not be static. Hope this helps!

**Comment by pwnfish203** [comment]
@ReganKvioke ah yes that was the error :') thanks!!
