### ISSUE TITLE
this or super (PA2)

### ISSUE THREAD

**Issue by Lu-Yi-Fan** [nus-cs2030/2122-s2#348]
Hi i was watching the recitation for PA2. Can anyone explain why we use this(), can we use super() instead? Thank you

<img width="492" alt="Screenshot 2022-04-16 at 6 22 58 PM" src="https://user-images.githubusercontent.com/88626655/163671333-65a3039e-11ce-4ca0-9dec-54d117a4d3e9.png">

**Comment by jace-han** [comment]
Hi! I don't think there is a difference between the two. abstractnum.opt is an Optional<Integer>, hence it would feed into the first private method which would end up using the super(opt) method.

**Comment by jace-han** [comment]
Hi! I don't think there is a difference between the two. abstractnum.opt is an ```
Optional<Integer>```, hence it would feed into the first private method which would end up using the super(opt) method.

**Comment by t11-20** [comment]
Hi! I believe super(opt) is calling the superclass's constructor, for this(abstractNum.opt) --> You are calling the constructor in Num class, while passing in an optional.

Then, the constructor taking in the optional<Integer> will call the superclass's constructor to create Num
