### ISSUE TITLE
Failed Private Test Cases for Level 3 and Tips for Level 5! 

### ISSUE THREAD

**Issue by tanweiming00** [nus-cs2030/2122-s2#35]
# Summary

Hi, did anyone encounter this private test cases and how did yall resolve it? 

![image](https://user-images.githubusercontent.com/97489703/154792983-32a8a6fa-1c85-4543-bf56-873c49e8aba9.png)

**Comment by hongyaong** [comment]
Hi, i had this error and spent hours on this T_T, my error lies in the compareTo method. So basically what i did is compare booking fare "this" to other booking, using "this"'s request and "other"'s request and their best services, then return the comparison whether <0 or >0. If == 0, do the waiting time check between them and do the same.

**Comment by lyskevin** [comment]
Check the request that you're using to compute the fare :)

**Comment by wjahoward** [comment]
Adding on to @hongyaong, I guess you can look into this as well (which I used as reference): https://stackoverflow.com/questions/24601604/overriding-compareto-method-in-order-to-sort-objects-by-string-values

**Comment by wk1267** [comment]
Hi, I faced this error too, agree with @hongyaong that the error lies in compareTo method. The cheaper booking should have a lesser value than one with a higher fare

**Comment by tanweiming00** [comment]
> Hi, i had this error and spent hours on this T_T, my error lies in the compareTo method. So basically what i did is compare booking fare "this" to other booking, using "this"'s request and "other"'s request and their best services, then return the comparison whether <0 or >0. If == 0, do the waiting time check between them and do the same.

**Comment by tanweiming00** [comment]
Hi guys, thanks for the quick response. I only checked this.plate and other.plate, this.waitTime and other.waitTime, thisDist and other.Dist, thisPax and otherPax, thisTime and otherTime... 

I thought we are just returning whether the integer is 0 or less than 0? How does the comparing fare come into play?

**Comment by tanweiming00** [comment]
Hi guys, thanks for the quick response. I only checked this.plate and other.plate, this.waitTime and other.waitTime, thisDist and other.Dist, thisPax and otherPax, thisTime and otherTime... 

I thought we are just returning whether the integer is 0 or less than 0? How does the comparing fare come into play?

**Comment by wk1267** [comment]
comparing of fee is used, in part, to determine if the integer is <0, 0 or >0. For example, if A's fare < B's fare, then A.compareTo(B) < 0.

**Comment by tanweiming00** [comment]
Honestly fixed the issue but how does it affect the private test cases hmmm?

**Comment by michael192002** [comment]
Probably they might be calling compareTo() repeatedly to check whether it correct compares Booking's fares and waitTime, I had the same error too before I fixed it.

**Comment by tanweiming00** [comment]
Anyone has tips for Level 5? I am not sure whether my implementation for Level 3 is correct as Booking toString should only output the cheapest fare/service but for level 5 it wants to list out all the services and fares.

I managed to list out all the services and fares but it is in String output,so I am not able to make use of the Comparesto to compare and sort them.

If anyone managed to solve level 5, please drop some hints!! Thanks!

**Comment by inas0ng** [comment]
hi! Initially, my level 5 also outputted the cheapest fare/service only. I had to change Booking toString to output class variables more generally. You may find the use of another constructor method useful!

**Comment by tanweiming00** [comment]
> hi! Initially, my level 5 also outputted the cheapest fare/service only. I had to change Booking toString to output class variables more generally. You may find the use of another constructor method useful! (edit: since compareTo compares one Booking to another Booking, you can only make use of it to sort multiple Booking objects)

How do you make your Booking toString method more general? and can you tell me more of how you make use of another constructor in Booking method?

**Comment by hongyaong** [comment]
how do you made use of compareTo for this case? Did you loop through each booking and compare one by one? @inas0ng .

**Comment by inas0ng** [comment]
@tanweiming00 I used the second constructor to take in more variables like the service. These variables are then used in my toString method, making it more general (than calling some other method, in my previous incorrect implementation). 

@hongyaong Ya I manually looped through and compared... Tbh mayb there's an easier way (like calling some .sort() method ) but idk about that ;-;

**Comment by tanweiming00** [comment]
> @tanweiming00 I used the second constructor to take in more variables like the service. These variables are then used in my toString method, making it more general (than calling some other method, in my previous incorrect implementation).
> 
> @hongyaong Ya I manually looped through and compared... Tbh mayb there's an easier way (like calling some .sort() method ) but idk about that ;-;

@inas0ng I see, do you mean you have one toString method only?

**Comment by inas0ng** [comment]
Yup, I used one toString method

**Comment by tanweiming00** [comment]
> Yup, I used one toString method

nice thanks got that part already! You mentioned you looped through and compared but I guess you used the compares to method right?

**Comment by inas0ng** [comment]
nice! yes I used the compareTo method

**Comment by tanweiming00** [comment]
> nice! yes I used the compareTo method

I see, how do you make use of the integer value from the compareTo to sort? Is it by creating another ImList?

**Comment by inas0ng** [comment]
An ImList would help to store the Bookings as you sort them. compareTo tells you if a Booking is better than another based on the int value it returns (negative or positive), which tells you whether to change the order of the two Bookings in comparison.

**Comment by tanweiming00** [comment]
> An ImList would help to store the Bookings as you sort them. compareTo tells you if a Booking is better than another based on the int value it returns (negative or positive), which tells you whether to change the order of the two Bookings in comparison.

I can't seem to change the order using Set method. I use a nested loop with variables a, b for index and it's just simple swop.. Not sure how you implement it.

**Comment by tanweiming00** [comment]
Fixed the problem, while I tried to generalise my toString and constructor, I forgot to amend the compareTo code.

**Comment by Yang990121** [comment]
Try to think of ways to create a new Booking booking that have only 1 service for lvl 5
