### ISSUE TITLE
Level 6 test case issue

### ISSUE THREAD

**Issue by summerthia02** [nus-cs2030/2122-s2#353]
![photo_2022-04-17 00 53 07](https://user-images.githubusercontent.com/97536121/163684111-b477475e-84eb-4415-b33a-f7c1debf8d6e.jpeg)
My reduce function results in a NaN : 8 
Anyone knows why? thanks in adv! :)

**Comment by Lu-Yi-Fan** [comment]
For it to return Nan : 8, you might want to check your private constructor for Fraction. Does it filter and check for whether it is a valid fraction?

**Comment by junbin-tan** [comment]
Hi @summerthia02 you might want to look at your constructor in `Fraction`.

Maybe in the `Fraction of(Numer, Denom)`, you might wanna add a `if(Numer.isValid(), Denom.isValid())` checker and if it's not valid `return new Fraction(Optional.empty())` 

Cause right now, you are passing in a not valid Numerator after reduction.

Hope this helps!

**Comment by summerthia02** [comment]
> For it to return Nan : 8, you might want to check your private constructor for Fraction. Does it filter and check for whether it is a valid fraction when you call it?

**Comment by summerthia02** [comment]
right! I think I forgot to check if the fraction is valid after subtraction thanks!

**Comment by Lu-Yi-Fan** [comment]
@kaitlyngohh
