### ISSUE TITLE
Level 3 multiple customers being served at once

### ISSUE THREAD

**Issue by Seibell** [nus-cs2030/2122-s2#354]
Hi all, sorry for the long post, I've been trying to fix level3 for the past 2 days and I still cant get it to work.

# Summary
I am having this problem of parallel events occuring. For example:
![image](https://user-images.githubusercontent.com/66213395/163691560-ed01b2bb-1d5c-462e-a5b8-58313e34acfd.png)

## Description 
I have a problem where if a customer arrives at the same time as a server(with a previous customer in the queue) done serving, both customers get served. I feel that the problem is occurring because the server list in shop isn't being updated fast enough. (I currently update my shop after every event).

For my current implementation:
My Server class has **id, nextAvailableTime, and booleans for isAvailable and hasCustomersInQueue**

In My Shop class i have 2 methods:
1. to get the index of the first server who is available
2. to get the index of the first server that has no customers in queue

For my ArriveEvent's execute: 

```
        if (availIdx != -1) {

            double nextServerAvailableTime = super.getCustomer().getArrivalTime() + super.getCustomer().getServiceTime();

            servers = servers.set(availIdx, new Server(availIdx + 1, nextServerAvailableTime, false, super.getServer().hasCustomersInQueue()));
            
            ServeEvent e = new ServeEvent(servers.get(availIdx), super.getCustomer(), super.getEventTime());
            
            return Pair.<Optional<Event>, Shop>of(Optional.<Event>of(e), shop.update(servers));

        } else if (noWaitIdx != -1) {
            // wait event
            
            double nextServerAvailableTime = servers.get(noWaitIdx).getNextAvailableTime();

            servers = servers.set(noWaitIdx, new Server(noWaitIdx + 1, nextServerAvailableTime, false, true));
            
            WaitEvent e = new WaitEvent(servers.get(noWaitIdx), super.getCustomer(), super.getEventTime());
            
            return Pair.<Optional<Event>, Shop>of(Optional.<Event>of(e), shop.update(servers));

        } else {
            LeaveEvent leave = new LeaveEvent(super.getCustomer(), super.getEventTime());
            return Pair.<Optional<Event>, Shop>of(Optional.<Event>of(leave), shop);
        }
```

and my Done Event: 

```
        servers = servers.set(serverID - 1, new Server(serverID, super.getServer().getNextAvailableTime(), true, false));

        return Pair.<Optional<Event>, Shop>of(Optional.empty(), shop.update(servers));
    }
```

May the problem be in the way i implemented my run() in Simulate?
```
        while(!temp.isEmpty()) {

            print += temp.poll().first().toString();
            
            
            Pair<Optional<Event>, Shop> e = temp.poll().first().execute(tempShop);
            tempShop = e.second();

            if (!e.first().equals(Optional.empty())) {
                temp = temp.add(e.first().orElseThrow());    
            }
            

            temp = temp.poll().second();

            if (temp.isEmpty()) {
                print += "\n" + "-- End of Simulation --";
            } else {
                print += "\n";
            }
        }
```
If i were to update the shop inside the if statement instead, it would result in this issue (that other people have experienced before):

![image](https://user-images.githubusercontent.com/66213395/163692210-1dab95a8-fc08-4dc8-8b84-9293614fb76f.png)

Any help to fix my bugged code would be appreciated, I'm really desperate. Thank you!

**Comment by ryougi1702** [comment]
From what I can figure out by skimming through the code and what you have described, I don't think the problem lies in the Arrive and Done events.
I also had this problem a while back, and if I remember correctly the problem was in the Wait and Serve events. The Wait event would generate a Serve event right after the Done event. Since I did my updating in my Arrive event, the Serve event that comes right after the Done event did not update the Server status in my shop and the next Arrive event would trigger another Serve event.
Not sure if this is the issue you may be having, this is just what I have experienced.

**Comment by Seibell** [comment]
The error, in the end, was that I'm updating the shop for the next event rather than the current one, so by fixing that my code now works.
