### ISSUE TITLE
Project Level 3 Reversed Order for Done and Serve event

### ISSUE THREAD

**Issue by Luna2SY** [nus-cs2030/2122-s2#360]
Hello everyone. I have encountered the following problem. I would appreciate any advice.
![image](https://user-images.githubusercontent.com/88837643/163712083-43df6dda-5c9e-4d8f-a94b-278732a388d5.png)

**Comment by yjjjiajie** [comment]
Maybe In EventComparator, if the time is the same, you can compare by customerID, this will ensure that the lower ID will always be called first when the time is same

**Comment by Luna2SY** [comment]
Thank you!
