### ISSUE TITLE
lab9 infinitelist

### ISSUE THREAD

**Issue by pohja1999** [nus-cs2030/2122-s2#361]
# Summary

Description of the question / problem here.

## Description: InfiniteList

unable to load InfiniteListImpl and EmptyList on shell even though they compiled... no cyclic dependency... 

## Code Snippets

Attach code snippets (if any)

## Screenshots

<img width="296" alt="image" src="https://user-images.githubusercontent.com/98691869/163716360-da352418-b376-4838-8d4b-4c548f1a7adc.png">

<img width="567" alt="image" src="https://user-images.githubusercontent.com/98691869/163716407-cb0c554b-238a-4393-8b4f-9642c7ee5148.png">

Compiled but encountered problems when running in shell.. 

<img width="562" alt="image" src="https://user-images.githubusercontent.com/98691869/163716388-cb2514b3-a791-4914-8329-7765c37d968a.png">

Screenshots (if any)

**Comment by yongchein-o** [comment]
did you load in all other class that they are dependent on

**Comment by pohja1999** [comment]
umm hi, yes...

**Comment by pohja1999** [comment]
### fixed it by removing override for all my methods.... Apparently files are compilable on my TA's shell but not on mine.. It is what it is.. ###
