### ISSUE TITLE
Level 3 order of event execution

### ISSUE THREAD

**Issue by raynang** [nus-cs2030/2122-s2#365]
# Summary
For test case 3.1, the order of customer 1 done serving by server 1 and server 1 serving customer 2 is swapped and I'm not sure why this is happening. I was thinking that there could be a problem with EventComparator class or poll() method in PQ class but I'm not very sure.

## Description 
In EventComparator I just used Double.compare() to compare the event times of both events o1 and o2. Not sure if there's anything wrong with this because it passed all the previous test cases in previous levels.

## Screenshots (if any): 
new queue in the screenshot below is the updated queue after every poll(), executing the event with the highest priority and adding the next event into the queue if it is not Optional.empty().
first event is the output from queue.poll().first()

I'm not sure why in line 10 the order in the queue is correct (server 1 done serving customer 1 first then server 1 serves customer 2) but after poll() then the order is swapped in line 12
![Screenshot (1089)](https://user-images.githubusercontent.com/99885253/163727189-f20068a0-a1a3-4993-9288-adc55feff3ba.png)

![Screenshot (1088)](https://user-images.githubusercontent.com/99885253/163727308-24ff9187-20f8-4ee2-90a2-2f4197a14c25.png)

**Comment by wxlim26** [comment]
perhaps you could try comparing the customer ID if the event times are the same in the event comparator so the customer ID that is smaller will appear first.

**Comment by adityajirafe** [comment]
hi rayna, you can refer to #366, basically the customer who arrived first, with a smaller customerID, should be served first. you can try modifying your eventComparator.

**Comment by LohYangXian** [comment]
Hi! you can try comparing the customer IDs (smaller id number will come first), or you can give different priorities to different types of events ( what i did was i gave a number to each type of event as you can see that eg. Done event is printed first before Arrive > Serve > Wait > leave )

**Comment by summerthia02** [comment]
you may want to update your comparator class to take into consideration customer id as well if the event time is the same! I've met with the same error as well

**Comment by nanfang02** [comment]
Hiii when the event time is the same, the customer with the smaller ID number will be considered first! This can be done by adding one more if-else statement in event comparator class to check the event time and ID number.

**Comment by chorhanchean** [comment]
Hi, I had the same problem, realized that I didn't define my EventComparator fully, the smaller ID should come first if the eventTime is the same.

**Comment by whyyouj** [comment]
Hello, had the same problem too but realized a quick fix was to just add in a comparison for Customer ID apart from the event time
