### ISSUE TITLE
Level 3 - order wrong 

### ISSUE THREAD

**Issue by summerthia02** [nus-cs2030/2122-s2#366]
<img width="325" alt="Screenshot 2022-04-18 at 4 23 42 AM" src="https://user-images.githubusercontent.com/97536121/163730918-a5970e43-f4f7-4e5d-8399-5db840824ebf.png">

hii! my 1.500 2 serves by 1 comes before 1 done serving by 1, any idea why?

**Comment by Seibell** [comment]
check your event comparator

```
    @Override
    public int compare(Event e1, Event e2) {
        if (e1.getEventTime() < e2.getEventTime()) {
            return -1;
        } else if (e1.getEventTime() > e2.getEventTime()) {
            return 1;
        } else {
            return e1.getCustomer().getID() - e2.getCustomer().getID();
        }
    }
```

it should also check for customerID

**Comment by adityajirafe** [comment]
hi summer, in general the test cases are designed such that the customer who arrived first (smaller customer ID) will be served first, so you can try to modify your eventComparator to account for situations where the event timing for 2 separate events is the same

**Comment by ca-leb** [comment]
hi, another alternative to what @adityajirafe suggested is to assign a certain priority to the event and pass it into the comparator, i.e. a `Done` event would have a higher priority than a `Serve` event. that way, in your PQ, when two events have the same timing the `Done` event would be executed first.
