### ISSUE TITLE
Limited to using Vim only during Finals?

### ISSUE THREAD

**Issue by wayneonn** [nus-cs2030/2122-s2#369]
## Description 
Just wondering if we are limited to just Vim during Finals or if other code editors are allowed?

**Comment by yongchein-o** [comment]
Hi prof say we need to use vim for finals?

**Comment by jlee1007** [comment]
i believe it will still be vim

**Comment by alwinngjw** [comment]
Hi, likely we are only allowed to use vim. (like in the PAs)

**Comment by Ohnojiso** [comment]
Hi, would like to ask what will the format be like for the final paper?  I still have no idea of that...I remember hearing from my TA that we do not have jshell to help us during the finals so I am a bit confused...

**Comment by jiawei88** [comment]
i think prof has sent out an email regarding the format of the exam and how it will be, theres also a mock finals paper released :)

**Comment by wayneonn** [comment]
Thanks all!

**Comment by tristky** [comment]
I think we are allowed to use our own ide as long as we submit the final files to codecrunch!

**Comment by AaronTay21** [comment]
Hi i think it is only on vim
