### ISSUE TITLE
level 3 _ test case 3 

### ISSUE THREAD

**Issue by summerthia02** [nus-cs2030/2122-s2#371]
hi guys person 5 is leaving instead of being served by server 2  : <  anyone knows what's the issue?

<img width="367" alt="Screenshot 2022-04-18 at 1 26 18 PM" src="https://user-images.githubusercontent.com/97536121/163759266-ca9a753f-3427-421c-8a8f-9087e5216d22.png">

**Comment by Swagston20** [comment]
when 2 done serving, the executing have to make 2 available

**Comment by jamietan123** [comment]
i think you can try looking at your done event and make sure that after every done event the server is not occupied/ available for waiting
