### ISSUE TITLE
Project Level 8

### ISSUE THREAD

**Issue by Guanjung27** [nus-cs2030/2122-s2#372]
Any ideas on how to do Level 8?
i tried to make a new class that extends Server, but the issue is that i dont know how to implement the Shared Queue.

**Comment by Swagston20** [comment]
Can try implement the share queue in shop

**Comment by wxlim26** [comment]
I implemented the shared queue in the simulate 8 run method. So when the next event was a Wait Event for a SelfCheckout Counter, I would update the shared queue and update all Self Checkout Counters with that new Queue. When it is a Serve event, I would remove the customer from the shared queue and then update all Self Checkout Counters with the updated Queue. This ensures that all the self checkout counters will have the same queue at all times.

**Comment by Guanjung27** [comment]
> I implemented the shared queue in the simulate 8 run method. So when the next event was a Wait Event for a SelfCheckout Counter, I would update the shared queue and update all Self Checkout Counters with that new Queue. When the next Event is a Serve event, I would remove the customer from the shared queue and then update all Self Checkout Counters with the updated Queue. This ensures that all the self checkout counters will have the same queue at all times.

hi @wxlim26 , can i know how you checked if its a selfcheckout or a normal server?

**Comment by wxlim26** [comment]
Because I extended selfcheckout from server, so I created a method in the normal server called getType() that returns me "Human" . Then I override that method in selfcheckout to return me "SelfCheckout". So i check that to see which type of server it is. Not sure if its the best method but it worked for me.

**Comment by weihan10** [comment]
I implemented the shared queue with an ImList<Customer> in Simulate8. This allowed me to just create 1 if-else with roughly 8 lines to handle the wait and leave events (since they share the same queue with qmax ) .

**Comment by yongchein-o** [comment]
I have one server class but they have a field indicating which type they are. Then only human servers and the first selfcheckout server has a queue. The rest has no queue. But the rest of selfcheckout can server customer from that first selfcheckout then update the queue

**Comment by hongyaong** [comment]
i had the same implementation as @wxlim26, extending selfcheck from server and a method which returns boolean to check if it is a selfcheck or server class. So in simulation, i create only one queue that contains human servers followed by selfcheck.
