### ISSUE TITLE
Level 8 java.util.NoSuchElementException

### ISSUE THREAD

**Issue by herq-ules** [nus-cs2030/2122-s2#373]
# Summary
my code passes level 7 fine but i'm not sure why there is suddenly this error when i try to do level 8 (first test case, 8_1)

## Description 
has anyone gotten this error and do yall know where the error could be coming from

## Screenshots (if any): 
<img width="776" alt="Screenshot 2022-04-18 at 4 18 31 PM" src="https://user-images.githubusercontent.com/100022021/163779271-83979f02-a98c-4c7a-89fb-a71b7b84a8f8.png">

**Comment by Swagston20** [comment]
Met this type of error a lot. Try to trace the error step by step

**Comment by hongyaong** [comment]
I agree with @Swagston20, sometimes i would go back track and do up the codes step by step..

**Comment by wjahoward** [comment]
I guess there might be some logic errors with your code. Previously, I have also faced the same problem as you - pass level 7 but did not pass level 8 test case #1

**Comment by LohYangXian** [comment]
Hi! I had this problem too, i think it means that your code is calling the scanner function more than necessary(hence theres no more values to call from the input). you can try to debug from there

**Comment by herq-ules** [comment]
thank you!!

**Comment by sinlerr** [comment]
hello! im also facing this issue now! do you mind sharing where your error was? i did not use any scanner functions in my code so am i supposed to look at Main8.java??

**Comment by herq-ules** [comment]
hello! my issue was actually within my arrive event / queues (i can't rlly remember which), as a customer who was supposed to leave ended up waiting, hence an extra input was used up and resulted in not enough time inputs for the remaining events. fixing the logic in my code (once again arrive or queue) worked!
