### ISSUE TITLE
Project level 5

### ISSUE THREAD

**Issue by sheryew** [nus-cs2030/2122-s2#374]
9.105 9 arrives
9.105 9 waits at 1
9.160 10 arrives
9.160 10 waits at 1

Did anybody encounter anything like this when attempting level 5?

**Comment by Lu-Yi-Fan** [comment]
Same! I got something similar, i dont know what is the issue though
<img width="434" alt="Screenshot 2022-04-18 at 6 09 36 PM" src="https://user-images.githubusercontent.com/88626655/163793557-68264787-0658-414a-8fc8-40a663639a30.png">

**Comment by jamietan123** [comment]
I think its because your next available time for each server is not updated properly

**Comment by sheryew** [comment]
Thanks for your help! Turns out the problem is my implementation. The way I count the number of waiters in line is wrong.
