### ISSUE TITLE
Level 6

### ISSUE THREAD

**Issue by NWH21** [nus-cs2030/2122-s2#376]
Hey everyone, I have implemented the code for level 6 and the output timings are all correct. However, I cannot seem to be able to update the waiting times, as for example, for test case 6_2, my waiting time is 0.270 instead of the 0.3 and for test case 6_3, my waiting time is 0.814 instead of the 1.008. Could anyone advice as to how I could circumvent the problem? Thank you in advance!

**Comment by jamietan123** [comment]
I think you can try updating the waiting time during each serve event?

**Comment by rachtan27** [comment]
how is your waiting time computed?
i initially had this problem as well but then i changed my waiting time to the time the customer is served minus the customer's arrival time?

**Comment by yongchein-o** [comment]
My waiting time is time served - the arrival time

**Comment by LohYangXian** [comment]
Hi! My waiting time is time served - arrival times as well

**Comment by yjjjiajie** [comment]
Similarly,  I updated the statistics in my ServedEvent. And it is the event's time - customer's arrival time

**Comment by NWH21** [comment]
thanks guys, managed to solve it alr :)
