### ISSUE TITLE
Level 7 test case 7_3 Time Limit Exceeded

### ISSUE THREAD

**Issue by xywang08** [nus-cs2030/2122-s2#379]
# Summary
Does anyone know how to resolve this problem? I also seem to get it when I change the probabilities to 0.8 and above in test case 7_2 as well.

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
![Screenshot (42)](https://user-images.githubusercontent.com/81962290/163814448-96ee7d9e-76b0-4767-ac89-626c429f6f1e.png)

**Comment by mingshan2705** [comment]
Hello! I encountered the same issue previously, you can check out the replies at #175 to see if it helps

**Comment by xywang08** [comment]
> Hello! I encountered the same issue previously, you can check out the replies at #175 to see if it helps

Hi thanks for your reply. May I know if your issue was in Server as mentioned in #175 ? I am unsure as to why my code would work for 7_2 but not 7_3.

**Comment by mingshan2705** [comment]
I think for mine it had to do with the customer not getting served after the server has finished resting, resulting in the WaitEvent being forever left in the PQ, leading to an infinite loop which results in Time Limit Exceeded. I think you can try to trace out the events from the expected output to see where your code might have led to an infinite loop

**Comment by weihan10** [comment]
I encountered this once a few weeks back, when I tested the Main program on my own computer it just didn't print out the output  until I manually terminated it. It was an infinite loop in my case, so you need to check your logic flow! I think it'll be best to manually go through the logic flow of what events give what and you'll definitely find something

**Comment by xywang08** [comment]
@mingshan2705 @weihan10 Thanks for your help I managed to resolve it.
