### ISSUE TITLE
Unable to use comparator in codecrunch

### ISSUE THREAD

**Issue by eesung00** [nus-cs2030/2122-s2#38]
Hi does anyone faced this problem before on level5? My code is able to do sort and return the correct output on jshell (for test case) but when I upload the code to codecrunch, this error occurs:
![image](https://user-images.githubusercontent.com/90175879/154910118-fec14329-1911-48e2-951c-077e9c363e3e.png)

Here is my comparator class code and how i implement it on level5.jsh. 
![image](https://user-images.githubusercontent.com/90175879/154910587-4a38ed05-1ee9-4434-a39b-7a777f16001a.png)
![image](https://user-images.githubusercontent.com/90175879/154910708-8b0ab765-a15f-4e09-8aa3-5bbe57fa200b.png)

**Comment by JhChee18** [comment]
You need to import `java.util.Comparator` first before using

**Comment by eesung00** [comment]
> To add to what @JhChee18 has mentioned, the reason why the `Comparable` is used by `Booking.java`doesn't require import is that it uses `java.lang` package which is already included by default, just like your `Math` class which you don't need to explicitly import.
> 
> Then `Comparator` on the other hand uses package from `java.util`. Hence, you need to explicitly write the import statement as it is not included by default.
> 
> You can find out more about which packages they used from here. [Java Comparable API doc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Comparable.html) [Java Comparator API doc](https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html) [Java Math package, which is imported by default, same as Comparable](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html)

Thank you it works, so does jshell import java.util by default? I didn't face any error or warning while using the code in jshell before I import java.util. and it gives me a correct output.

**Comment by lukasleeyo** [comment]
> > To add to what @JhChee18 has mentioned, the reason why the `Comparable` is used by `Booking.java`doesn't require import is that it uses `java.lang` package which is already included by default, just like your `Math` class which you don't need to explicitly import.
> > Then `Comparator` on the other hand uses package from `java.util`. Hence, you need to explicitly write the import statement as it is not included by default.
> > You can find out more about which packages they used from here. [Java Comparable API doc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Comparable.html) [Java Comparator API doc](https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html) [Java Math package, which is imported by default, same as Comparable](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html)
> 
> Thank you it works, so does jshell help import java.util by default? As I didn't face any error or warning while using the code in jshell before I import java.util. and it gives me a correct output.

Yes! Jshell imports ```java.util``` by default. If you are interested in what are the default imports jshell have, simply go to the ```jshell>``` mode and type ```/imports```. It will show you the list of default libraries the Jshell come with.

**Comment by eesung00** [comment]
> > > To add to what @JhChee18 has mentioned, the reason why the `Comparable` is used by `Booking.java`doesn't require import is that it uses `java.lang` package which is already included by default, just like your `Math` class which you don't need to explicitly import.
> > > Then `Comparator` on the other hand uses package from `java.util`. Hence, you need to explicitly write the import statement as it is not included by default.
> > > You can find out more about which packages they used from here. [Java Comparable API doc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Comparable.html) [Java Comparator API doc](https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html) [Java Math package, which is imported by default, same as Comparable](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html)
> > 
> > 
> > Thank you it works, so does jshell help import java.util by default? As I didn't face any error or warning while using the code in jshell before I import java.util. and it gives me a correct output.
> 
> Yes! Jshell imports `java.util` by default. If you are interested in what are the default imports jshell have, simply go to the `jshell>` mode and type `/imports`. It will show you the list of default libraries the Jshell come with.

Alright, thank you!
