### ISSUE TITLE
Project Level 6 Implementation

### ISSUE THREAD

**Issue by Lu-Yi-Fan** [nus-cs2030/2122-s2#381]
Hi can someone clarify my doubts. For level 0-5 the server can only take in one customer to wait but then for level 6 is it trying to say this server can take in a number of customers to wait as a queue? I am confused about how to go about designing this level, wont level 6 be conflicting with level 1-5 is about where there can only be one person waiting per server.

**Comment by jlee1007** [comment]
this means that now the max queue length will no longer be 1 but will be whatever is read from the scanner

**Comment by ryougi1702** [comment]
You can modify the server to have a qMax attribute, and have the initial constructor of Server(int id) to initialise your qMax = 1.
This will enable the earlier Simulates which are not passing in the qMax parameter to still create servers that serve only a single customer.
Your later simulates will then use the more detailed constructors that specify the queue length.

**Comment by summerthia02** [comment]
it's just modifying from the levels 1-5 where the max was 1, but now max is the second input that is passed into the scanner! as what was mentioned, you can created an overloaded constructor in server that takes in an additional argument qMax and set qMax = 10 for instance, while that for 1-5 has qMax set to 1
