### ISSUE TITLE
Failing Level9_10 Test Case

### ISSUE THREAD

**Issue by wzs02** [nus-cs2030/2122-s2#383]
# Summary
Hi, does anyone know what this test case here is looking for or managed to fix this problem? Any general tips on debugging or level 9 edge cases would also be appreciated, thank you!

## Screenshots (if any): 
![Screenshot 2022-04-18 at 11 53 10 PM](https://user-images.githubusercontent.com/79785001/163835741-b68658ab-f481-46b5-a16d-332bdf2d4ccc.png)

**Comment by daitenshionyan** [comment]
Hello!!

For line 6, if a customer wants to wait at a self checkout counter, the output should be that the customer waits at the first self checkout (ie. the selfcheckout with the lowest ID).

As for line 8, I think it might be how you have defined the max queue length for a self checkout. Although the queue for self checkouts are shared, the collective maximum queue length for self check out is `qmax` and not `qmax * n` where n is the number of self checkouts. Meaning if qmax = 1 and n = 5, only 1 customer can be waiting for ANY of the 5 self checkout and not 5.

Here is what I think the magic numbers are for this test case. The result should be the same as in code crunch.
```
0 2 1 5 0.0
0.0000
0.0350
0.0460
0.1240
0.1260
0.3130
2.6450
2.7020
```

**Comment by wzs02** [comment]
@daitenshionyan thanks for the help, I managed to get it! :)
