### ISSUE TITLE
JavaDoc needed/graded?

### ISSUE THREAD

**Issue by shotnothing** [nus-cs2030/2122-s2#385]
Hi guys, anyone knows if JavaDocs are required and/or graded?

**Comment by wjahoward** [comment]
CodeCrunch did not flag me for not writing JavaDocs, so is not required.

**Comment by weihan10** [comment]
Nope definitely not required. Even the ImList provided has this issue, it's with public classes

**Comment by Swagston20** [comment]
Do not need to worry. Do not change or else your code cannot run

**Comment by shotnothing** [comment]
ok thanks!
