### ISSUE TITLE
Level 7 test case 7_3

### ISSUE THREAD

**Issue by kiacheng** [nus-cs2030/2122-s2#393]
# Summary
edit: 
after changing from lazy to supplier, i passed test cases 7_1 and 7_2 but my output for 7_3 failed the test case. im not sure where it started going wrong. did anyone face a similar issue?

I am somehow getting the wrong values from the restTimes supplier in level 7. i used the same concept in level 5 where i only called get once. For this level, i called get under run in Simulator7 to check if the server decides to rest (if the rest time from the supplier is more than zero) but so far i am only getting 0.0. 

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
![Screenshot (177)](https://user-images.githubusercontent.com/97575545/163955278-b221c68e-5654-46fa-a0bc-36e772f7bf83.png)

**Comment by Ohnojiso** [comment]
Hello I had one similar issue before. I got the wrong timimgs because I wrapped the restTime supplier in a Lazy. You can check my prev post here [](https://github.com/nus-cs2030/2122-s2/issues/254) to see if you are getting the same issue.

**Comment by wannyu** [comment]
Hi I think using the supplier directly would give non 0 values since Lazy calls for the supplier's get() once and stores it as an attribute. Therefore, when calling for Lazy's get(), it would repeatedly return the first value, which is 0.0
