### ISSUE TITLE
Incompatible types for creating Shop

### ISSUE THREAD

**Issue by FanKJ13** [nus-cs2030/2122-s2#395]
`
package cs2030.simulator;

import java.util.List;
import cs2030.util.ImList;

public class Shop {
    private final ImList<Server> servers;

    public Shop(ImList<Server> servers) {
        this.servers = servers;
    }

    @Override
    public String toString() {
        return servers.toString();
    }
}
`

`
new Shop(List.<Server>of(new Server(1), new Server(2)))
|  Error:
|  incompatible types: java.util.List<cs2030.simulator.Server> cannot be converted to cs2030.util.ImList<cs2030.simulator.Server>
|  new Shop(List.<Server>of(new Server(1), new Server(2)))
|           ^-------------------------------------------^
`

When I ran the above test case, it returned me an incompatible type error, may I check if anyone knows what's causing the error? I checked my ImList but everything seems fine.

**Comment by bryankwe** [comment]
Your Shop takes in an ImList of servers, but you input a List of servers

**Comment by WenJett** [comment]
Hello,

You just need to have another constructor which takes in List<Server> instead to create the Shop occordingly.

**Comment by alwinngjw** [comment]
Hi, yea just add another constructor that takes in a List

**Comment by kaitlyngoh** [comment]
u can create a constructor to take in List, then convert List to ImList

**Comment by FanKJ13** [comment]
Thanks all!!
