### ISSUE TITLE
Project Usage of Optional

### ISSUE THREAD

**Issue by sinlerr** [nus-cs2030/2122-s2#399]
# Summary
Hello! I'm attempting level 3 and i cant submit my code on code crunch because they said i used restricted Optional methods. Which Optional methods are disallowed? i have used get() and forEach() as far as i can remember.

if get() is not allowed, how did you guys "get" the events out of Optional<Event>? any help would be appreciated!!

## Screenshots (if any): 
<img width="1420" alt="Screenshot 2022-04-19 at 4 54 16 PM" src="https://user-images.githubusercontent.com/100189830/163967154-b026f5cb-e394-4dfc-afaf-2ed3cf498dc3.png">

**Comment by kkinmunn** [comment]
Those that are not allowed are `.get()` , `.isPresent()` , `.isEmpty()` iirc. You can use `.orElseThrow()` to get your Event out of Optional. Hope this helps!

**Comment by jlee1007** [comment]
yep similar to the most recent PA those methods are banned

**Comment by wjahoward** [comment]
Can refer to this as well #339

**Comment by shotnothing** [comment]
Take a look if your PQ.java is using these optional methods as well. I kept looking for illegal optional methods in my simulate classes as I forgot about util.

**Comment by sinlerr** [comment]
thanks all! I realised I was using Optional::get() in Simulate, and my 5 event classes! hope this can be of help to you guys
