### ISSUE TITLE
Level 7 Implementation

### ISSUE THREAD

**Issue by Lu-Yi-Fan** [nus-cs2030/2122-s2#411]
Hi can i ask, for level 7, for the case where the server is done serving and takes a break, can this server take in any customers into its own waiting queue?

**Comment by WenJett** [comment]
Hello,

Yes, customers can still queue at the server (who is at break) until the maxQueueLength as specified. After the Break ends then it will starts to Serve again.

**Comment by shotnothing** [comment]
Yup but take note, during the break the existing customer is not considered to have left yet. The queue only shortens after the resting time, not after the done event.

**Comment by YangHaoying** [comment]
Yes. Just to add on, for me queueing for a server that is resting has the lowest priority and should only come after there is no readily available server and no server with queue space that is not resting. Hope this helps!
