### ISSUE TITLE
Naming/Formatting Issue

### ISSUE THREAD

**Issue by xywang08** [nus-cs2030/2122-s2#412]
# Summary
Hi may I know if this refers to the naming of the file? Does that mean that all the events names and file names should be something like Arrive instead of ARRIVE?

## Screenshots (if any): 

![Screenshot (44)](https://user-images.githubusercontent.com/81962290/164044890-6c4788c2-596d-44f3-81fb-86c32268aa34.png)

**Comment by Bearypop** [comment]
Yup you are right, can't have all the letters in caps.

**Comment by shotnothing** [comment]
Refer to
https://www.comp.nus.edu.sg/~cs2030/style/

Full caps is typically reserved for `STUFF_LIKE_CONSTANTS` whereas classes should be `NamedLikeThis`.
This is also the convention outside of cs2030 for many programming languages.

**Comment by xywang08** [comment]
@Bearypop @shotnothing thanks for your help Ive managed to resolve it.
