### ISSUE TITLE
Level 8_4

### ISSUE THREAD

**Issue by NWH21** [nus-cs2030/2122-s2#413]
![image](https://user-images.githubusercontent.com/99738981/164058908-36f2361e-8142-4765-a286-1788521e3e4b.png)

Hey everyone! I have passed the test cases till 8_3 but however I am facing this issue of not being able to call the other self checkouts to serve the one in the waiting queue. My implementation is that I created a selfCheck class that extends Server and the difference will be in their types so as to know which event is which. Could anyone advice as to how I could circumvent the problem? Or should I change my implementation altogether.

**Comment by Ohnojiso** [comment]
If your current server is a `SelfCheck` You can try to filter out all the `SelfCheck` servers from the Shop's server list, and  find the one with the shortest "waiting time"(i.e. next available time). Then you use this `Self Check` server instead of whichever `Self Check` you have returned from the last event.

**Comment by YangHaoying** [comment]
Hii! The idea is that if a wait event for a customer at the self-check queue is executed, the customer should go for the self-check counter that can serve at the earliest timestamp, but not necessarily the first available one in the loop or the current one it’s queueing at. Filtering out all self-check servers and comparing all of their timestamps to find the earliest timestamp might be helpful to get the correct server. Hope this helps!

**Comment by StanleyMak** [comment]
What I did was to have a queue for all self checkouts, just that i will add a customer to all self checkout queues and similarly, make all self-checkouts serve the customer if its being served.

**Comment by NWH21** [comment]
Thanks guys, managed to clear level 8_4!!
