### ISSUE TITLE
Project Level 7 NoSuchElementExceptionError

### ISSUE THREAD

**Issue by sheryew** [nus-cs2030/2122-s2#418]
Hi, did anybody face such an error when doing level 7_2?

Would greatly appreciate it if anybody can assist me in this. Thanks!

![Screen Shot 2022-04-20 at 12 46 30 PM](https://user-images.githubusercontent.com/71963942/164152424-6d3e34af-76e2-4e93-b301-dbe6d9d5a042.png)

**Comment by vveining** [comment]
usually this error happens for me when get() is called on the supplier more times than required, so you might want to take a look at your logic to double check

**Comment by sheryew** [comment]
@vveining Thanks a lot for your hint! It managed to solve my problems. Turns out I was overcalling it in my simulate 7.
