### ISSUE TITLE
Level 5_4 NoSuchElementException

### ISSUE THREAD

**Issue by andrea-yxl** [nus-cs2030/2122-s2#421]
# Summary
Put a summary of the question
I am facing issues with test case 5_4. I have read the other posts which points out that this error occurs when you call Lazy.get() too many times. For me, I stored the serveTime as a Lazy in my Customer constructor and only call Lazy.get() in my Serve class where I need the service time to determine the eventTime of my Done event  and the next available time for my server to update the shop. I can't seem to find where the problem is. Anyone experienced a similar issue too and how did you manage to solve it? Any help will be greatly appreciated. Thank you!
## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
<img width="707" alt="Screenshot 2022-04-20 at 2 48 35 PM" src="https://user-images.githubusercontent.com/100149561/164168551-15b28a1b-e811-4891-b2f7-875525bf9c88.png">

**Comment by WenJett** [comment]
Hello,

Faced a similar issue previously, you may want to print out the serviceTime after calling it to see where you might have called unnecessarily and if the order is correct. Mine had some minor double calling in my Simulate file due to my careless mistake.

**Comment by duofeng0110** [comment]
I suspect your are calling the supplier.get() more than necessary. If you look at the input for level5_4.in, there are 17 doubles, because 10 arrive and only 7 are served. You should only call supplier.get() at Serve event to ensure that the customers who leave without being served do not take the service time input.

**Comment by andrea-yxl** [comment]
Thanks @WenJett @duofeng0110  for your suggestions! I tried checking for any double calling by printing out my events and it doesn't seem to be the mistake here and more of the order of my events are wrong. I have opened a new question #454 .
