### ISSUE TITLE
L7_3 ???@?!?!??!?!?!

### ISSUE THREAD

**Issue by jlee1007** [nus-cs2030/2122-s2#422]
Hi anyone faces a similar issue of failing hidden test case 7_3, i managed to passs all levels before and w/o the test cases i cant debug any thing????????
<img width="451" alt="Screenshot 2022-04-20 at 3 34 49 PM" src="https://user-images.githubusercontent.com/100404924/164175347-e4d48bd6-70e4-4fcd-abe0-14e0ddce24e6.png">

**Comment by wannyu** [comment]
Hi I think this [#406](https://github.com/nus-cs2030/2122-s2/issues/406#issue-1208403355) might help. Not sure if its the same as mine, for me my customer 3 was not served as I did not create a serve event for customers waiting at a server that is at rest. I added an additional if else condition I the run() method to solve it.
