### ISSUE TITLE
Level 7 supplier

### ISSUE THREAD

**Issue by nyiwei** [nus-cs2030/2122-s2#424]
# Summary
I am very confused on how to supplier rest times work… 

## Description 
In my simulate I tried printing restTimes.get() whenever it is a done event for test case 7_2, however the restTimes printed is as shown below and I think it is wrong. Did anyone experience the same issue or have any idea what I should do

Thank you in advance !!!

![9B4B876A-5341-426F-AB01-607D15605B9E](https://user-images.githubusercontent.com/99710151/164184828-330f9be2-67df-460a-a04c-9f6470b43431.jpeg)

**Comment by xywang08** [comment]
Hi did you call supplier get or did you store it in a lazy?

**Comment by nyiwei** [comment]
For me I just printed restTimes.get()

**Comment by xywang08** [comment]
so your rest times would be 0.0, 0.0, 0.0, 0.0, 0.0, 36.96, 2.16 and so on?

**Comment by xywang08** [comment]
Did you only call it once per done when updating server's next time and including the println?

**Comment by nyiwei** [comment]
I think I only called in println because I was not very sure how the supplier works so that was why I tried printing

**Comment by xywang08** [comment]
maybe you can try to update your server first and printing the next available time

**Comment by nyiwei** [comment]
If I have a constructor in Server which takes in the Supplier, is it possible to update my server in the Done Event or how else should I update my server?

**Comment by xywang08** [comment]
do you have a next available time variable in your server? You can update the server in done with the supplier

**Comment by nyiwei** [comment]
Ohh I see, then may I know ways I can update my server such that when customers arrive during the server rest time would not be served by that server?

**Comment by xywang08** [comment]
you can have a canserve in server that checks if the servers nextavail time is <= customers arrival time and is not currently serving

**Comment by nyiwei** [comment]
I tried the above mentioned method and I am still getting strange supplier numbers, I tried printing the restTime in the Done Event and in the simulate if it is a Done Event, it will print the NextAvailTime
<img width="235" alt="Screenshot 2022-04-20 at 7 24 25 PM" src="https://user-images.githubusercontent.com/99710151/164220351-e0e7af93-766d-4ca0-b3a2-362d8b16c287.png">

**Comment by nyiwei** [comment]
Okay!! I think I have managed to solve it!! Thank you so much for helping me!
