### ISSUE TITLE
Project Test Case 9_15

### ISSUE THREAD

**Issue by xuanweiweiwei** [nus-cs2030/2122-s2#425]
# Summary
Test Case 9_15: Customer leaves when not supposed to.

## Description 
This customer leaves instead of waiting for test case 9_15. Would appreciate some help with this issue because I am unsure how to correct it.

## Screenshots (if any): 
Insert Images here if necessary
<img width="488" alt="Screenshot 2022-04-20 at 6 04 21 PM" src="https://user-images.githubusercontent.com/83380959/164204303-69ff1f31-7cf5-423d-8c5f-e3a5d45973ef.png">

**Comment by shotnothing** [comment]
could try printing the queues of your severs and tracing how they are behaving wrongly
