### ISSUE TITLE
Project level 5 - How to test out level 5?

### ISSUE THREAD

**Issue by t11-20** [nus-cs2030/2122-s2#426]
![image](https://user-images.githubusercontent.com/101245687/164214524-6a4a7ee3-6eef-477b-9b0e-1c6e94dc0820.png)
Hello all! How do I actually test out level 5?

When I input cat level5_1.in
It returns "cat: test5_1.in: No such file or directory"
![image](https://user-images.githubusercontent.com/101245687/164214769-ccb72a97-e90a-4ab5-b114-ed8eb1ac1471.png)

**Comment by shotnothing** [comment]
type `ls` to see all the files and folders(directories) in your current directory

if test5_1.in is not there, create an empty file called `test5_1.in` and paste the test case

1 3
0.500
0.600
0.700
1.0
1.0
1.0

ensure Main5.class is in the directory too (should be if you made it till here)

then enter

cat level5_1.in | java Main5

to run

**Comment by duofeng0110** [comment]
Have you created the level5_1.in file in your folder?

**Comment by seanpbteo** [comment]
Hello, yep you can create a new test5_1.in file with all the inputs copy pasted from codecrunch and then run 
`java Main5 < test5_1.in`. Hope this helps!

**Comment by t11-20** [comment]
@shotnothing @duofeng0110 @seanpbteo thank you very much! :D
