### ISSUE TITLE
Level 3 Running Error 

### ISSUE THREAD

**Issue by vvarshh** [nus-cs2030/2122-s2#427]
Hello! I was trying run and test my level 3 using Main 3 but I got this error. Does anyone know the likely reason for it happening and where I can look to debug it. Thank you!

![Screenshot 2022-04-20 at 7 16 20 PM](https://user-images.githubusercontent.com/101083930/164219095-cc4d0276-5441-4691-b2a0-2d0373faab6f.png)

**Comment by aliciamichellew** [comment]
maybe try to not type in the "^D" into the input? use ctrl + d instead.

**Comment by vvarshh** [comment]
hello managed to run it thank you!
