### ISSUE TITLE
Main7 kept prompting for input 

### ISSUE THREAD

**Issue by lihuicham** [nus-cs2030/2122-s2#428]
Hi has anyone encountered this issue ?

When I try doing cat 7_1.in | java Main7 in my command prompt, it is asking me to input values even thought i already have a 7_1.in file in the same directory as Main7.java 

I can't even check whether my solution is correct or not, because I cant see the output.

**Comment by shotnothing** [comment]
its possible its not asking for input, but stuck in an infinite loop? try adding a System.out.println("hi"); in your run() loop, and it floods your console then thats the problem

**Comment by lihuicham** [comment]
Hi thank you for replying, yeap, i tried to add a System.out.println("hi") to my run method, nothing is being printed out, this means that... it is not the issue ? The console still prompts me for input

**Comment by shotnothing** [comment]
hmm weird, and if you ^D it terminates?
