### ISSUE TITLE
Project Level 8_4

### ISSUE THREAD

**Issue by sheryew** [nus-cs2030/2122-s2#429]
Did anybody encounter this? 
I managed to pass levels 8_1 to 8_3 but I am not too sure why my 8_4 didn't work. 
My 16 is supposed to leave but instead, it waits at self-check 2?

![Screen Shot 2022-04-20 at 19 25 28 PM](https://user-images.githubusercontent.com/71963942/164220551-a76d77f0-2d1e-49d6-8489-b0e3011b8220.png)

**Comment by weihan10** [comment]
Imo it's something to do with your shared queue implementation. I got the exact same error before due to my shared queue/Server. Maybe you can try to look from there? Trace the events and print them out if it helps.

**Comment by Swagston20** [comment]
check the share queue u used. Most prob is in your arrive event

**Comment by sheryew** [comment]
@Swagston20 @weihan10! Thanks for your help! I managed to solve it.
