### ISSUE TITLE
lvl6: recycled loader class cannot access cruise 

### ISSUE THREAD

**Issue by jwjiawei** [nus-cs2030/2122-s2#43]
# Summary

I created a RecycledLoader class which has a method cruise.getServiceCompletionTime(), but cannot access it since the cruise has private access in Loader. I tried changing it to protected, which works, but is not accepted on codecrunch. Does anyone know how to solve this? Thank you!

**Comment by matthewchoo** [comment]
hi, may I check if you implemented RecycledLoader as a class of its own or a class inherited from Loader?

**Comment by shotnothing** [comment]
Don't use protected! This is to strictly maintain abstraction barrier I think. Make use of `super.someMethod()` to call the parent class method, there should be enough methods to complete the task. Also remember to add the `@Override` annotations.

In your case, super.getNextAvailableTime() should return cruise.getServiceCompletionTime().

**Comment by jwjiawei** [comment]
I implemented RecycledLoader as a subclass of Loader @matthewchoo

**Comment by calvinseptyanto** [comment]
If you want to access serviceCompletionTime property, you need to construct RecycledLoader first by using super(...) inherited from Loader class. That way you can have the access to the related property!

**Comment by undeser** [comment]
To maintain abstraction, they need to be private.

I suggest creating getting functions.

In Loader, there should be a `getCruise()` function.

Such that in your RecycledLoader subclass, you can `super.getCruise().getServiceCompletionTime()`
