### ISSUE TITLE
Project Level 3: Prioritising waiting events over arriving events

### ISSUE THREAD

**Issue by lvxhnat** [nus-cs2030/2122-s2#431]
# Summary
<img width="212" alt="Screenshot 2022-04-20 at 7 59 53 PM" src="https://user-images.githubusercontent.com/58301316/164225734-8072fbe7-1244-4f0f-a7ba-2a6c421f4c65.png">

This is what I am currently getting. I am sorting the events by arrival time using a comparator that compares event times. Am I supposed to add in an additional condition also where if a instanceof Wait ? -1 ? 1 (Something like that)? Is that allowed? If not any suggestions on how to prioritise the events?

**Comment by shotnothing** [comment]
they are not sorted by event type whatsoever, they are sorted by event times and customer arrival times

**Comment by aliciamichellew** [comment]
Try sorting by event times. If the two events have the same event times, sort by its customer id.

**Comment by lvxhnat** [comment]
Got it, thanks all!
