### ISSUE TITLE
Level 7_2 Rest Time

### ISSUE THREAD

**Issue by Lu-Yi-Fan** [nus-cs2030/2122-s2#433]
![Screenshot 2022-04-20 at 8 06 17 PM](https://user-images.githubusercontent.com/88626655/164226823-d4bce371-17de-4044-95e7-bc883bb18b1d.png)

Hi i seem to be running into an infinite loop when i run test case 7_2, can I check whether these 3 timings are the rest timings for the servers in test case 7_2

**Comment by shotnothing** [comment]
0.0
3.1387621604911167
0.8478039781484203
0.0
0.8489675729370934
0.0
0.0
3.863139226870278
0.0
0.0

**Comment by Lu-Yi-Fan** [comment]
Thank you! This will be useful for my debugging!
