### ISSUE TITLE
Level 8 Server serving multiple customers at once 

### ISSUE THREAD

**Issue by kiacheng** [nus-cs2030/2122-s2#437]
# Summary
hii so my code makes the server serve two customers at once and i cant figure out why. My implementation does not include an additional event class. My logic is that when looping the pq, if the event is a wait event, i add a serve event in the queue at the time when the server is done resting. However, this seems to make multiple wait events produce a serve event at the same time. I have tried keeping a list of server ids that have already had the first wait event add a new serve event. But this did not prevent the next wait event of the same server to add a serve event of the same time. Would appreciate any suggestions to fix my code/ a better approach to level 7!!

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
![Screenshot (178)](https://user-images.githubusercontent.com/97575545/164254476-ee6e5fed-381a-4033-937a-93eff1c4f5e6.png)

**Comment by herq-ules** [comment]
hello! i faced the same issue and i'm not sure if this is the best way to do it but what i did was to add a while loop in my simulate7's run that checks for two (or more jic) serve events that occur at the same time and are served by the same server and then replaces the second serve event with a new serve event that starts at the time when the first serve event is done.

**Comment by celine-chung** [comment]
hi! not sure if i understood your issue correctly but i think what's happening is that you're scheduling serve events for all the customers in the server's queue when really only one person is going to be served in the next available time? which might be why there are multiple customers being served at the same time! the easy fix would be to simply check if the person is at the head of the queue before returning a serve event. if the person is not at the head of the queue, a good way would probably be to just create another class. but i know that some others did not create a separate class for this so if you don't want to, i'm sure there's a way if anyone else would like to offer some insight haha

**Comment by kiacheng** [comment]
@celine-chung @summerthia02 @herq-ules 
hii thanks all for the replies!! i realised i forgot to check if the customer is the first in the waiting queue like what you all said and i managed to fix this bug
