### ISSUE TITLE
lvl6 testCase 6_2

### ISSUE THREAD

**Issue by hhujiale** [nus-cs2030/2122-s2#440]
Hiii anyone facing the same issue can help me :(
I created Pending class that returns either a Pending event or Serve event
Arrive -> Wait -> Pending -> (either Pending or Serve)

If returns a Serve event, the server needs to be available and customer is the first one in waitingQueue; otherwise returns a Pending event with the update time.

## Screenshots (if any): 
![Screen Shot 2022-04-20 at 23 24 05](https://user-images.githubusercontent.com/95912577/164267787-04a6d088-ae84-4ade-b2d6-848362554190.png)

**Comment by WenJett** [comment]
Hello,

Your Pending event seems to work as intended. You may want to look at if you are limiting the size of the queue properly cause the input for maxQueueLength is 2 but customer 10 is going to Server 2 instead of Server 1 (which only has customer 9 waiting at that moment).

**Comment by summerthia02** [comment]
10 is waiting at 2 instead of 1, which may mean that your Server 1 has reached its max queue even though it hasn't reached - maybe can do a check of the current queue number and the maxQueue - for me I checked if the server hasSpace() by checking if current number in queue has reached the maxQueue!
