### ISSUE TITLE
main2 unresolved compilation problems when running

### ISSUE THREAD

**Issue by demitan02** [nus-cs2030/2122-s2#442]
## Description 
Hello! When I try to test using Main2.java, this error pops out although when I compile all my files, they compile without any error. Does anyone know what is up with this? Thank you! 

## Screenshots (if any): 
<img width="625" alt="image" src="https://user-images.githubusercontent.com/97874900/164282735-5d065b2d-c9f4-4246-9216-5fc86d9b36c6.png">

**Comment by summerthia02** [comment]
try java Main2 ?

**Comment by vvarshh** [comment]
do make sure you have package cs2030.simulator in your classes

**Comment by celine-chung** [comment]
sis did you package all your classes correctly? i forgot to add the "package cs2030.simulator;" line at the start of some of my files initially which led to some errors.. it says that the expected package is "" so you might have forgotten to include a package name somewhere

**Comment by demitan02** [comment]
i did put all the package statements in though but it still gives me the same error. i tried running on codecrunch it passed all the way until testcase 3_1 hopefully its okay?

**Comment by Lu-Yi-Fan** [comment]
Try javac -d . *.java  to compile all your files, if you are able to compile all your files, you would be able to test main2 if not you will get errors. As mentioned by the rest, do make sure to package your files correctly

**Comment by Lu-Yi-Fan** [comment]
there are two packages one called cs2030.util and another is called cs2030.package

**Comment by Zarilex09** [comment]
when you use PQ did you import cs2030.util.PQ in that file

**Comment by shotnothing** [comment]
.
├── Main2.java
├── Main3.java
├── Main4.java
├── Main5.java
├── Main6.java
├── Main7.java
├── Main8.java
├── cs2030
│   ├── simulator
│   │   ├── Arrive.java
│   │   ├── Customer.java
│   │   ├── Done.java
│   │   ├── Event.java
│   │   ├── EventComparator.java
│   │   ├── EventStub.java
│   │   ├── Leave.java
│   │   ├── Rest.java
│   │   ├── Serve.java
│   │   ├── Server.java
│   │   ├── Shop.java
│   │   ├── Simulate2.java
│   │   ├── Simulate3.java
│   │   ├── Simulate4.java
│   │   ├── Simulate5.java
│   │   ├── Simulate6.java
│   │   ├── Simulate7.java
│   │   ├── Simulate8.java
│   │   ├── Statistics.java
│   │   ├── Typee.java
│   │   └── Wait.java
│   └── util
│       ├── ImList.java
│       ├── Lazy.java
│       ├── PQ.java
│       └── Pair.java
├── test5_1.in
├── test5_2.in
├── test5_3.in
├── test5_4.in
├── test6_1.in
├── test6_2.in
├── test6_3.in
├── test7_1.in
├── test7_2.in
├── test7_3.in
├── test8_1.in
├── test8_2.in
├── test8_3.in
└── test8_4.in

**Comment by shotnothing** [comment]
.
├── Main2.java
├── Main3.java
├── Main4.java
├── Main5.java
├── Main6.java
├── Main7.java
├── Main8.java
├── cs2030
│   ├── simulator
│   │   ├── Arrive.java
│   │   ├── Customer.java
│   │   ├── Done.java
│   │   ├── Event.java
│   │   ├── EventComparator.java
│   │   ├── EventStub.java
│   │   ├── Leave.java
│   │   ├── Serve.java
│   │   ├── Server.java
│   │   ├── Shop.java
│   │   ├── Simulate2.java
│   │   ├── Simulate3.java
│   │   ├── Simulate4.java
│   │   ├── Simulate5.java
│   │   ├── Simulate6.java
│   │   ├── Simulate7.java
│   │   ├── Simulate8.java
│   │   ├── Statistics.java
│   │   └── Wait.java
│   └── util
│       ├── ImList.java
│       ├── Lazy.java
│       ├── PQ.java
│       └── Pair.java
├── test5_1.in
├── test5_2.in
├── test5_3.in
├── test5_4.in
├── test6_1.in
├── test6_2.in
├── test6_3.in
├── test7_1.in
├── test7_2.in
├── test7_3.in
├── test8_1.in
├── test8_2.in
├── test8_3.in
└── test8_4.in

**Comment by demitan02** [comment]
i managed to compile all without any errors, and my statements are correct >< not sure why it isn't running properly when I test with main 2

**Comment by shotnothing** [comment]
whats your directory structure like? could you post the output of 

`du -a .`

from the same place as where you run your main

**Comment by demitan02** [comment]
mine looks like that 

<img width="413" alt="image" src="https://user-images.githubusercontent.com/97874900/164403335-12997322-0d3e-4323-8be0-3f2e26ad6f00.png">

**Comment by shotnothing** [comment]
hmm you seem to have multiple copies of classes like Simulate2, EventStub PQ etc in the same directory/folder as your main. you should structure it like this:

```
.
├── Main2.java
├── Main3.java
└── cs2030
    ├── simulator
    │   ├── Arrive.java
    │   ├── Customer.java
    │   ├── Done.java
    │   ├── Event.java
    │   ├── EventComparator.java
    │   ├── EventStub.java
    │   ├── Leave.java
    │   ├── Serve.java
    │   ├── Server.java
    │   ├── Shop.java
    │   ├── Simulate2.java
    │   ├── Simulate3.java
    │   └── Wait.java
    └── util
        ├── ImList.java
        ├── Lazy.java
        ├── PQ.java
        └── Pair.java
```

The issue i suspect is that ur java is confused and reads the Simulate2 from ./ than from ./cs2030/simulate/

**Comment by demitan02** [comment]
thank you! should i move the .java files to within the folder? because right now the .class files are in the folder when I compile them using javac -d . *.java

**Comment by shotnothing** [comment]
just delete all the class files for now, you can compile later. yup, move everything into their respective folders

**Comment by demitan02** [comment]
i moved everything into the respective folders but now when I try to run main2, it gives me a whole lot of other errors >< 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/97874900/164408664-be9470cc-0c3a-4b5b-9c8a-4e8a5f789d1a.png">

**Comment by shotnothing** [comment]
can I check if your main2 is outside the cs2030 folder?

**Comment by shotnothing** [comment]
![image](https://user-images.githubusercontent.com/16388604/164410148-933355be-86c4-4527-bac6-695cb871fecc.png)

**Comment by demitan02** [comment]
yeap it is outside the cs2030 folder

**Comment by shotnothing** [comment]
hmm very weird, you could try to run these things on a terminal just in case its something to do with vscode's buildpath config or smth, im not very familiar with vscode 

the folder structure i sent should be correct, its just for some reason it seems to be doing everything within ./cs2030/

**Comment by daitenshionyan** [comment]
Hello you can try doing this so that VS Code recognises this project folder as a folder. (This is assuming you are using VS code with the Java extensions which I think you are using)

1. `ctrl` + `shift` + `P`
2. Search for "create java project"
3. Select `Java: Create Java Project...`
4. Select `No build tools`
5. Find a place where you want the project folder to be
6. Name your project folder (anything you want)
7. A new window should open with the project created.
8. Copy and save everything over into the `src` folder that was automatically created. The structure in the `src` folder should be the same as your original project folder that you were working on.

To test your code with the test cases, open the terminal and cd to bin first using `cd bin` and everything else should be as per normal.
eg:
![image](https://user-images.githubusercontent.com/100074448/164422995-955482b6-9f32-4e6b-b841-a6f5737a26d8.png)
LHS column shows structure and Terminal shows testing.

Also note if you are using Windows `^D` might not work, instead use `^Z`

Everything that you save (`ctrl` + `S`) will automatically be compiled into the bin folder. So for the .in files that you might create later on, create and save then in the `src` folder. They will automatically be outputted to the `bin` folder. Also you will not need to use javac anymore as your files are automatically compiled when you save so long as they are compilable (no red lines). So instead of "always compie your work", it is "always save your work".

**Comment by demitan02** [comment]
thank you so much! its working now :")
