### ISSUE TITLE
Cyclic Dependency

### ISSUE THREAD

**Issue by Lu-Yi-Fan** [nus-cs2030/2122-s2#443]
Hi did anyone face this issue for cs2030 project? 
AHHAAH idek where to start send helps 

![Screenshot 2022-04-21 at 1 57 29 AM](https://user-images.githubusercontent.com/88626655/164293398-912fc859-e1ad-4150-815c-0df9bbd2bdab.png)

**Comment by summerthia02** [comment]
I have not faced this error before but it seems like you have a never ending loop bc your done event calls your serve event? for mine I implemented in a way such that done calls optional.empty() and thus breaks the cycle I guess?

**Comment by Geraldworks** [comment]
Your Done event Calls Serve event, Which Calls Serve event again, hence the cyclic dependency 
You could take a look at #153

**Comment by Lu-Yi-Fan** [comment]
@summerthia02 @Geraldworks  Thanks for spotting my cyclic dependency! Solved thanks
