### ISSUE TITLE
level 8_2 - self check 3 and 3 in output

### ISSUE THREAD

**Issue by summerthia02** [nus-cs2030/2122-s2#446]
hii im not sure why there is both 3 and self check 3 in my output even though 3 is a self checkout server. anyone knows why?
<img width="360" alt="Screenshot 2022-04-21 at 2 26 11 AM" src="https://user-images.githubusercontent.com/97536121/164297768-db56d5d0-2698-43e7-8a90-905ff0b60639.png">
]

**Comment by Geraldworks** [comment]
Maybe its a type casting issue
When you retrieve the SelfCheckout 3 was it a Server type or SelfCheckout type

**Comment by summerthia02** [comment]
self check out 3 is a selfcheck type while 3 is a server type im not sure why my shop suddenly adds a 3 inside, even though I added self-checkout 3 from the start only

**Comment by Geraldworks** [comment]
I encountered the same issue and it was because the return type in some method returned a server type and not the selfcheckout type 
How did you implement your selfcheckouts?

**Comment by summerthia02** [comment]
hmm do I have to have a shop constructor that takes in the number of selfchckout as well?

**Comment by Geraldworks** [comment]
what would change if you included this new attribute?

**Comment by summerthia02** [comment]
@Geraldworks this is my output for the various events - from sc -> 3 it suddenly changes!
<img width="253" alt="Screenshot 2022-04-21 at 2 43 46 AM" src="https://user-images.githubusercontent.com/97536121/164300792-7762d840-0b53-40f8-92d7-fb89a44d24be.png">

**Comment by Geraldworks** [comment]
I can't really tell what's happening cause our implementations are likely different, though I can think of some reasons

1. Did you call a new Constructor which altered the desired attributes?
2. Did you update your Shop of servers to generalise to Server type only?

**Comment by summerthia02** [comment]
ohh how do I update such that both server types can be included? is sit extends super kinda thing
