### ISSUE TITLE
Level 3

### ISSUE THREAD

**Issue by gypsyxx** [nus-cs2030/2122-s2#449]
Not sure why my timings for serve and done event are wrong. 
<img width="152" alt="image" src="https://user-images.githubusercontent.com/97491909/164360418-9e96f414-d416-4655-b2e9-8fe0dbef7c0a.png">

**Comment by gwynethguo** [comment]
I think you can check whether your server's end time (to know when to serve the next customer) is updated correctly.

**Comment by jamietan123** [comment]
I think you need to check that there are no customers currently being served before servign the next one

**Comment by terrrence** [comment]
you can check whether the next available time of your server is being updated correctly at each event. the state of the shop has to be updated as you update your servers

**Comment by winnnnnnnnnnn** [comment]
2 is being served while 1 is still being served so I think you need to make sure 1 is done being served before Serve event for 2 is invoked

**Comment by Lu-Yi-Fan** [comment]
Server 1 is serving customer 2 before it is done serving customer 1. Maybe you would want to check the flow from a wait to a serve event, the timing that you input when you create a serve event

**Comment by eugenetaan** [comment]
faced this problem initially too, like what the others said u need to check the flow from wait to serve, what I did personally was to create 2 different serve methods to differentiate the flow where one is serving a new customer and one is serving the customer in the queue
