### ISSUE TITLE
How to factor in rest time at level 7 ?

### ISSUE THREAD

**Issue by johnnythesnake12** [nus-cs2030/2122-s2#452]
Hi guys,

Could someone please explain how to factor in rest time in level 7? 

With much love,
johnnythesnake12 sssss

**Comment by Guanjung27** [comment]
i would recommend that you add the rest time to the next available timing, however it may depend on your implementation

**Comment by kkinmunn** [comment]
You can consider checking if your server is taking a rest in your Done event by getting it from the `Supplier`, then return a new event back to your PQ with the current event time + server resting time. Hope this helps!

**Comment by feederalert** [comment]
I opted to check if the server is going to rest in the Done event. If the rest time obtained from the supplier isn't 0, then it goes to a ServerRest event, else the server goes to serve the next customer (if any).

**Comment by duofeng0110** [comment]
I think you can try to store a supplier for rest time in each customer, and only invoke it when a server is done serving that customer, in the Done event.

**Comment by celine-chung** [comment]
i believe it should be somewhat similar to the way you update the shop for your serve class! the idea is that the server will continue to be busy just like it was if it was serving a customer until it's next available time which is simply the current time (i.e. time of done event) + the rest time which you would get from the supplier!
