### ISSUE TITLE
Project Level 7 Queries - Don't understand Main7 and Level 7

### ISSUE THREAD

**Issue by sinlerr** [nus-cs2030/2122-s2#453]
# Summary
Hello! I just started on Level 7 and I have some questions about Main7.java and Level 7 itself!

## Description 
**Main7.java queries**
Does anyone know what
`private static final Random rngRest = new Random(3);` and 
`private static final Random rngRestPeriod = new Random(4);` mean? according to the java api (attached pic below) there are only 2 constructors for Random? so does it mean that 3 and 5 are long seed types?

in addition, are we supposed to understand the genRestPeriod() method?

**Level 7 query**
and my last question: if our outputs are randomised, how does code crunch know if our implementation is correct or not?

any help will be appreciated! :))

## Screenshots (if any): 

![Screenshot 2022-04-21 at 2 42 29 PM](https://user-images.githubusercontent.com/100189830/164390427-db9a2dff-3f2c-4e31-9a4e-8aeda945f92c.png)

**Comment by Geraldworks** [comment]
You don't have to bother about the random class. The seed input is to generate a sequence of fixed random inputs so that your code remains predictable and testable. 

The only thing you need is the Supplier<Double> restTimes variable 

This variable will generate the restTimes of your servers

**Comment by feederalert** [comment]
Since the seed is constant, the 'random' number generated using the seed as argument is deterministic and will be the same at each run. Do not worry about it as the server rest times will be the same each time you run it.

**Comment by sinlerr** [comment]
ohh i see, thanks all!
