### ISSUE TITLE
Level 5 last test case wrong order

### ISSUE THREAD

**Issue by andrea-yxl** [nus-cs2030/2122-s2#454]
# Summary
Previously, I faced a NoSuchElementException error for my last test case. I printed out the events, serveTimes and arrivalTimes to check and it does not seem like I have called it unnecessarily. What I found was that my "1 done serving by 1" comes before "2 arrives" which messes up the order of the events at the back. For my comparator, when the event time is tied, the customer with a smaller ID will be done first but this should not be the case of tied event times since the arrival time of 2 is earlier than the done time of 1. I don't remember rounding off any of the values except at the toString method and I don't think the values are rounded off when stored. I really can't seem to figure how to resolve this. Anyone encountered this as well? Any help will be greatly appreciated! 
## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
<img width="480" alt="Screenshot 2022-04-21 at 2 22 31 PM" src="https://user-images.githubusercontent.com/100149561/164392156-52ac6c4e-ba5d-4ba3-81e6-b60594d758b3.png">

**Comment by shotnothing** [comment]
You ran out of customer service times to call, most likely you are producing more serve events than intended

**Comment by andrea-yxl** [comment]
@shotnothing thanks for your help!
