### ISSUE TITLE
Jshell testing error

### ISSUE THREAD

**Issue by mauvedelune** [nus-cs2030/2122-s2#455]
Hi everyone! I am unable to test level 1's test cases despite creating Event.java and EventStub.java. (As shown in the screenshots below). Does anyone happen to know why? Any help is appreciated. Thank you!
![595166EE-86F6-440B-988B-2B485237627D](https://user-images.githubusercontent.com/86298464/164403312-3f21740f-7b93-4925-88db-2684ffc238bc.jpeg) 
![3C277588-9FDE-4089-97B8-879465BF5703](https://user-images.githubusercontent.com/86298464/164403986-f03e6f89-35c3-4c6b-aced-4742a1d98d56.jpeg)

**Comment by ryuniqlo** [comment]
hi i think you need to make sure your EventStub extends/implements your Event

**Comment by feederalert** [comment]
I'm not too sure but maybe if you're testing in jshell you might want to comment out the package line?

**Comment by mauvedelune** [comment]
> 
![8DBC1977-EB6D-405C-A7F5-B2C54A3282C1_4_5005_c](https://user-images.githubusercontent.com/86298464/164409394-73b007bd-53e6-41ef-a99c-3ee8c21fb3f9.jpeg)

Hi! I have implemented it as shown here, however it still gave me the same error

**Comment by mauvedelune** [comment]
> I'm not too sure but maybe if you're testing in jshell you might want to comment out the package line?

I have tried it, it still gave the same error :(

**Comment by bryankwe** [comment]
Did u compile using `javac -d . *.java`?

After that just `jshell` and `import cs2030.util.*` and `import cs2030.simulator.*`

**Comment by celine-chung** [comment]
hm that's odd... i was faced with the error when i was trying to test out my code before submission and fixed it by ensuring all the relevant classes were public and compiling all my code before testing! if you've already tested using the Main programs and it works, it should just be an issue of the access modifiers
