### ISSUE TITLE
ImList syntax

### ISSUE THREAD

**Issue by mauvedelune** [nus-cs2030/2122-s2#457]
Hi everyone! I was testing out my Simulate2 class and I had this error while compiling. May I know what they meant by illegal start type and how can I fix it? Any help will be appreciated. Thank you!
![57E217F2-434F-4C5E-A15D-70C20D64A1C1_4_5005_c](https://user-images.githubusercontent.com/86298464/164410767-72068f88-bc9d-4803-b49c-814e915c5430.jpeg)

**Comment by Geraldworks** [comment]
Shouldn't it be 
`ImList.<Integer>of()` 
The syntax order seems wrong

**Comment by gwynethguo** [comment]
Should be ImList.<Integer>of()

**Comment by rachtan27** [comment]
ImList.<Integer>of()

always put the "." before the <type>

**Comment by mauvedelune** [comment]
ahh I see, it works now, thank you both 👍

**Comment by tristky** [comment]
i also had this mistake! i spent so long trying to debug this. thanks for asking this question :D
