### ISSUE TITLE
still getting rekt by level 7 2nd set of test cases

### ISSUE THREAD

**Issue by johnnythesnake12** [nus-cs2030/2122-s2#461]
Could someone point out the possible logical flaw in my code based on my failed test case? 
Seems that my server 1 decided to take a rest after serving just 1 customer, what a clown.
But not sure why it decided to do so...

![Screenshot (32)](https://user-images.githubusercontent.com/98082700/164460381-6aa0e0b5-1bfc-47f3-ac22-9ad83feaf7b9.png)
![Screenshot (33)](https://user-images.githubusercontent.com/98082700/164460394-63c02d0e-5b9e-444c-bf04-6dfa51cbc7bf.png)

**Comment by Guanjung27** [comment]
it could be because of how you get your restimes, you might want to check your implementation and ensure you are not double calling the rest time supplier
