### ISSUE TITLE
Level 8_1 

### ISSUE THREAD

**Issue by eugenetaan** [nus-cs2030/2122-s2#464]
# Summary
Hi guys so im facing the same error as in #441, after doing some debugging I think ive identified the problem so as in the screenshot below 

## Description 
I think the problem lies in that everytime a Done event is called the queue is wiped and hence in the test case when customer 14 arrives 10 and 13 are supposed to still be in the queue for Server 1 but since the queue is wiped 14 sees the queue for server 1 as having space and thus waits at 1 instead of at 2. However after multiple tries of debugging I cant seem to get it to work, though I passed all of level 7 testcases. Anyone knows what I can do next ? 

## Screenshots (if any): 
Debugging Screenshot
<img width="357" alt="Screenshot 2022-04-21 at 7 10 03 PM" src="https://user-images.githubusercontent.com/80191549/164480162-bb38fb52-810a-44e1-9b6e-fffc36b32a2f.png">

Code Crunch Result
![Screenshot 2022-04-21 at 10 34 34 PM](https://user-images.githubusercontent.com/80191549/164481861-5f569422-dcad-474a-b706-015233b6e787.png)

**Comment by eugenetaan** [comment]
Hmm for the done event i only call a doneServingCustomer method to update shop,

```
    public Shop doneServingCustomer(Server s, double eventTime) {
        Server tempS = s.doneServing(eventTime);
        int serverIndex = s.getServerID() - 1; 
        tempS = tempS.rest();
        return new Shop(servers.set(serverIndex, tempS), this.stats, firstSelfCheckout);
    }
```

and the doneServing() and rest() methods are below 

```    
    public Server doneServing(double eventTime) {
        return new Server(serverID, true, eventTime, this.queue, maxQ, restTimes, restTime, selfCheckoutCounter);    
    }

    public Server rest() {
        if (selfCheckoutCounter) {
            return this;
        }
        double newRestTime = getNewRestTime();
        return new Server(serverID, available, nextAvailableTime + newRestTime, queue, maxQ, restTimes, newRestTime, selfCheckoutCounter);
    }
```
None of the methods modifies the server queue so I'm having such a hard time figuring this out why the queue changes

**Comment by TohDeKai** [comment]
@eugenetaan can i ask how you managed to solve this?

**Comment by jonyeokj** [comment]
did you manage to solve this?

**Comment by eugenetaan** [comment]
Yup i managed to solve this! My issue was with my doneServing not updating the server properly, I should have updated the server in the shop by calling a shop.getServer(serverIndex) but I was instead updating the server input.

**Comment by jonyeokj** [comment]
Alright thank you, I managed to solve it similarly as well haha. I wasn't updating my servers properly and didn't update my server when the Done Events were executing. Thank you so much!
