### ISSUE TITLE
Level 8_4

### ISSUE THREAD

**Issue by shanernigans** [nus-cs2030/2122-s2#465]
hello, im not really sure why customer 12 does not get immediately served after 9 is done at self-check 3 (14 gets served instead).
for context, i have a method that returns the earliest available self-check in my Shop class, which returns that 12 would get served by self-check 3.

## Screenshots (if any): 
<img width="399" alt="image" src="https://user-images.githubusercontent.com/100223061/164484138-1e1c6df8-bef7-4b8a-9a54-ec58080c17cc.png">

**Comment by abigailxj** [comment]
hii did you update all the other self check counters in Wait each time one of them gets a waiting customer? self check 3 should have a queue too since self check 2 has 2 customers waiting currently, so customer 14 can join the queue instead of get served

**Comment by sherrycqu** [comment]
Hi! Maybe you can provide more information about your implementation. Do you have a self check waiting list to store all the customers waiting? If yes, then when you call the next serve event, you can get the first customer from the list to be served. And if you have a pending class, you can check if the customer is the first in that list, if not, return another pending event with event time of the earliest self-check counter available time.
