### ISSUE TITLE
Level 9_16

### ISSUE THREAD

**Issue by fionlim** [nus-cs2030/2122-s2#467]
Hi! I'm currently stuck on 9_16, right now the logic of my simulate8 is that i store wait events so that they are executed after done events (if event involves self check outs) or rest events (if event involves server). There also seems to be some problem with my service times, and the customers are not served by the correct servers. Is there any other way to control the flow of events to correct this?

## Screenshots (if any): 
Insert Images here if necessary
<img width="927" alt="AC853DC3-5119-412A-92E3-5FEC9CB67C65" src="https://user-images.githubusercontent.com/98956367/164497757-1602a8b3-7f33-411b-8b29-7063a2976052.png">
<img width="924" alt="A912CD02-4945-4646-A07D-281B3D9E9D21" src="https://user-images.githubusercontent.com/98956367/164497793-5b94b71a-e0b4-41a8-a65b-3660a9c7c796.png">

**Comment by summerthia02** [comment]
hmm not too sure but I dun rly understand the way your implementation is. like why is your wait events only executed after done events?

**Comment by fionlim** [comment]
@summerthia02 hi summer! this is to ensure that the event takes in the most updated shop, rather than letting them be executed immediately when the done event has not been executed since the done event updates the server's next available time.

**Comment by Cheehao4** [comment]
Hi, do u have a boolean to check if your server serving in your server class? If not you can try adding that! Hope it helps!

**Comment by fionlim** [comment]
hi! i think my main problem was that i was holding back my wait events, so they were not being executed properly. I resolved it by adding an additional event such that instead of serving the first customer in the queue immediately, i do a pre-serve so as to ensure im only serving after the rest time of the server. This way, i did not have to hold back my wait events in simulate8.
