### ISSUE TITLE
Project level 8/9 logic of updating self check servers 

### ISSUE THREAD

**Issue by wannyu** [nus-cs2030/2122-s2#469]
Hi I managed to pass level 8 but I cant seem to fix my code for the level 9 private test cases. 
Currently, this is how my implementation works:

I created an ImList of customers at the very start of the run() method in simulate8 to represent the list of customers for the shared queue. My Self Check Server is a child class of Server.

Whenever there is a WaitEvent or ServeEvent or DoneEvent involving a Self Check Server, I would update all the Self Check Servers in the shop to the have the same list of waiting customers. Additionally, if there is a DoneEvent and the list of customers for the shared queue is not empty, I would create a new ServeEvent for the first customer and remove the customer from the list. 

May I know if this logic is wrong? I'm quite unsure of how the shared queue should be updated accordingly. Any help would be greatly appreciated. Thanks in advance!

<img width="689" alt="Screenshot 2022-04-22 at 12 25 47 AM" src="https://user-images.githubusercontent.com/99942808/164506999-da9695c3-3b03-4780-8e99-4d23848f6640.png">

**Comment by Seibell** [comment]
What i did was that i have an entirely separate event flow in the arrive event class. In my event class, i check if my server is a human or a self-checkout, if its a selfcheckout then it will go through the wait/serve/done based on its own queue (implemented in the shop) so i don't have to deal with any inconsistency

**Comment by herq-ules** [comment]
hello you mentioned that "Additionally, if there is a DoneEvent and the list of customers for the shared queue is not empty, I would create a new ServeEvent for the first customer and remove the customer from the list." are you removing the first customer (the one you are creating the serve event for) from the list? 

what i did was to remove a customer from the waitlist only when executing a serve event, add customer only when executing wait event and not change the waitlist during a done event. hope this helps!

**Comment by wannyu** [comment]
@herq-ules 
Ohh I see where I went wrong now, the customer should be removed from the queue when its served, not during a done event. Fixing this made it pass the test case. Thank you very much!!
