### ISSUE TITLE
Project Level 8 How to select SelfCheck Server 

### ISSUE THREAD

**Issue by Lu-Yi-Fan** [nus-cs2030/2122-s2#472]
hi i have a question, when i create a wait event of a customer and a self check server, it might not be served by the self check server that it is waiting at. How do i go about creating a serve event for this particular wait event, do i get the best available self check out server meaning i sort the self check out server and get the earliest available timing

**Comment by herq-ules** [comment]
hello! what i did was to create a serve event after a done event is executed within my simulate8 using the same self check server that just finished the done event

**Comment by seanpbteo** [comment]
Hi, my implementation was to handle it inside of the waitEvent's execute method such that I'll search through all of the shops self check servers for the server with the earliest done timing and pass that into the next serve timing instead of the original allocated server. Hope this helps!

**Comment by lyzhou717** [comment]
Hi what i did was that I checked my waitlist in my simulate. So whenever as selfcheck server was done serving, it checked the shared queue

that way the the earliest available server will always be selected

**Comment by Lu-Yi-Fan** [comment]
@herq-ules @seanpbteo @lyzhou717  thanks for sharing your implementation! appreciates!
