### ISSUE TITLE
Level 7_2 answer is the same as Level 7_1

### ISSUE THREAD

**Issue by pwintthiri** [nus-cs2030/2122-s2#486]
# Summary
Hi, I tried printing out the rest times for the Server and everything was 0, except for Server 2 after done serving customer 6, the rest time is 3.1387621604911167.

In my Done event, I returned an Optional empty and the same shop. Then in Simulate7, I check if the event polled is Done, it will return a Break event with the same conditions as Done event. 

Then in the Break event, I call .get() to the Supplier to and save that as a double restTime. I update the Server's end time to the previous end time + restTime and change the Server's status to busy. Then I return a BreakEnd event with event time which is the updated Server's endTime and the updated shop. 

Finally in BreakEnd, I have an if the Server has Customers waiting, I update the Server's status to not busy and return a Serve event for the first customer in the wait list and update the shop status. If the wait list is empty, the Server's status is not busy and I return an Optional empty and the updated shop status.

I'm not sure where it's going wrong. Thank you!

**Comment by abigailxj** [comment]
hi only the first rest time should be 0 so maybe youre not calling an updated supplier for rest time? i had the resttime as an attribute for Shop so each time it is updated the next resttime.get() will be updated as well, since shop is shared across all servers

**Comment by pwintthiri** [comment]
> it is updated the next resttime.get()

Hi, thanks for your reply! What do you mean by an updated supplier? Currently, my rest time is an attribute for Server instead of Shop. Do you mean that one Shop will only have one rest time instead of there being a rest time for each Server?

**Comment by pwintthiri** [comment]
Update: I printed out the rest times and I think the problem is that the updated rest time is going to the second server instead of the first server at customer 2. How can I fix this?

![Screenshot 2022-04-22 at 4 24 50 PM](https://user-images.githubusercontent.com/95198407/164649032-441fce3b-ae6f-4407-b4dd-73279b23a3e1.png)

**Comment by abigailxj** [comment]
Do you mean that one Shop will only have one rest time instead of there being a rest time for each Server?
- yepp otherwise the Servers might get repeated rest times when theyre actually all supposed to be different

**Comment by pwintthiri** [comment]
> Do you mean that one Shop will only have one rest time instead of there being a rest time for each Server?
> 
> * yepp otherwise the Servers might get repeated rest times when theyre actually all supposed to be different

Ohh that's the problem I have now! So is it like whenever the Server is updated, I do something like shop.getRestTime()?

**Comment by abigailxj** [comment]
hmm what i did was update the rest in Done so the shop in the done.execute(shop) will update that server's next avail time by adding rest time from the shop. i had a shop.restServer() method to do this

**Comment by pwintthiri** [comment]
> server's next avail time by adding rest time from the shop

I just tried to do this but I only get 0 for all the values so I'm not getting updated Supplier values. I added the restTime attribute to Shop and remove it from Server. Then I updated the Server's next available time by adding Server's end time and the rest time from Shop.
 I think my error is because i initialise Shop in Simulate7 constructor by doing `this.shop = new Shop(servers, restTimes)` so the restTimes remain the same throughout. I'm not sure how to get different values from the Supplier each time round. How did you ensure that the Supplier values are updated in Shop?

**Comment by abigailxj** [comment]
i think thats ok as long as the shop is updated after each event is executed in simulate's run(). so in the shop class the shop.restServer method can call this.restTime.get which u can use to update the server and update shop with the newServer

**Comment by pwintthiri** [comment]
> i think thats ok as long as the shop is updated after each event is executed in simulate's run(). so in the shop class the shop.restServer method can call this.restTime.get which u can use to update the server and update shop with the newServer. then Done.execute will return optional.empty and the updated shop

omg I got it thank you so much!!
