### ISSUE TITLE
Level 3 Cyclic Dependencies Done -> Serve

### ISSUE THREAD

**Issue by muhdjabir** [nus-cs2030/2122-s2#492]
# Summary
Hello I'm currently stuck on level 3 with calling a Serve Event in my DONE event. Im facing the issue of cyclic dependencies. I read in the forum something about calling it in the Simulate, but im not really sure how to do that. Can anyone point me in the right direction?

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
<img width="240" alt="image" src="https://user-images.githubusercontent.com/99940885/164651636-556597d4-1ea4-4253-abc8-5b998a4dde70.png">

**Comment by wjahoward** [comment]
Based on the screenshot, it can be seen that done.class and serve.class are "linked" to each other: `DONE.class -> SERVE.class` and `SERVE.class -> DONE.class`, you can take a look at those two classes and do the changes.

**Comment by nuzzul** [comment]
hi jabir! im facing the same issue broski! so dont feel too disheartened!

**Comment by lyzhou717** [comment]
Hi! i think what they mean was checking the waitlist in simulate. So your done shouldn't really be calling any events (serve!!) other than empty event (or like a Rest event in later levels).

**Comment by jeffhzy** [comment]
Hello for me i returned an `Optional.empty()` in the execute of my Done class. In my Simulate I created a PQ of Arrival events for each of the customer, and then looped through it to poll each event. If the polled event returned another event other than `Optional.empty()`, I added it back to the PQ. I didn't have any cyclical issues doing it this way. Hope this helps!

**Comment by ReganKvioke** [comment]
Erm for me is because I called Wait(Arrive event) which takes in an Arrive event leading to Cyclic Dependency. Maybe you can double-check this? Hope this helps.

**Comment by StanleyMak** [comment]
Hi, you have to make sure your classes dont call each other and at most, only one direction. For example, if your Class A utilises Class B in one of the methods, Class B cannot use Class A in any of its methods

**Comment by sherrycqu** [comment]
Hi! The cyclic issue could be caused by serve -> done -> serve -> done ... which is not correct. For me, instead of calling back Serve in Done, I return an empty EventStub in Done and in Wait, I return a serve event at the next available time of the server. So, the flow is Arrive -> Serve -> Done -> EventStub (END) ; Arrive -> Wait -> Serve -> Done -> EventStub(END).

**Comment by muhdjabir** [comment]
Hi thanks all I've solved the issue !! by returning an empty optinal in done instead of return another serve event if there was a wait pending
