### ISSUE TITLE
Level 4 Statistics Class How to get Event information

### ISSUE THREAD

**Issue by muhdjabir** [nus-cs2030/2122-s2#496]
# Summary
Hi everyone, was thinking of the statistics class and cannot seem to come to a conclusion as to where it should be tracked.

## Description 
Based on the codecrunch task, its clear to see that Statistics should probably be tracked on the Simulate4 class and the previous classes should be left relatively untouched. I was just wondering then how you guys took note of what type of event it was and get the specific timings?

## Screenshots (if any): 
<img width="721" alt="image" src="https://user-images.githubusercontent.com/99940885/164728869-c1be6c4e-205d-4c5f-b980-ca27a9d87ef0.png">

**Comment by jefflimwz** [comment]
Hello! The question is prompting you to create a new class `Statistic` that handles the event details, although you can also try to implement it directly in simulate if you want.

To keep track of each event type, maybe try adding a method to identify each event type within each event class? As for timing, you can make use of the fact that each event involves a customer which contains information about his arrival time, and that every event occurs at a specific timing.

**Comment by fionlim** [comment]
Hi! my statistics class stored leave events and done events in separate lists. i only tracked done events since they contained done times(from the done event time), customer arrival times and service times(from the customer)

**Comment by Keefetgy** [comment]
Hi you can consider storing the variables that needs to be printed in a Statistic class and include methods that will help you update the corresponding attributes.

**Comment by maximyam** [comment]
for me, i store my statistics object in Shop so after every event I can update it with the relevant changes. event such as serving, and leaving are important to note because of how it changes waitingtime, customer served and customer left

**Comment by muhdjabir** [comment]
HEY GUYS THANKS ALOT FOR ALL THE HELP I chose to implement it like how Jeff recommended ! thanks alot for the prompt assistance guys!

**Comment by nuzzul** [comment]
YUP Thank u!
