### ISSUE TITLE
Project Test Case 9 - 16

### ISSUE THREAD

**Issue by Cheehao4** [nus-cs2030/2122-s2#499]
# Summary
Unable to pass test case 9 - 16

## Description 
Hi guys, I am stuck at test case 9 - 16, where customer 21 is waiting at server 3 instead of server 1 and I am unable to solve the issue. Would appreciate some help to get pass it. Thank you!
## Screenshots (if any): 

![image](https://user-images.githubusercontent.com/99947120/164752304-42ba0eef-a091-48c7-ac5d-0ef26dde3700.png)

**Comment by zeentan22** [comment]
For my implementation, I will have a comparator to sort my servers based on their ids so that I will get the right server. Or maybe u can check if your rest time is implemented correctly? Hope this helps!
