### ISSUE TITLE
Individual Project Submission

### ISSUE THREAD

**Issue by YohKato** [nus-cs2030/2122-s2#500]
This is generic questions for our project.

1. How do we submit our final codes? 
I do not remember exactly how we are suppose to submit our final codes for our project. Do we submit on codecrunch as usual for any labs? Or, we need to submit the .class files inside the cs2030 in a zip file to somewhere else.

2. What happens if we cannot pass all the tests on codecrunch?
I know that this project is marked for the formats and structures as well as the correctness of the codes. However, do we need to pass all the tests on codecrunch to start with?? I remember for PA, if we do not pass all the tests, we will be awarded 0 so I am wondering how the scores to be calculated.

If you have any information on above two, it would be helpful!!

**Comment by elvern18** [comment]
Hi ! 

Not sure about the second question, but for the first question, its just the same as normal lab sessions whereby you upload the .java files on codecrunch. You do not have to submit the .class files.

**Comment by ChngWC** [comment]
Hi! 

For the 2nd question, my TA mentioned that there will be partial marks given depending on how much you have progressed in the project. Though, I am not sure how is the progression being measured but do try to do as much as you can!

**Comment by YohKato** [comment]
I see, okay thanks!!
