### ISSUE TITLE
Project Level 3(?)

### ISSUE THREAD

**Issue by Tohtoroo** [nus-cs2030/2122-s2#503]
![image](https://user-images.githubusercontent.com/100463724/164790280-57553605-1000-4d62-b600-098fced13a21.png)
basically i just really dont get how I'm out of index range? This is after I implemented level 8, and it passes 8_4 test case, so originally it was already working for this, but i have no idea what i changed that would even remotely affect so early in the levels, if anyone got any insight it would be greatly appreciated!!

**Comment by mingshan2705** [comment]
Since the error occurs in your ArriveEvent, maybe in there you could input a print statement to print out the "status" of the ImList to help with debugging. You can also try to trace out the code line by line since level 3 test cases are quite short. All the best!

**Comment by jlee1007** [comment]
since the error from a get could it be that you have accidentally removed an obj from the list too early such that at the next Arrive the list is empty?

**Comment by Brianliew77** [comment]
Hi, I think the index out of range probably arised due to the loop conditions. First try to locate which loop is causing the condition first. U can try commenting to ur code or something along this line to check. Its likely that its a minor error like <= instead of < etc. Hope u are able to debug!

**Comment by Tohtoroo** [comment]
SOLVED! It was just an inequality error that arised when I was checking for checking queues in self checkout, where the if elses in my arrive event went to get a self checkout server when there was not any since the checking queues always returned true.
