### ISSUE TITLE
Level 7 Implementing a REST event after DONE 

### ISSUE THREAD

**Issue by muhdjabir** [nus-cs2030/2122-s2#509]
# Summary
Hello everyone it's (Code)crunch time and I'm currently wondering for Level 7. My logic for this level would be to set the server to rest and return rest event where it would update the server back to working. I was just wondering to ensure the priority of the rest event being polled first, would attaching a Customer(0) result in any issues further down the road? If yes, what are the approaches that you have considered

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary

**Comment by eugenetaan** [comment]
Hi, i think if the customer u associated to the rest event is not being touched at all and is a placeholder it should be fine, but personally I feel there's no need to create a new event class just for rest instead what I did was I updated the nextAvailableTime of my server upon each done event and updated the events time directly in the simulate file instead. Hope this helps!

**Comment by Seibell** [comment]
I had a done event > rest event > done resting event to make it easier for myself

**Comment by muhdjabir** [comment]
@Seibell oh but since you can have events that happen at same time and you want to make sure the rest and done resting occurs first how did you ensure that those happened first
