### ISSUE TITLE
Level 5 Test Case 5_3

### ISSUE THREAD

**Issue by AmirulShyakir** [nus-cs2030/2122-s2#520]
I'm not entirely sure what is going here. I'm able to pass 5_1 and 5_2 but it seems like the first customer is done at time t = 1 instead of t = 0.313 and it snowballed abit. Funnily enough, its didn't snowball large enough to affect the end statistics. Any help is appreciated thanks!

<img width="440" alt="Screenshot 2022-04-23 at 10 15 32 PM" src="https://user-images.githubusercontent.com/72700184/164910098-e59e7677-da9a-4f38-91dd-fb28036ba4a4.png">

**Comment by kkinmunn** [comment]
It seems like you're getting a fixed service time of 1.0 for every customer instead of getting the specific service time from the supplier. Perhaps you want to check if you're calling the supplier to get the specific service time correctly? Hope this helps.

**Comment by leeannong** [comment]
@kkinmunn hi I am facing this problem too, I added into simulate5:
`double serviceTime = this.customer.getServiceTime();
Event nextEvent = new Done(this.customer, this.time + serviceTime, this.assignedServer);`
but it doesn't seem to read the arrival times in test5_3. Is this implementation correct though?

**Comment by kkinmunn** [comment]
> @kkinmunn hi I am facing this problem too, I added into simulate5: `double serviceTime = this.customer.getServiceTime();` `Event nextEvent = new Done(this.customer, this.time + serviceTime, this.assignedServer);` but it doesn't seem to read the arrival times in test5_3. Is this implementation correct though?

Does not seem to read the 'arrival'(?) time ? They look ok imo (depending on how you implemented), perhaps you want to look at #227 alternatively if it gives you more ideas!

**Comment by harisdzl** [comment]
hi @leeannong @AmirulShyakir, wherever you added the service time of 1.0 for the previous levels, you can try to change the 1.0 to the service time of the customer which is obtained from by using .get() on the lazy property in your Customer. also note that you should only be calling .get() in one place! hope this helps

**Comment by leeannong** [comment]
@kkinmunn @harisdzl I managed to find and resolve the issue, thank you!

**Comment by AmirulShyakir** [comment]
thanks all @kkinmunn @leeannong @harisdzl it appears to be that i updated my Shop's available time with the get, however my Serve class was still returning a Done with t + 1.
