### ISSUE TITLE
Project failed at Test Case9_16

### ISSUE THREAD

**Issue by JunRay** [nus-cs2030/2122-s2#525]
# Summary
The output is not in chronological order

## Description 
Serve Event at 10.225 is only printed out after a Done Event at 10.753. I highly doubt its the event comparator's fault?

## Screenshots (if any): 
Insert Images here if necessary
<img width="692" alt="Screenshot 2022-04-24 at 12 22 07 AM" src="https://user-images.githubusercontent.com/85005447/164914554-ef3c0cf5-1210-4dd5-975f-da763517abd1.png">

**Comment by pearlynliu** [comment]
hi! do you have an event before serving and after wait (aka Pending event)? if yes, then i think the error might be there

**Comment by jlee1007** [comment]
could check where did you return the new serve event from the pending class (if any) 
trace to code to see if it runs in chronological order!

**Comment by Brianliew77** [comment]
Try tracing ur code to check if it runs in chronological order. Else u can do system.out.println statements to see where ur events move. Hope this helps u debug!

**Comment by JunRay** [comment]
Thanks for the help! The issue came from the pending classes!
