### ISSUE TITLE
Level 7 test case 2 confused

### ISSUE THREAD

**Issue by xiaotuziyi** [nus-cs2030/2122-s2#529]
## Description 
Customers are not assigned to the correct server. I have tried to compare using server.nextAvailableTime() and then by the ids but when case 7_2 is correct, the earlier test cases are wrong. **How should I do it? I'm really confused.** 
![image](https://user-images.githubusercontent.com/61974028/164946561-fc7c33bd-1323-48b3-9ffb-7c9cb68b922c.png)
Implementation: (in case this wrong)
In my simulate7, when the event is "done", I  will update the server's next available time with restTime generated. 
For my previous level, I let waitEvent.exacute to return Optional.empty. then I will only create the Serve Event for waiting customer in simulate when an event is "done".

## Screenshots (if any): 
<img width="308" alt="test7_2" src="https://user-images.githubusercontent.com/61974028/164946425-28a98170-69d8-42c1-9a4d-ff84affbad7a.PNG">

**Comment by Brianliew77** [comment]
Hi, i suspect that your servers arent taking rest time into consideration as it still calls server 1 in #9. How did u call ur supplier?

**Comment by xiaotuziyi** [comment]
> 

I used a this.restTimes.get() where this.restTimes is the Supplier<Double> I stored.

**Comment by Longhao307** [comment]
I created another variable to store the time and compare.

**Comment by pearlynliu** [comment]
hi! i am not sure if the error is in the line where you create the serve event. i think you can try having the new serve event at the updatedServer's next available time (would already include server's rest time), rather than e.eventTime + restTime

**Comment by xiaotuziyi** [comment]
> time

Thanks, I have tried but I think is not that error. I end up solved by creating 2 other events called serverRest and serverBack. and now it finally pass all test.
