### ISSUE TITLE
Project Style Check

### ISSUE THREAD

**Issue by jonyeokj** [nus-cs2030/2122-s2#530]
Hello, this is a simple fix, but I cant figure out for the life of me where this style check error is :(
Can anybody point it out to me, AHHHHHH

Screenshots:
<img width="922" alt="Screenshot 2022-04-24 at 10 50 26 AM" src="https://user-images.githubusercontent.com/84386849/164954079-58e3f3c0-efd4-40ee-a75e-ea05b0b4c763.png">
<img width="553" alt="Screenshot 2022-04-24 at 10 51 53 AM" src="https://user-images.githubusercontent.com/84386849/164954308-e8dd7d94-8505-42a8-96dd-c62f22838164.png">

**Comment by nicljr** [comment]
hi the problem is in the for loop statement, it should be (for int i = 1; i <= n; i++) and not (for int i = 1 ; i <= n ; i++).

**Comment by jonyeokj** [comment]
> hi the problem is in the for loop statement, it should be (for int i = 1; i <= n; i++) and not (for int i = 1 ; i <= n ; i++).

bro pm me your number i paylah you 5 dollars rn

**Comment by ReganKvioke** [comment]
yeah that's the error, the space before ;

**Comment by tristky** [comment]
Hi, i encountered this problem too many times when doing the prac, it is as simple as deleting the space before ;.
