### ISSUE TITLE
PYP q3b

### ISSUE THREAD

**Issue by ReganKvioke** [nus-cs2030/2122-s2#531]
For 3b, the question asks for convert(arr, f) however the jsh file provided convert(arr, function, f). 
Anyone has an elegant way to combine these 2 functions?

**Comment by jamietan123** [comment]
i think the answer in the jsh is not the correct one

**Comment by Swagston20** [comment]
there is only 1 function parameter. What the qns is trying to say is the function specifies how the array is accessed and how the elements are to be mapped. so is convert(arr,f)

**Comment by spicyseaweed** [comment]
i think the code in the jsh provided is not correct, however I cannot think of a way to make sure one function can achieve the 2 purposes stated on the question.. need help here too!!

**Comment by shotnothing** [comment]
flatmap guys

**Comment by shotnothing** [comment]
lmao all the jsh answers seem super whack. for this qn just use one fn and flatmap.
