### ISSUE TITLE
Level 7: Server time not updated before serving next customer

### ISSUE THREAD

**Issue by joannelxl** [nus-cs2030/2122-s2#532]
Hi! For the rest time of the server, i called it only when the server is done serving the customer. However, it seems like the updating is too late.

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/79855907/164955268-439f0692-0337-4114-b3a9-6b2bcf1ff620.png)
9 serve by 1 gets polled out, and gets executed to become 9 is done serving by 1. This is added to the PQ. But then because 9 done serving by 1 is not called yet, hence the server's next available time is not updated before 10 pending serve gets polled and executed. So when 10 is polled out, it will be still the server's old next available time before it gets updated.

Any help will be appreciated, thanks!

**Comment by pearlynliu** [comment]
hi joanne! i personally have an event PreServe after Pending event to check whether the server is done resting.

what i do is that my pending event either returns another pending event or PreServe event at the nextAvailTime. the PreServe event then checks whether the eventTime >= server's nextAvailTime. this is to make sure the server is done resting. then it either returns another PreServe event at nextAvailTime or a Serve event at current eventTime.

i hope this helps!!

**Comment by joannelxl** [comment]
hi pearlyn! thanks for the suggestion! may i know where u added the server's resting time? Is it in PreServe ?

**Comment by pearlynliu** [comment]
> hi @pearlynliu! thanks for the suggestion! may i know where u added the server's resting time? Is it in PreServe ? because for me, i added it in done, and 9 done serving by 1 is not yet executed before 10 gets polled out

yep mine is the same! i think PreServe will be able to solve your problem of Serve event being added to the PQ before the Done event is executed

**Comment by joannelxl** [comment]
> 

oh i see, just to confirm my understanding for pending serve, if the customer is the first in queue, PreServe gets executed, else pending serve is returned. If this is the case i think it may work! since i have been returning a serve or pending serve. Let me try haha

**Comment by pearlynliu** [comment]
yep!! HAHA hope it workss

**Comment by joannelxl** [comment]
it works! thanks so much :)
