### ISSUE TITLE
Level 6 infinite loop for pending event

### ISSUE THREAD

**Issue by nuzzul** [nus-cs2030/2122-s2#537]
# Summary
Infinite loop of Pending Event.
![2022-04-24](https://user-images.githubusercontent.com/97597986/164958865-bef6e844-746a-44ad-bc64-4e64c99c0ccb.png)

## Description 
Hi guys, so i know for level 6 we need to have a pending event. 
Wait -> Pending
Pending -> Serve
Pending -> Pending ( if customer isnt first in queue, event time is next available time of server)
But my output stops at "9 serves by 1" line.
I suspect that theres an infinite loop of pending event since my output doesnt even show the statistic output. Im not sure where im going wrong or what im missing. Any help is appreciated thank u.

## Screenshots (if any): 
Insert Images here if necessary

**Comment by rexlionz** [comment]
Hi! I would recommend debugging the infinite loop by adding println statements in your pending server class, so at least you would be able to tell at which point in your code the infinite loop starts triggering. If you want to track you should add println statements in your simulate run method as well to trace your code. I hope this helps!

**Comment by zendenleong** [comment]
Hi! Since your output stops at "9 serves by 1", I suggest you either look at your Serve class or your Simulate whether it adds your Pending Event into the PQ. If it looks alright, then the problem should lie within your Pending Event. You can try adding print statements in the simulate run method as mentioned! I don't really know your pseudo code, so that's all the problems I can think of

**Comment by kaitlyngoh** [comment]
i personally did not use pending but maybe you can check if there is any cyclic dependency between pending and serve? some of my friends had a similar issue  of infitinte loop due to cyclic dependencies

**Comment by coffeecode2** [comment]
Hi, I personally used the same implementation as you, with my Wait -> Pending -> Pending again -> Serve.

**Comment by evelyynnz** [comment]
Hi! i got this error too & i resolved it by updating the event time of pending class. u could try debugging using  println Statements in ur pending class/ in ur simulate 6 to help as well

**Comment by nuzzul** [comment]
Thank you for ur help everyone i managed to solved it.
