### ISSUE TITLE
19/20 Sem 1 Qn 6.

### ISSUE THREAD

**Issue by Lu-Yi-Fan** [nus-cs2030/2122-s2#541]
Hi does anyone know what the answer should be for this question?  I got x -> (f.apply(x) + delta) - (f.apply(x) - delta) / 2 * delta;
Has anyone tried 
![Screenshot 2022-04-24 at 3 58 11 PM](https://user-images.githubusercontent.com/88626655/164966349-6c0fb486-841f-45d3-a35f-b21ea344906e.png)

<img width="976" alt="Screenshot 2022-04-24 at 4 02 50 PM" src="https://user-images.githubusercontent.com/88626655/164966482-e6fcbde5-4703-41ed-8565-1b22a7309acf.png">

**Comment by kaitlyngoh** [comment]
hello i think you should write x -> ((f.apply(x) + delta) - (f.apply(x) - delta)) / (2 * delta) because delta is a constant so you should not need to apply it as a whole like x + delta

**Comment by jingyulim1** [comment]
Base on the formula provided, f applies to x+delta and x-delta. What I would do is
 `x -> (f.apply(x + delta) - f.apply(x - delta)) / (2 * delta)`

**Comment by ca-leb** [comment]
hi, i think your answer would not give the desired output as f should be applied on (x + delta). my answer for this qn was:

**Comment by jamietan123** [comment]
I think your answer would be different as delta should be in the bracket, just like as shown in the formula
