### ISSUE TITLE
20/21 Sem1 Q1d

### ISSUE THREAD

**Issue by jingyulim1** [nus-cs2030/2122-s2#542]
# Source
20/21 Sem1 Q1

## Description 
Does anyone know how to chain them together for part d?  After doing part c, `set` returns a new object so that it is immutable.

I tried the following but it wouldn't work, since `a.set()` will return a new A which is different from the original one (other is empty in the original a).

`A a = new A();`
`a = a.set(new A().set(new B().set(new B().set(a))))`

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/95527957/164967846-4366f929-ba69-4c30-b758-717a6cb57f03.png)
![image](https://user-images.githubusercontent.com/95527957/164967894-b6cba408-169b-45e4-ab29-e0d39d8b6542.png)
![image](https://user-images.githubusercontent.com/95527957/164967906-2752eb9b-410e-432a-9d6a-c5949df24401.png)

**Comment by ca-leb** [comment]
hi, I am facing the same issue as well. I have tried something similar to the traffic light question in the mock paper but I couldn't get it to work :(
