### ISSUE TITLE
Project Level 7 restTimes Approach

### ISSUE THREAD

**Issue by jonyeokj** [nus-cs2030/2122-s2#549]
# Summary
I managed to solve this level by storing the restTime Supplier in the customer class, but I was wondering if there was any alternative approach to this level?

## Description 
In the screenshots below, I stored my restTime Supplier in the customer class, and only called the method in the customer and got the restTime when a Done Event was executed. However, I don't think the restTime Supplier variable should be assigned to the customer but instead to the Servers themselves, as it doesn't make sense for customers themselves to have restTimes. I tried implementing it that way, but the order in which the restTimes.get() was called turned out to be different. Has anybody successfully implemented their restTimes to their Servers as described? If so, how did you manage to approach and go about it? Thanks in advance!

## Screenshots (if any): 
<img width="560" alt="Screenshot 2022-04-24 at 6 46 28 PM" src="https://user-images.githubusercontent.com/84386849/164972738-53717863-a176-4345-9a91-335d857e1bbf.png">
<img width="301" alt="Screenshot 2022-04-24 at 6 46 32 PM" src="https://user-images.githubusercontent.com/84386849/164972739-55df0a66-1aa7-41e5-aef7-a12c9a868aa7.png">
<img width="405" alt="Screenshot 2022-04-24 at 6 46 46 PM" src="https://user-images.githubusercontent.com/84386849/164972741-34da5626-49e0-4754-ad7f-10a3c6148911.png">

**Comment by tristky** [comment]
Thank you for the inputs Jonathan, I believe this will help many of my friends who are struggling with this issue and i will gladly share with them, they seem to be stuck here and they will be so happy to know that this solution is on github. May i invite you to a coffee when the semester starts next semester as i would like to get to know likeminded individuals who are brilliant at CS2030 and who are able to grasp the concepts of this topic and also think outside the box which is very crucial to this module where it rewards very good knowledege and ability to think beyond the scope of the course. Meet Soon! thanks Jonathan for your inputs

**Comment by Noel-Lee** [comment]
I happen to implement the rest time in the Server class.
My events are the following, Arrive -> Serve -> Done -> Rest -> DoneResting -> Serve(if have customer waiting) else empty

my Resting event  just has to call a doneResting that is this.eventTime + server.getRestingTime() 
Hope this helps :)

**Comment by abigailxj** [comment]
hello maybe you can try putting restTime in Shop instead, and call it in Done. then you can just update the servers by adding it to their nextAvailTime if you have that attribute alr!

**Comment by mingshan2705** [comment]
I have the rest time supplier in servers, just keep in mind that you should only .get() during the DoneEvent while returning the updated Shop containing the updated servers

**Comment by Alexius0123** [comment]
Hi Jon! One method I was experimenting with was to simply add the rest times supplier function to the Server classes. This way, when a Done event is executed, you call the Supplier's get() method just once to retrieve the rest time using the server that was serving the customer in the event. This will ensure consistency in what you receive from the supplier (i.e. don't call more than once and get a different RNG output). 

This also makes sense from an Object Oriented Programming stand-point, where the Server should be in-charge of their own rest times, instead of delegating it to a customer who should have no visibility over how long the server should rest. (Single Responsibility Principle).

Hope this helps!

**Comment by dapscc** [comment]
hello, similar to noel and mingshan above, I put the resttime supplier in the Server class, and it is only called when the server is done serving a customer and triggers a Rest event. the duration of the Rest event will hence be decided only here and a new event that allows the Server to serve a new customer is triggered at the end of it!

**Comment by jonyeokj** [comment]
> I happen to implement the rest time in the Server class. My events are the following, Arrive -> Serve -> Done -> Rest -> DoneResting -> Serve(if have customer waiting) else empty
> 
> my Resting event just has to call a doneResting that is this.eventTime + server.getRestingTime() Hope this helps :)

Hello, thanks for all your replies! I will try it out and experiment with all these different implementations.

In particular, why did you create a doneResting Event in addition to your Rest Event? Shouldn't calling the restTime in the Rest Event be enough? Thanks for your response regardless :)

**Comment by Tohtoroo** [comment]
I used rest in my servers as well, only calling it in done and sending the server off to a rest event. I've heard its possible to just do it straight into the simulate though, so may you can try that?

**Comment by Noel-Lee** [comment]
U could take out the Rest event and call DoneResting after Done event straightaway, since a server would only be looking for customers after he or she is doneResting.

Dun mind the Rest event haha
