### ISSUE TITLE
Level 7_2 wrong servers

### ISSUE THREAD

**Issue by leeannong** [nus-cs2030/2122-s2#550]
Hi, I've managed to update my classes such that it prints out all the timings and statistics correctly for test case 7_2. However my servers are all wrong.

<img width="412" alt="Screenshot 2022-04-24 at 7 29 05 PM" src="https://user-images.githubusercontent.com/101859526/164974255-ae91bb23-fd1d-462f-b3f2-34b424545bbb.png">

A brief outline of how I implemented things:
When an event is DONE, I will call restTimes.get() to get a new **nextTime**, and add it to the new event 
`new Serve(cust, nextTime, assignedServer)`

I am guessing I have to probably implement some method to change the assignedServer if certain conditions are met? Would appreciate any advice on how to approach this, and if possible without adding a pending event! Thank you.

**Comment by jonyeokj** [comment]
Hello! I believe you're having this problem because your queues are not being updated properly, and hence your customers are going into the wrong queue. This is probably due to the fact that you're either not updating the queues themselves properly, or the state of the servers and shops. Check that your execute method for all your events properly update the states of the objects. Hope this helps!

**Comment by StanleyMak** [comment]
Try adding some debugging print lines to print out the queues of the server, or whether the servers can serve (if you have an idle boolean) to check where the state of the objects are not updated properly as according to jon's suggestion.

**Comment by Alexius0123** [comment]
Hello! It would seem that looking at the errors, your rest time is not being implemented properly. That is to say that your servers are not resting for the appropriate amount of time. One work around that you can do is call the supplier's get() function only in the Done class, and return a different Break class based off the timing you get.

Hope this helps!

**Comment by leeannong** [comment]
Thanks all for ur suggestions!
