### ISSUE TITLE
Extra lines in codecrunch after implementing Pending class

### ISSUE THREAD

**Issue by rotatingowl** [nus-cs2030/2122-s2#554]
Hi, I have now been getting this issue after implementing pending class, I did put "\n" at the end of all my event toStrings, not sure if that causes the problem. Are there other ways to print out the events?

![image](https://user-images.githubusercontent.com/104189900/164977272-2ff80bf3-0028-43d1-9c5a-94595a8036d7.png)

**Comment by evelyynnz** [comment]
hmm it seems like u added "\n" twice in your code. Perhaps u added it in your event toStrings and in ur simulate classes which thus results this error? 

Hope this helps!

**Comment by rotatingowl** [comment]
Hi thanks both, I realised i didnt remove "\n" from the previous simulators.
