### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by michael192002** [nus-cs2030/2122-s2#556]
# Source
18/19 SEM1
## Description 
Does anyone know how to go about this question?
## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/97863846/164979639-8f864fff-544a-4d11-8c65-c5a98b51e44e.png)

**Comment by pohja1999** [comment]
Hello, I think the idea is to convert all the numbers into MinMax class like a Pair/Wrapper, and make use of reduce to compare between the streams of MinMax. 
<img width="492" alt="image" src="https://user-images.githubusercontent.com/98691869/164983384-1da8cf56-058b-4e09-92b0-ee11663e0d50.png">

**Comment by Noel-Lee** [comment]
Btw, where do you find the pyp and answers for finals? I cant seem to find it

**Comment by pohja1999** [comment]
hello, i got the pyps from nus exam database. not sure where to get the answers tho :/
