### ISSUE TITLE
Finals open book?

### ISSUE THREAD

**Issue by ryuniqlo** [nus-cs2030/2122-s2#557]
Hi, just wanted to confirm if our finals will be open book like the mock paper. Thank you!

**Comment by Geraldworks** [comment]
yes it is

**Comment by evelyynnz** [comment]
yes iirc it is

**Comment by blmj00** [comment]
yup online and offline resources should be accessible

**Comment by jodytng** [comment]
yuppp it is!! all the best for finals everyone 👍

**Comment by AaronTay21** [comment]
yes it is

**Comment by fionaxjy** [comment]
yep it is. jiayou for finals!

**Comment by ryuniqlo** [comment]
thanks everyone, atb for finals!
