### ISSUE TITLE
What to put for toString() method in between wait and serve class

### ISSUE THREAD

**Issue by dorothyyuann** [nus-cs2030/2122-s2#559]
I currently have a blank "" string but it prints as a new line because my simulate class adds "/n" to it. This is my pending/buffer event class in between my wait and serve for level 5. Wondering what other people used instead? So far my only solution is to make another more complicated method to only add "/n" to non-buffer classes...
<img width="240" alt="Screenshot 2022-04-24 at 9 57 32 PM" src="https://user-images.githubusercontent.com/101258725/164980099-3c857036-074e-4766-b040-4a645d1f348f.png">

**Comment by denshem10** [comment]
what if you created a overriding toString() method?

**Comment by FeanTMX** [comment]
I used a identify() method to identify the class. In Simulate, I only added the line to my resulting string if .identify != Something

**Comment by evelyynnz** [comment]
i used an if else condition in my simulate as well as an idenfity() method. so if event.identify() == "Rest", it will not be added to my output

**Comment by pwintthiri** [comment]
Hi, I added a line with the class name to help me when debugging. But in the Simulate class, as @evelyynnz mentioned, I had an if the event was a Pending Event, I did not add it to my answer.
