### ISSUE TITLE
Default access modifiers

### ISSUE THREAD

**Issue by fionaxjy** [nus-cs2030/2122-s2#564]
Hi, could I ask what the default access modifier in java is? Is it protected? Is this the same as package-private? Thank you!

**Comment by denshem10** [comment]
![image](https://user-images.githubusercontent.com/37451609/164981219-aad87a6f-7b80-425f-a2ff-a47765503b63.png)


you can use this as a reference!
it's not the same as protected, and you should be able to access everything inside ur package.
Hope this helps!

**Comment by FeanTMX** [comment]
it is more restrictive than public so when you override methods you need to specify public!
