### ISSUE TITLE
Available PYPs

### ISSUE THREAD

**Issue by fionaxjy** [nus-cs2030/2122-s2#566]
Hi, may I know if I am able to find more of the PYPs anywhere? Thanks!

**Comment by blmj00** [comment]
you can check the nus library exam paper repository from here

**Comment by AaronTay21** [comment]
Hi i think most of the pyp are on cs2030s

**Comment by jodytng** [comment]
hi! I do have a few PYPs from my seniors (some with solutions) ! feel free to pm me if you want them for extra practice!! all the best for finalsss :-))

**Comment by dorothyyuann** [comment]
@jodytng do you mind sending them to me? thanks!
