### ISSUE TITLE
Unsure about how Optional OrElseGet works

### ISSUE THREAD

**Issue by AaronTay21** [nus-cs2030/2122-s2#568]
Hi does anyone know how optional.orelseget() works? do we need to input anything into it?

**Comment by Alexius0123** [comment]
Hi Aaron! How Optional.orElseGet() works is that it will either give the value of the thing stored in the wrapper context Optional, or it will give the other thing that you input into the .orElseGet() method as a parameter.

If you're still confused, think of it as a simple if-else control flow statement, where it works similar to if (Optional.isPresent()) { return thing;} else { return other thing not stored in optional;}.

Hope this helps!

**Comment by bryankwe** [comment]
Maybe an example might help:
`Optional.<Integer>of(5).orElseGet(() -> foo())` returns 5
`Optional.<Integer>empty().orElseGet(() -> foo())` returns whatever `foo()` does

**Comment by dorothyyuann** [comment]
orElseGet( ) contains a supplier and a supplier is meant to postpone execution until the function is called. Meaning that .orElseGet() will only call the given .orElseGet() function when the Optional.isPresent() == false

**Comment by fionaxjy** [comment]
Hi, OrElseGet() takes in a supplier and only executes when an Optional is not present!

**Comment by AaronTay21** [comment]
Thank you guys
