### ISSUE TITLE
PYP Q4

### ISSUE THREAD

**Issue by jwjiawei** [nus-cs2030/2122-s2#572]
# Source
PYP Q4 (Semester 1: AY2021/2022)

## Description 
Hi, could anyone explain the code in q4 to me? I don't really understand it nd hence do not know how to approach the question. Thank you!

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/99887027/164985181-f3a1cb04-8dbe-4834-9017-d7be292946fc.png)

**Comment by danyelys** [comment]
for a) MyStream.generate returns a new MyStream with the updated abstract method with a random number supplier. So the question is asking us to create a foreach method that is similar to that of the stream class. So some properties of foreach would be that it returns void and takes in a consumer.

**Comment by rachtan27** [comment]
> for a) MyStream.generate returns a new MyStream with the updated abstract method with a random number supplier. So the question is asking us to create a foreach method that is similar to that of the stream class. So some properties of foreach would be that it returns void and takes in a consumer.

@danyelys may i ask what did u "loop" through? for instance, in Imlist the forEach method loops through the this.list and applys the Consumer on each element.
But i cant seem to figure out what to "loop through" in MyStream

**Comment by Geraldworks** [comment]
The use of forEach could be defined differently for every context.
For the ImList, you are going through each element in the stored collection.
For this case of MyStream, notice that there is a get method that retrieves something from the Supplier, seed.
As such, your forEach should be attempting to get() something from the seed, for the number of times specified in the forEach arguments.

**Comment by jwjiawei** [comment]
i got it, thank u sm!!
