### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by michael192002** [nus-cs2030/2122-s2#575]
# Summary

Hi, does anyone know why this design's wildcard yields an error?
## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Scree
![image](https://user-images.githubusercontent.com/97863846/165029136-681d1a81-fec6-4a78-a4ad-4e1b6efb68f9.png)
nshots (if any)

**Comment by hengyjj** [comment]
i think it has got to do with your generic type T ? it is `private final Supplier<T>` but your `of method `is returning a `<? extends T> supplier`?
