### ISSUE TITLE
Final Exam Power Socket

### ISSUE THREAD

**Issue by mamayuan** [nus-cs2030/2122-s2#578]
May I know if we will have access to power socket at MPSH5? I dont think my laptop battery can sustain 2 hours without charging :(

**Comment by tanweiming00** [comment]
Here's an advisory from UG office regarding the DA (digital assessment) venue at MPSH5:
While the exam venue is DA ready, do note that there isn’t 1:1 PowerPoint for all students... Please remind students that they are expected to come to the exam venues with their laptops fully charged and only use the charging station if their laptop battery is low.

**Comment by tanweiming00** [comment]
Here's an advisory from UG office regarding the DA (digital assessment) venue at MPSH5:
While the exam venue is DA ready, do note that there isn’t 1:1 PowerPoint for all students... Please remind students that they are expected to come to the exam venues with their laptops fully charged and only use the charging station if their laptop battery is low.

**Comment by sshawnlim** [comment]
Yup, we will have access to a power socket at MPSH5! However they probably only recommend those who really need them to use it as there will not be enough power sockets for everyone!

**Comment by jlee1007** [comment]
yep but there isn't enuf for ev one so do charge fully first!

**Comment by jamietan123** [comment]
Yup but if need there will be don't worry

**Comment by Zhenyubbx** [comment]
Yup but we are supposed to fully charge the laptop first before going to the exam venue

**Comment by neverdivideby0** [comment]
Should be ok if you email the prof beforehand or you inform the invigilators on site
