### ISSUE TITLE
Q17

### ISSUE THREAD

**Issue by michael192002** [nus-cs2030/2122-s2#581]
# Source
18/19 SEM2
## Description 
Hi, does anyone know how to go about this question?
## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/97863846/165228293-22e93782-f6d5-49bb-9e2e-9c0f3e35e549.png)

**Comment by pohja1999** [comment]
Hello, i just iterate a stream of logs and takewhile it is less than the max of the two nums, and reduce it using an impure function which triggers the printing of the carry lines. then afterwards i return the carry value for the next reduction.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/98691869/165243952-b459009c-77ef-4df8-b95c-57d6b8c43828.png">

**Comment by Zhenyubbx** [comment]
yeap I also did the same thing^
