### ISSUE TITLE
20/21 sem1 qn1

### ISSUE THREAD

**Issue by nuzzul** [nus-cs2030/2122-s2#583]
# Source

## Description 
Hi i dont understand what qn1 b is asking for can someone point me in the right direction.
My idea is that i need to create a parent class where A,B,C extends. Or am i just meant to make the other attribute generic?
Thanks in advance.

## Screenshots (if any): 
Insert Images here if necessary
![2022-04-26 (2)](https://user-images.githubusercontent.com/97597986/165240305-557a7ffb-489e-4d94-b6bc-5ee0096e9c9e.png)

**Comment by pohja1999** [comment]
hmm? not really sure why a generic would be needed here if every A,B,C classes extends your abstracted/concrete parent class T. I think by LSP, all A,B,C would be directly substitutable for T since they're subclasses of T.

**Comment by ReganKvioke** [comment]
For this question what I did was I had another Interface called Intermediate. And then I made A and B as child classes of intermediate. Hope this helps!

**Comment by xmlew** [comment]
I did the same thing as @ReganKvioke. Since A, B and C all implement Intermediate, other can reference an object from either class A, B or C! I think both interface or abstract class works, but I did interface as it was easier for me haha.

**Comment by nuzzul** [comment]
alright thanks guys! i just got confused at the qn where it says "design should be readily extensible for other classes". so i thought other could be of type string/int etc as well
