### ISSUE TITLE
Final files format? .java?.jsh?

### ISSUE THREAD

**Issue by Ahuanglovescoding** [nus-cs2030/2122-s2#586]
Hello:) Just want to check for final do we create a .jsh file for each question?

**Comment by alantay11** [comment]
I think we'll get files for each question with the correct extensions like the mock paper

**Comment by Ahuanglovescoding** [comment]
> I think we'll get files for each question with the correct extensions like the mock paper

Thanks for replying! so the files are provided to us. make sense.
