### ISSUE TITLE
PYP 17/18

### ISSUE THREAD

**Issue by michael192002** [nus-cs2030/2122-s2#589]
# Source
Put the year/semester and the question number

## Description 
Hi, does anyone know how to approach this question?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/97863846/165292904-234905cf-8c96-495a-85e5-7d5c4c1747fb.png)

**Comment by Swagston20** [comment]
List<Customer> customers = new ArrayList<>(); double now = 0;
for (int i = 0; i < numOfCustomers; ++i) {
Customer customer = new Customer(); 
customer.setArrivalTime(now); 
customer.setServiceTime(rng.genServiceTime()); 
customers.add(customer);
now += rng.genArrivalTime(); 
}
