### ISSUE TITLE
Comparable Vs Comparator

### ISSUE THREAD

**Issue by jlee1007** [nus-cs2030/2122-s2#59]
Hi all,

Noted that in Lab 4 we worked with both Comparable & Comparator. 
Comparable mainly overrides the compareTo in the booking class while Comparator was for the ImList sort.

However I am still quite confused on the difference between Comparable & Comparator and when should we each either one.
Also, for Booking class, could we have just included a compareTo method w/o implementing Comparable?
Last, while reading online i note some example of Comparable do not return -1 or 1, is this correct?

Thanks!

**Comment by shotnothing** [comment]
Comparable:
- Only one sorting sequence (up to you to @Override compareTo() )
- Your original class has to implement the comparable interface, i.e. quite invasive
- Mostly shorter and cleaner: Collections.sort(list), no additional "outside" comparing function

Comaparator
- Option for multiple sorting sequences
- You implement an additional comparator class, don't have to change your original class
- Need to write more things

Do note that to sort a comparable in a method that expects comparator (e.g. ImList), you can use a static method (that I assume returns a comparator), Comaprator.naturalOrder(), in place of a comparator.

**Comment by jlee1007** [comment]
@shotnothing thank you so much for the clarification! just to confirm when you say comparable only works for one sorting sequence whereas comparator works for multiple one example would be lets say Comparator<Shape> we can extend to cr8 shape area comparators and perimeter comparators, but if I were to implement the comparable interface i would be only able to pick one?

So does this also mean for simpler codes it would be better to implement comparable since its more straightforwards? thanks!

**Comment by shotnothing** [comment]
> Comparator we can extend to cr8 shape area comparators and perimeter comparators, but if I were to implement the comparable interface i would be only able to pick one
Yeap, u can make a whole bunch of different comparators but in comparable, you only have whatever u put in the `compareTo` method and that's it.

If this were cs2040 I would say yes, but in this module I think it depends, you have to read the task and plan ahead (i.e. are they forcing you to use one? Is there a later part where they expect you do compare on another sequence? etc.). Given a choice, I would stick to comparable and `Comparator.naturalOrder()`.

**Comment by jlee1007** [comment]
Nice, thanks so much @shotnothing!
