### ISSUE TITLE
Mock Qn 1 Private Final?

### ISSUE THREAD

**Issue by shotnothing** [nus-cs2030/2122-s2#591]
Hi guys, for the qn 1 of the mock finals, why are we able to access newList.list at all, given that it is declared private final? Like I know its not really part of the question but isn't it actually fundamentally wrong?

![image](https://user-images.githubusercontent.com/16388604/165332977-7ff6f609-8b6f-4835-8ee1-86af73e16d81.png)

This is how I thought add would be implemented (before using update())

```
ImList<T> add(T elem) {
	return new ImList(list.add(elem));
}
```

I have tested it out and for the original code, even within the same method signature ImList::add(T) its giving me (as expected):

![image](https://user-images.githubusercontent.com/16388604/165334075-5730206a-f429-4a52-98dd-fb2d741c4dba.png)

Am I missing something here?

**Comment by ldkai** [comment]
Hi, I am not sure if I am correct but if i recall correctly it's because lists are mutable structures in java? which is why ImList was introduced... (someone pls correct me if im wrong HAHA)

**Comment by shotnothing** [comment]
> Hi, I am not sure if I am correct but if i recall correctly it's because lists are mutable structures in java? which is why ImList was introduced... (someone pls correct me if im wrong HAHA)

Yeah lists are mutable but I think I dont think you can call a List from a ImList that has it as private final, as the issue is not with mutability but with being able to access the thing in the first place?

**Comment by shotnothing** [comment]
> Hi Im not too sure whether I understand your question correctly, but isn't the ImList in the question similar to our given ImList that we have been using all this while?
> 
> If I understand your question correctly, the abstraction barrier is not broken when an object of type `ImList` assesses the instance variables of another `ImList` object (referenced from Recitation 1 Guide)

omg ur right haha I should have just referred to one of my many ImList.java files. Must be an issue with my testing then, thanks!

**Comment by ldkai** [comment]
> > Hi, I am not sure if I am correct but if i recall correctly it's because lists are mutable structures in java? which is why ImList was introduced... (someone pls correct me if im wrong HAHA)
> 
> Yeah lists are mutable but I think I dont think you can call a List from a ImList that has it as private final, as the issue is not with mutability but with being able to access the thing in the first place?

ahhh.. i misunderstood ur qns my bad hha
