### ISSUE TITLE
CS2030 Forum Guidelines

### ISSUE THREAD

**Issue by RussellDash332** [nus-cs2030/2122-s2#6]
# Welcome to CS2030 Forum using Github Issues!
We will be using Github Issues for CS2030 Q&A instead of the LumiNUS Forum!

Please take note of the following etiquette. Let's make this a pleasant place for online interaction and peer learning!

1. If you have a new question, create a new post instead of posting it as a reply on someone else's unrelated question.

2. Think carefully about what you are posting and write a succinct summary (or post title) that describe the question. E.g., the title "Java" is too generic. "Unable to install Java?" is better. "Installing Java on Windows 10 gives the error 'permission denied'" is even better.

3. Avoid posting questions that have been asked before (read through what others have posted before posting yourself) or have been answered in the notes and handouts (read through carefully what we released to the class)

4. Github Issues supports powerful formatting. If your post or reply contains code, use proper formatting to make your post readable. Markdown is powerful in allowing you to write inline code (which is by adding triple backticks (` ``` `) before and after). For example:
    ```
    public void sayHello() {
        System.out.println("Hello World!");
    }
    ```

    Even better, you can give colors to the inline codes by adding the language after the first triple backticks. For example, doing

    ````
    ```java
    public void sayHello() {
        System.out.println("Hello World!");
    }
    ```
    ````

    will give you this.

    ```java
    public void sayHello() {
        System.out.println("Hello World!");
    }
    ```

5. If you post about a problem you faced, please provide all the information (what you have done, what error message you faced) to help the readers of this forum help you. E.g., "My program cannot compile. Can you please help?" is not a meaningful post.

*[Guidelines adapted from CS2030 AY20/21 Semester 2 Forum Guidelines]*

Hopefully, you have a wonderful time taking this module and learning Java!

**Best regards,**
**Russell**
Your lovely CS2030 alumni 😊

**Comment by BrendanCheong** [comment]
Eh walao leave some class part marks for the rest of them leh

**Comment by RussellDash332** [comment]
Hi Brendan! Nice to see you again, so exciting to learn CS2030 from you!

**Comment by BrendanCheong** [comment]
'_>'

**Comment by upabove122** [comment]
Of cos its @RussellDash332 HAHA

**Comment by RussellDash332** [comment]
> Of cos its @RussellDash332 HAHA

Hi @upabove122, it's been a while!

**Comment by wilsonwid** [comment]
Of course it's @RussellDash332 everytime :)

**Comment by RussellDash332** [comment]
> I really want to pin this post...

Wait you can't? 😦

**Comment by RussellDash332** [comment]
> I've pinned this issue. Now it is more visible. Can I close this @RussellDash332?

Feel free. I'm just putting the message here anyways

**Comment by RussellDash332** [comment]
@danqiye1 I can close it on my end. Thanks!

**Comment by francisyzy** [comment]
Oh no what happened to our semester's issues page? Got some PYP resources for them to use

**Comment by RussellDash332** [comment]
> Oh no what happened to our semester's issues page? Got some PYP resources for them to use

No idea, but we can recover from email

**Comment by FYimu** [comment]
HAHA Russell the God of Forum Forever
