### ISSUE TITLE
Failed Test Case 5: Getting wrong output

### ISSUE THREAD

**Issue by jeanyeeee** [nus-cs2030/2122-s2#60]
hello! I'm getting the wrong output for this level and I'm not sure how I should fix my code

<img width="473" alt="image" src="https://user-images.githubusercontent.com/87226663/155869762-443c9961-7187-4014-8c26-d5694c3e7b25.png">

**Comment by haoyangw** [comment]
Seems like your code sorts by distance before sorting by price sometimes when it's not supposed to. You should only sort by distance if the price is the same, so could you check if you implemented a price equality check correctly?

**Comment by jeanyeeee** [comment]
> Seems like your code sorts by distance before sorting by price sometimes when it's not supposed to. You should only sort by distance if the price is the same, so could you check that before comparing by distance, you implemented a price equality check correctly?

Thank you! I changed my compareTo(Booking other) method to compare based on price first then waitingTime, it passed the test case :)
