### ISSUE TITLE
Level 6: How to define the add method

### ISSUE THREAD

**Issue by teresasee** [nus-cs2030/2122-s2#61]
## Description 
The question told us to create a SafeEntry class which can connect directly to the DataStore unlike a Token which needs to connect to Registry then to DataStore. However I am having trouble defining the add method without the use of instanceof to check whether the object is a Token or a SafeEntry. Are there any approaches I can take without using instanceof?

## Idea 
My idea was to have Token and SafeEntry inherit from a parent class/interface Device. Then I implement a method in Token and SafeEntry so that for SafeEntry it will connect to the DataStore while for Token it will call the method in Registry which connects to DataStore. But then I think this will cause Token to have dependency on Registry (not allowed). Any thoughts??

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/99934329/155878495-66b59347-9c74-473a-8807-da31f1d5488d.png)

**Comment by wk1267** [comment]
I have really no clue if this works cos I am not even close to Level 6 lol but maybe you can try comparing the output of toString()  of either device. I don't think this requires a parent class Device because all objects have toString()s defined

**Comment by Alexius0123** [comment]
Having Token and SafeEntry inherit from Device is on the right track. What I did was to have Token have a method that outputs a string that was then passed into Registry, where Registry would output the DataStore with the string from Token. For SafeEntry, there will be a similar method, but it will only pass an arbitrary string, like "SafeEntry". When this "SafeEntry" string is passed into Registry, it will realise that it is not a token, and do something else. This skirts the need for instanceof.

Hope this helps!
