### ISSUE TITLE
Position of + in string concatonation

### ISSUE THREAD

**Issue by mamayuan** [nus-cs2030/2122-s2#65]
# Summary

Position of + in string concatonation

## Description:

Since a Java sentence ends with a semicolon, we can break a sentence into multiple lines before it ends. When I was wrting the toString method for my Booking class, at first(screenshot 1), my file was complilable without errors, but when I test the output on jshell, nothing is returned. I submit on codecrunch, the output is also blank. After that, I spent some time trying to debug the code. Then I attempted to move the + sign to the next line(screenshot 2), and then the output is shown. May I know why this happens? I am very confused about this behaviour.

## Screenshots

Screenshots (if any)
Screenshot 1
![Screenshot 2022-02-28 091906](https://user-images.githubusercontent.com/97677245/155909890-c7aa38d9-2dbe-42d3-a900-309f66d4fd08.jpg)

Screenshot2
![Screenshot 2022-02-28 091951](https://user-images.githubusercontent.com/97677245/155909905-865225b7-09d9-4232-a538-2ba7ae57e53f.jpg)

**Comment by szeying02** [comment]
This happened to me a couple of times before, and I found that the reason behind the error was more or less something to do with the methods used in the `toString()` method. Perhaps you could check those instead?

**Comment by shotnothing** [comment]
Nothing is returned could mean that your `@Override toString()` has an error, but fails silently. Try and explicitly call whatever.toString() in jshell, an error should pop up.

**Comment by summerthia02** [comment]
I'm not sure if this will solve the problem but whenever you break a line because a particular line is too long, you have to indent it by 4 spaces. 
e.g. 
return this.booking + .....
    + this.taxi
^^ has to be indented

**Comment by shotnothing** [comment]
> I'm not sure if this will solve the problem but whenever you break a line because a particular line is too long, you have to indent it by 4 spaces. e.g. return this.booking + this.whatever .... + this.taxi ^^ has to be indented (the dots are spaces)

Based on https://www.comp.nus.edu.sg/~cs2030/style/, it should be 8 spaces

**Comment by celine-chung** [comment]
Not too sure why this error occurs but based on the Lab slides, "it is usually appropriate to wrap lines after operators" (like your case here after the + sign) "or at appropriate junctures for Strings (e.g. after a full-stop)". Following these conventions should help you avoid such unexpected errors!
