### ISSUE TITLE
When you want to instantiate the abstract class...

### ISSUE THREAD

**Issue by YohKato** [nus-cs2030/2122-s2#66]
Abstract classes (and interfaces) cannot be instantiated. However, sometimes, I find the need for more generalized class to be initialized at first so that it can be replaced with more specific classes later. How I went around was to make a parent class (ie. normal class) instead with implementation of the interface, while putting dummy values to the constructor values that needs to be filled in. But I feel that this way, it works but losing out the advantages of abstract classes that I wanted. Are there any smarter way to get around with the issue of instantiating the abstract classes? or any solutions / suggestions in such cases?

**Comment by wk1267** [comment]
If the original "parent"/abstract class does not need to exist by itself then there is no need to instantiate it (i think). So you can still make it abstract without losing any functionality

**Comment by YohKato** [comment]
Thank you both. I guess based on what you two have discussed, I have to really think about whether I need to create is concrete class, abstract class, or even interface before solving any issues: including the consideration of the need of instantiation.
