### ISSUE TITLE
Trouble with using Comparator

### ISSUE THREAD

**Issue by wayneonn** [nus-cs2030/2122-s2#69]
# Summary

The objective is to use a comparator to compare fares between services and to deliver the best service

## Description:

The idea is that using `ImList<Service> services = driver.getServicesOffered();` at line 14, this list would have stored the list of services `NormalCab` would have (JustRide and TakeACab). I am trying to compare this list of services that I have to compare the computed fares at the `Comparator` and churn out the best service. Any ideas on how to proceed with this? 

## Screenshots

![Capture 1](https://user-images.githubusercontent.com/97547503/156177967-16daf7b6-0fcd-41dc-b550-0defaf6e9cfc.PNG)

**Comment by loqir** [comment]
hi i think to get the cheaper service you dont have to sort the list since there are only 2 elements. 
you can try something like getting the first service in the list and compute its fare by taking in the request, and directly compare it with the fare of the second service , then return the service with a lower fare by using if else statements.

**Comment by wayneonn** [comment]
Hi, thanks for your response. This is actually a hypothetical question if the client decides to include more services (beyond JustRide and TakeACab), so this is why I am trying to include an `ImList<Service> services` to resolve this which I am currently trying to solve by using `Comparator`.

**Comment by loqir** [comment]
ohh in that case i think returning s1.computeFare(this.request) - s2.computeFare(this.request) in the compare method will sort the services list in ascending order(by fare) . Also, i think the return type of the method should be int

**Comment by wayneonn** [comment]
Thanks now it works, a silly mistake I made that got me stuck 🤣
