### ISSUE TITLE
Level 5 Lineage ImList<Case>

### ISSUE THREAD

**Issue by tanweiming00** [nus-cs2030/2122-s2#76]
Have anyone tried out the Lineage ImList<Case> method? How did you all implement? 

Do you all populate it under Case or ContactCase class? 

![image](https://user-images.githubusercontent.com/97489703/156909098-ab2c4443-db99-406a-8305-705ac05d6179.png)

**Comment by alantay11** [comment]
If your constructor sends in the B234 person and the ART test to super a new case, I think you can just print it normally? You can just use the toString method in the parent.

**Comment by tanweiming00** [comment]
> If your constructor sends in the B234 person and the ART test to super a new case, I think you can just print it normally? You can just use the toString method in the parent.

You are right! Thanks!!

**Comment by tanweiming00** [comment]
> If your constructor sends in the B234 person and the ART test to super a new case, I think you can just print it normally? You can just use the toString method in the parent.

Have you tried the getLineage portion? How did you implement it?

**Comment by jingyulim1** [comment]
The lineage shows how one case is linked to another and ContactCase has the source of contact (the exisiting case). 

We can treat Case as the first case, where Lineage would just return an ImList of itself. Then, for ContactCase, Lineage would just return the source of contact's lineage + itself.

**Comment by tanweiming00** [comment]
> The lineage shows how one case is linked to another and ContactCase has the source of contact (the exisiting case).
> 
> We can treat Case as the first case, where Lineage would just return an ImList of itself. Then, for ContactCase, Lineage would just return the source of contact's lineage + itself.

I would like to clarify for your second paragraph, does “treating Case” refer to the Source of case or the linked case? 

Where do you keep the ImList<Case>? Is it at Case or ContactCase? 

Sorry cause your explanation isn’t that clear.

**Comment by jingyulim1** [comment]
I think I clarified with you in private, but for others to refer:

Ok, because Case has no source of infection, it is the earliest case. So the lineage would just be itself. So you can return a New ImList<Case> of itself.

Then for ContactCase, we already have the source as an attribute(we store the Case which it gets the infection from in ContactCase). So, we need to get the source's lineage and add itself in. We can return source.getLineage().add(this)

This way, there is no need to store the ImList<Case> anywhere, since the list will be generated only when the getLineage is called

**Comment by tanweiming00** [comment]
Thanks!!

**Comment by wayneonn** [comment]
Hi how did yall come around the issue where `ContactCase `can take in a `Test `but then it would contradict the super class of `Case` where it can only take `PCR`, can't think around it

**Comment by tanweiming00** [comment]
> Hi how did yall come around the issue where `ContactCase `can take in a `Test `but then it would contradict the super class of `Case` where it can only take `PCR`, can't think around it

I override the method iirc or that I created a standalone private static to populate it out.

**Comment by wayneonn** [comment]
Sorry may have phrased it wrongly, I would start a new thread on this. Thanks for assisting me
