### ISSUE TITLE
Level 5 ContactCase unable to take in Test due to inheritance

### ISSUE THREAD

**Issue by wayneonn** [nus-cs2030/2122-s2#77]
# Summary
Level 5 ContactCase unable to take in Test due to inheritance

## Description 
I'm facing an issue where the constructor for `ContactCase `is required to take in `Person`, `Test `and `Case`, but due to inheritance extending from `Case`, the super constructor from Case is required to take in `Person `and `PCR `test only. This results in it contradicting the super class as `PCR `has to be taken in.

From Level 3 to show that only `PCR `is accepted
```
jshell> new Case(new Person("A123", "PP", 8), new ART("C"))
|  Error:
|  incompatible types: ART cannot be converted to PCR
|  new Case(new Person("A123", "PP", 8), new ART("C"))
|   
```

From level 5 is able to take in any valid tests
`new ContactCase(new Person("B234", "M", 7), new ART("CT"), c)`

**Comment by tanweiming00** [comment]
I did this in ContactCase class --> private static ImList<Test> populateTestHistory(Test test)  while i did this in Case class ImList<Test> populateTestHistory(PCR test)

**Comment by jingyulim1** [comment]
You can consider using the other constructors in Case. Eg if you have a constructor that takes in ImList<Test>, in the super you can create a new ImList and put the ART test in it.

**Comment by wayneonn** [comment]
Thanks all! I did consider using that constructor containing the ImList, but I made it private as I thought it might produce something undesirable with the constructor. I will implement that since it seems I'm stuck 🙃

**Comment by wayneonn** [comment]
Oh dear, I didn't realise that making it not private would push two errors instead of the expected one. Does it mean that I should not think of making other constructors not specified in `Case` right?
![PCR](https://user-images.githubusercontent.com/97547503/156924924-59c3b078-83f1-4270-95aa-024f59b47353.PNG)

**Comment by jingyulim1** [comment]
I think you should only have 1 constructor in Case that takes in 2 arguments, try to see if you can utilize those constructor with 3 or more arguments if possible. At worst, you can make a new constructor, but that may affect the similiarty for grading.

**Comment by michael192002** [comment]
For me, I implemented a constructor with 3 arguments in the Case class, and selected the protocol in the ContactCase class before calling the parent class constructor

**Comment by michael192002** [comment]
I used a constructor in the Case class taking in a Person, list of results, and protocol; and because you are selecting the protocol in the child (as jingyu said) before calling the parent class, the difference should be quite modest (total changes in around 6 lines).

**Comment by jlee1007** [comment]
you cant inherit because pcr is a test but test may not always be a pcr. i created a new constructor for this, might affect similarity marks but i think it would be better to get the job done!

**Comment by JhChee18** [comment]
Regardless of adding a new `populateTestHistory(Test test)` in ContactCase or overloading the constructor of Case, either way could affect the similarity grading. For this case, I think overloading the Case is the easier way to be done.

**Comment by wayneonn** [comment]
Thanks all I have managed to complete, really appreciate each one of your guidance 😊
