### ISSUE TITLE
Codecrunch error level 5

### ISSUE THREAD

**Issue by wk1267** [nus-cs2030/2122-s2#79]
# Summary
Hi all, when trying to submit and clear level 5 on Codecrunch, they gave me lots of errors which doesnt appear when I run my code on my jshell when I try to open all the files (using jshell *.java *.java *.java *.java *.java ...). My code works and gives me the correct output on my jshell but not on Codecrunch. Has anyone faced a similar problem? If so, how did you solve them?
Thank you.

## Screenshots (if any): 
Insert Images here if necessary
<img width="550" alt="Screenshot 2022-03-08 at 6 17 24 PM" src="https://user-images.githubusercontent.com/97509680/157216540-00711757-f199-4023-ae5e-4ddbac68da50.png">
<img width="693" alt="Screenshot 2022-03-08 at 6 19 53 PM" src="https://user-images.githubusercontent.com/97509680/157216908-5dadb90d-1c83-4108-ab48-92fad78be903.png">

**Comment by jingyulim1** [comment]
I am not sure if this is the problem, but does your protocol interface only have 1 Next method defined?

**Comment by wk1267** [comment]
Hi all, thanks for your suggestions and feedback! It turns out my protocol interface had 2 next methods defined, which was not allowed. The protocol interface should have only 1 next method defined (and a toString method defined).
