### ISSUE TITLE
Incompatible Types vs No suitable constructor found

### ISSUE THREAD

**Issue by shotnothing** [nus-cs2030/2122-s2#80]
![image](https://user-images.githubusercontent.com/16388604/157547560-ea54e8e1-2cb3-4afc-9816-3eca54e26791.png)

Hi guys, anyone faced this problem that needs to force an Incompatible Types error to appear instead of no suitable constructor found?

**Comment by jingyulim1** [comment]
Seems like you have another constructor that takes in Case and Test as arguments, which causes both constructors to be considered when you try to construct a Case with 2 arguments.

To get the error on the left, you can only have 1 constructor with 2 arguments.

**Comment by shotnothing** [comment]
Ohh I see. It feels a bit arbitrary forcing you to change your code to get the error they want, when it doesn't actually violate any OOP principles. Thanks anyway!
