### ISSUE TITLE
Level 1 Pirority Queue

### ISSUE THREAD

**Issue by wayneonn** [nus-cs2030/2122-s2#87]
# Summary
Unable to understand the rationale behind how the queue is sorted

## Description 
I struggle to understand why the event time is sorted in this behaviour. Hope anyone who knows why can enlighten me on this, thanks!

## Screenshots (if any): 
![Comparison](https://user-images.githubusercontent.com/97547503/158020069-9b58e2ac-e0fb-4c0a-8b80-1877196b8f63.PNG)

**Comment by shotnothing** [comment]
I'm suspect its because the way data is stored internally in a priority queue is in a heap, which is not sorted, and it doesn't really matter anyway. As long as the the output is consistent and poll() ends up fetching the highest priority, it should be fine?

**Comment by wayneonn** [comment]
Thanks for the detailed explanation, I understand it better now!
