### ISSUE TITLE
Unable to import cs2030.util.Pair

### ISSUE THREAD

**Issue by wayneonn** [nus-cs2030/2122-s2#88]
# Summary
Unable to import cs2030.util.Pair

## Description 
I am facing an issue where jshell throws an error when I want to import the `cs2030.util.Pair` class into my `EventStub` class. It is a run-time error as it was able to compile successfully. 

Strangely, CodeCrunch was able to pass the test case without any issues. Have looked up online resources for help and it mentions that I may have 2 classes of the same name conflicting, but I have checked my packages and even deleted and recompiled my packages, but to no avail. Hope if anyone have overcame this issue could help comment on this, thanks!

```
package cs2030.simulator;

import java.util.Optional;
import cs2030.util.Pair;

interface Event {
    Pair<Optional<Event>, Shop> execute(Shop shop);
}
```
Given `Event` template interface for reference. Importing the package with the `Pair` class caused this issue, but if I were to remove anything associated with `Pair` on the classes of `cs2030.simulator` package it would work fine.

```
jshell> new Customer(3, 0.7)|  Error:
|  a type with the same simple name is already defined by the static single-type-import of Pair
|  new Customer(3, 0.7)
|  ^
```
jshell output

**Comment by jingyulim1** [comment]
Issue may be that you jshell Pair.java, causing there to be 2 Pair.java. (one from package, one from you jshell-ing Pair.java)

**Comment by shotnothing** [comment]
To add on, since everything is in a package, I think that you should not open Pair.java in jshell but just open the immediate classes that you are testing. This allows you to check if your dependency importing is correct.

**Comment by wayneonn** [comment]
I see, yep I will stick to just opening the immediate classes for testing since it would work without me packaging it separately to each folder. Thanks all!
