### ISSUE TITLE
Event Interface

### ISSUE THREAD

**Issue by szeying02** [nus-cs2030/2122-s2#90]
## Description
In the level 1, it is mentioned that an event is associated with a customer and an event time, which implies the use of class (abstract / concrete to initialise the variables / properties). However, in level 2, an Event interface was given, allowing for modification. Is it possible to directly use an abstract class for Event? Or should we just expand the interface's list methods? Thanks!

**Comment by wayneonn** [comment]
I think you should probably focus on the latter, where it's to just expand on the interface since the template has been given as an interface. Hope it helps.

**Comment by Yang990121** [comment]
I tired to make Event a concrete class or abstract class, code crunch passed me
