### ISSUE TITLE
There is some typo in the Level 1 to 4 test cases given to us, take note guys

### ISSUE THREAD

**Issue by Yang990121** [nus-cs2030/2122-s2#96]
# Summary
Some typos in the test cases given

## Description 
Basically all the 
- "serves by server 1" is actually "serves by 1'
- "wait at server 1" is actually "wait at 1"
- "done serving by server 1" is actually "done serving by 1"

## Screenshots (if any): 
![camphoto_959030623](https://user-images.githubusercontent.com/65878741/158506739-48c9e791-1d16-4e7e-a974-6e8270a4e063.JPG)
![camphoto_33463914](https://user-images.githubusercontent.com/65878741/158506703-9f91f74c-d862-4173-893c-7d30c45675d9.JPG)

**Comment by LauWyeRock** [comment]
nice thank you

**Comment by spicyseaweed** [comment]
thank you!

**Comment by ignatiustan123** [comment]
thank you

**Comment by waisheen** [comment]
thank you!

**Comment by Noel-Lee** [comment]
thank you :)

**Comment by Kent-twl** [comment]
thank you!!!!
