### ISSUE TITLE
Creating Packages and Compiling it and Running it

### ISSUE THREAD

**Issue by hengyjj** [nus-cs2030/2122-s2#99]
# Summary

## Description 
Hello guys! I am having some issues as I am not too sure how to create a package? I first created a folder and then I created a java file in it. 

![image](https://user-images.githubusercontent.com/77519191/158543618-5c333c63-85f0-4435-b171-3e35bfd0c28b.png)

Just like to check if this is the right way of creating a package?

May I also know do I access this package from other files just by typing "import cs2030.util.MyPackage"? 

Thank you for your help!

## Screenshots (if any): 
Insert Images here if necessary

**Comment by yongchein-o** [comment]
if you have another class in the same package. 
```
package cs2030.util;
class A { } 
```
there is no need to import. otherwise I believe if you want to use MyPackage, you'd have to import it. 
```
package cs2030.anotherPackage; 
import cs2030.util.MyPackage; 
class A {} 
```

**Comment by hengyjj** [comment]
> if you have another class in the same package.
> 
> ```
> package cs2030.util;
> class A { } 
> ```
> 
> there is no need to import. otherwise I believe if you want to use MyPackage, you'd have to import it.
> 
> ```
> package cs2030.anotherPackage; 
> import cs2030.util.MyPackage; 
> class A {} 
> ```

I am not too sure. I followed what CC said by splitting it into 2 packages, cs2030.util and cs2030.simulator and tried importing it but it doesn't work.

![image](https://user-images.githubusercontent.com/77519191/158566030-4483173f-e79d-4499-8ec1-2ef1e406468c.png)

But this error pops up
![image](https://user-images.githubusercontent.com/77519191/158566128-d8093b56-44b1-4742-9b32-048f4866de7c.png)

**Comment by SpectralMusket** [comment]
you typed `import package cs2030.util` instead of `import cs2030.util` my man

**Comment by szeying02** [comment]
And take note not to `jshell` / open in jshell any package that is being imported by another java file (speaking from experience)!

**Comment by hengyjj** [comment]
thank you guys!
